junit-team/junit-framework

- junit-engine-api/src/main/java/org/junit/gen5/engine/AbstractTestDescriptor.java
- junit-engine-api/src/main/java/org/junit/gen5/engine/EngineDescriptor.java
- junit-engine-api/src/main/java/org/junit/gen5/engine/EngineExecutionContext.java
- junit-engine-api/src/main/java/org/junit/gen5/engine/TestDescriptor.java
- junit-engine-api/src/main/java/org/junit/gen5/engine/TestEngine.java
- junit-engine-api/src/test/java/org/junit/gen5/engine/AbstractTestDescriptorTest.java
- junit-launcher/src/main/java/org/junit/gen5/launcher/Launcher.java
- junit-launcher/src/main/java/org/junit/gen5/launcher/TestPlan.java
- junit4-engine/src/main/java/org/junit/gen5/engine/junit4/DescriptionTestDescriptor.java
- junit4-engine/src/main/java/org/junit/gen5/engine/junit4/JUnit4SpecificationResolver.java
- junit4-engine/src/main/java/org/junit/gen5/engine/junit4/JUnit4TestDescriptor.java
- junit4-engine/src/main/java/org/junit/gen5/engine/junit4/JUnit4TestEngine.java
- junit4-engine/src/main/java/org/junit/gen5/engine/junit4/RunnerTestDescriptor.java
- junit4-launcher-runner/src/main/java/org/junit/gen5/junit4runner/JUnit5RunnerListener.java
- junit4-launcher-runner/src/main/java/org/junit/gen5/junit4runner/JUnit5TestTree.java
- junit5-engine/src/main/java/org/junit/gen5/engine/junit5/JUnit5TestEngine.java
- junit5-engine/src/main/java/org/junit/gen5/engine/junit5/descriptor/ClassTestDescriptor.java
- junit5-engine/src/main/java/org/junit/gen5/engine/junit5/descriptor/JUnit5TestDescriptor.java
- junit5-engine/src/main/java/org/junit/gen5/engine/junit5/descriptor/MethodTestDescriptor.java
- junit5-engine/src/main/java/org/junit/gen5/engine/junit5/descriptor/SpecificationResolver.java
- junit5-engine/src/main/java/org/junit/gen5/engine/junit5/execution/TestExecutionNode.java
- junit5-engine/src/test/java/org/junit/gen5/engine/junit5/JUnit5TestEngineTests.java
- junit5-engine/src/test/java/org/junit/gen5/engine/junit5/descriptor/SpecificationResolverTest.java
- junit5-engine/src/test/java/org/junit/gen5/engine/junit5/stubs/TestEngineStub.java
- sample-project/src/test/java/com/example/JUnit4SamplesSuite.java
I used the days to push the idea of an hierarchy of test descriptors further.
Not the engine only gets an EngineDescriptor for resolution and just adds children to it.
This makes a lot of code easier through the whol code base. Especially
- Launcher
- JUnit5TestEngine
- SpecificationResolver
- JUnit5TestTree
JUnit4TestEngine should also become simpler but I haven't had the time to look at it - just did the minimum to keep it working.
If one accepts TestDescription to be a composite, a lot of code can move to the appropriate node types. I only scratched the surface of it.
Please have a look at it and consider it as a basis for discussion.
> Hierarchical Test Descriptor

- junit-commons/src/main/java/org/junit/gen5/commons/util/ReflectionUtils.java
- junit-console/src/main/java/org/junit/gen5/console/TestSummaryReportingTestListener.java
- junit-engine-api/src/main/java/org/junit/gen5/engine/AbstractTestDescriptor.java
- junit-engine-api/src/main/java/org/junit/gen5/engine/EngineDescriptor.java
- junit-engine-api/src/main/java/org/junit/gen5/engine/TestDescriptor.java
- junit5-api/src/main/java/org/junit/gen5/api/Context.java
- junit5-engine/src/main/java/org/junit/gen5/engine/junit5/descriptor/ContextTestDescriptor.java
- junit5-engine/src/main/java/org/junit/gen5/engine/junit5/descriptor/JUnit5Class.java
- junit5-engine/src/main/java/org/junit/gen5/engine/junit5/descriptor/JUnit5Context.java
- junit5-engine/src/main/java/org/junit/gen5/engine/junit5/descriptor/JUnit5Testable.java
- junit5-engine/src/main/java/org/junit/gen5/engine/junit5/descriptor/JUnit5TestableFactory.java
- junit5-engine/src/main/java/org/junit/gen5/engine/junit5/descriptor/SpecificationResolver.java
- junit5-engine/src/main/java/org/junit/gen5/engine/junit5/execution/ContextTestExecutionNode.java
- junit5-engine/src/main/java/org/junit/gen5/engine/junit5/execution/TestExecutionNodeResolver.java
- junit5-engine/src/main/java/org/junit/gen5/engine/junit5/testers/CanBeTestClass.java
- junit5-engine/src/main/java/org/junit/gen5/engine/junit5/testers/IsTestContext.java
- junit5-engine/src/main/java/org/junit/gen5/engine/junit5/testers/ReflectionObjectTester.java
- junit5-engine/src/test/java/org/junit/gen5/engine/junit5/JUnit5TestEngineTests.java
- junit5-engine/src/test/java/org/junit/gen5/engine/junit5/descriptor/SpecificationResolverTest.java
- sample-project/build.gradle
- sample-project/src/test/java/com/example/HierarchyTestCase.java
- sample-project/src/test/java/com/example/JUnit4SamplesSuite.java
- sample-project/src/test/java/com/example/SampleTestCase.java
One more pull request. I based this branch on Stefan's branch "contextsupport", fixed the resolver problems and merged it with current master.
The PR supports the resolution of nested contexts (inner classes with annotation @Context).
It does not yet execute them (i.e. ContextExecutionNode just skipps everything).
> Provide support for nested contexts

- documentation/src/docs/asciidoc/writing-tests.adoc
This small patch fixes the documentation for inner class sample.
---
> fix documentation for test inner class

- junit-tests/src/test/java/org/junit/gen5/engine/junit5/descriptor/ExtensionContextTests.java
- junit-tests/src/test/java/org/junit/gen5/engine/junit5/descriptor/ExtensionValuesStoreTest.java
- junit5-api/src/main/java/org/junit/gen5/api/extension/ExtensionContext.java
- junit5-engine/src/main/java/org/junit/gen5/engine/junit5/descriptor/AbstractExtensionContext.java
- junit5-engine/src/main/java/org/junit/gen5/engine/junit5/descriptor/ExtensionValuesStore.java
- junit5-engine/src/main/java/org/junit/gen5/engine/junit5/descriptor/NamespacedStore.java
- sample-extension/src/main/java/com/example/mockito/MockitoExtension.java
- sample-extension/src/main/java/com/example/timing/TimingExtension.java
According to team decision today. Parameter order was changed as requested.
> Integrated ExtensionContext.getStore

- junit-gradle/src/test/groovy/org/junit/gen5/gradle/JUnit5PluginSpec.groovy
On my system it was actually D:\any instead of /any
Fixed by creating the canonical path for the assertion
---
> the spec failed because the path in args is OS dependent

- junit-launcher/src/main/java/org/junit/gen5/launcher/main/DefaultLauncher.java
- junit-launcher/src/main/java/org/junit/gen5/launcher/main/TestExecutionListenerRegistry.java
Rename `registerListener` to `registerListeners`.
---
> Rename registerListener to registerListeners.

- junit-launcher/src/main/java/org/junit/gen5/launcher/main/DefaultLauncher.java
- junit-tests/src/test/java/org/junit/gen5/launcher/main/DefaultLauncherTests.java
A `DefaultLauncher` with `TestEngine`s that have equal ids is unusable. It fails to discover or execute tests. Hence it should not be possible to create such a launcher.
---
> Engines for DefaultLauncher must have different ids.

- junit-tests/src/test/java/org/junit/gen5/api/AssertionsTests.java
- junit5-api/src/main/java/org/junit/gen5/api/Assertions.java
- This pr fixes #110 .
- I just added assetEquals for following primitive types.
- byte
- short
- int
- long
- char
- float
- double
---
> Add assertEquals for primitive types

- documentation/build.gradle
- documentation/src/docs/static/README.md
- Generate only index.html for User Guide
- Remove static files kept in master that were added every time to
gh-pages branch (now kept there)
- Use new directory structure for user guide (docs/current/user-guide)
Related issue: #205.
---
- Generate only index.html for User Guide
- Keep existing files in gh-pages branch
- Remove static files kept in master that were added every time to
gh-pages branch
- Use new directory structure (docs/current/user-guide)
> Generate and upload User Guide to new directory structure

- junit-console/src/main/java/org/junit/gen5/console/tasks/XmlReportWriter.java
- junit-console/src/main/java/org/junit/gen5/console/tasks/XmlReportsWritingListener.java
- surefire-junit5/src/main/java/org/junit/gen5/surefire/RunListenerAdapter.java
String.toString() just returns the string itself, so calling toString()
on a String instance is pointless.
This patch removes the occurrences of this faulty pattern from the
codebase, and replaces them with a straight-forward use of the strings
themselves.
---
Signed-off-by: Allon Mureinik <mureinik@gmail.com>
> Remove redundant toString() calls

- junit-console/src/main/java/org/junit/gen5/console/tasks/ColoredPrintingTestListener.java
- junit-tests/src/test/java/org/junit/gen5/console/tasks/ColoredPrintingTestListenerTests.java
Indentation for failed tests was a bit off because printed exception message could be a multi line string.
This PR fixes indentation by changing exception messages to contain same amount of spaces as the rest of the output.
Fixes #160 
---
> Fix indentation for failed tests in ConsoleRunner

- junit-engine-api/src/main/java/org/junit/gen5/engine/TestDescriptor.java
- junit-engine-api/src/main/java/org/junit/gen5/engine/support/descriptor/AbstractTestDescriptor.java
- junit-launcher/src/main/java/org/junit/gen5/launcher/TestPlan.java
- junit-launcher/src/main/java/org/junit/gen5/launcher/main/Root.java
- junit-tests/src/test/java/org/junit/gen5/engine/support/discovery/AbstractTestDescriptorTests.java
- junit5-engine/src/main/java/org/junit/gen5/engine/junit5/DiscoveryFilterApplier.java
Every visitor gets the instance of the TestDescriptor and a Runnable for deleting it from the hierarchy. Everybody who has access to a TestDescriptor can therefore delete it, but with an approach that is not obvious. That's why I added the delete method to the TestDescriptor interface because I think that it is easier to understand compared to the Runnable.
---
> Simplify interface of the TestDescriptor.Visitor.

- junit-launcher/src/main/java/org/junit/gen5/launcher/main/Root.java
The parameter is a descriptor, not an engine.
---
> name variable properly

- documentation/src/docs/asciidoc/extensions.adoc
- junit-tests/src/test/java/org/junit/gen5/engine/junit5/execution/JUnit5EngineExecutionContextTests.java
- junit-tests/src/test/java/org/junit/gen5/engine/junit5/extension/ExecutionConditionTests.java
- junit-tests/src/test/java/org/junit/gen5/engine/junit5/extension/sub/SystemPropertyCondition.java
- junit5-engine/src/main/java/org/junit/gen5/engine/junit5/Constants.java
- junit5-engine/src/main/java/org/junit/gen5/engine/junit5/JUnit5TestEngine.java
- junit5-engine/src/main/java/org/junit/gen5/engine/junit5/descriptor/ClassTestDescriptor.java
- junit5-engine/src/main/java/org/junit/gen5/engine/junit5/descriptor/MethodTestDescriptor.java
- junit5-engine/src/main/java/org/junit/gen5/engine/junit5/execution/ConditionEvaluator.java
- junit5-engine/src/main/java/org/junit/gen5/engine/junit5/execution/JUnit5EngineExecutionContext.java
Prior to this commit, there was no way to deactivate or turn off
support for conditional test execution. In other words, there was no
way to execute a `@Disabled` test and no way to deactivate custom
implementations of `ContainerExecutionCondition` or
`TestExecutionCondition`.
This commit addresses this issue by introducing support for supplying a
`junit.conditions.deactivate` pattern to the `Launcher` via a
configuration parameter in the `TestDiscoveryRequest`.
If the `junit.conditions.deactivate` pattern consists solely of an
asterisk (`*`), all conditions will be deactivated. Otherwise, the
pattern will be used to match against the fully qualified class name
(FQCN) of each registered condition. Any dot (`.`) in the pattern will
match against a dot (`.`) or a dollar sign (`$`) in the …
> Introduce deactivation mechanism for conditions

- junit-engine-api/src/main/java/org/junit/gen5/engine/support/descriptor/CompositeTestSource.java
- junit-tests/src/test/java/org/junit/gen5/engine/support/descriptor/CompositeTestSourceTests.java
This commit introduces a `CompositeTestSource` that can be used to hold one or more `TestSources`. This can be useful, for example, if the programming model for a particular testing framework relies on Java classes and associated scripts in the file system.
Issue: #271
---
> Introduce composite TestSource

- documentation/src/test/java/example/UsingTheLauncherDemo.java
Change the example in the documentation to use a more obvious name for the `TestDiscoveryRequest` variable
---
> Use variable "request" for TestDiscoveryRequest.

- junit-platform-console/src/main/java/org/junit/platform/console/tasks/ExecuteTestsTask.java
The TODO is there since the beginning. The current `Launcher` interface does no allow any configuration except of adding listeners.
---
> Remove abandoned TODO about configuring Launcher.

- documentation/src/docs/asciidoc/running-tests.adoc
- junit-platform-console/src/main/java/org/junit/platform/console/options/AvailableOptions.java
- junit-platform-console/src/main/java/org/junit/platform/console/options/CommandLineOptions.java
- junit-platform-console/src/main/java/org/junit/platform/console/tasks/ConsoleTask.java
- junit-platform-console/src/main/java/org/junit/platform/console/tasks/ExecuteTestsTask.java
- junit-platform-gradle-plugin/src/main/groovy/org/junit/platform/gradle/plugin/JUnitPlatformPlugin.groovy
- junit-platform-gradle-plugin/src/test/groovy/org/junit/gen5/gradle/plugin/JUnitPlatformPluginSpec.groovy
- platform-tests/src/test/java/org/junit/platform/console/options/JOptSimpleCommandLineOptionsParserTests.java
- platform-tests/src/test/java/org/junit/platform/console/tasks/ExecuteTestsTaskTests.java
In general I consider it helpful to always return a status code that is not 0 in case of a failure. This makes it easy for scripts to decide whether all tests succeeded. In addition I cannot imagine any use case that relies on returning 0 in case of a failure.
The old implementation returned the number of failing tests as status code if the flag `enable-exit-code` has been set. But this is only possible for a small number (< 256) of failing tests. The problem was that n*256 failing tests have been reported as 0 failing tests and therefore could not be distinguished from a successful run via status code.
The parser in `AvailableOptions` still accepts the `enable-exit-code` flag because the project is build with an older version of the Gradle plugin from …
> Always use status code on exit.

- junit-platform-console/src/main/java/org/junit/platform/console/options/AvailableOptions.java
This is a follow-up to e568a3563c417829a20eec988daa98797c8391b3. That commit removed support for the flag `enable-exit-code`. It is already deployed to the snapshot repository. Therefore we can now remove support for this flag from `AvailableOptions`.
---
> Don't accept flag enable-exit-code.

- junit-platform-console/src/main/java/org/junit/platform/console/tasks/DiscoveryRequestCreator.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/TestDiscoveryRequest.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/DiscoveryRequest.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/LauncherConfigurationParameters.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/TestDiscoveryRequestBuilder.java
- junit-platform-runner/src/main/java/org/junit/platform/runner/JUnitPlatform.java
Avoid code duplication with `TestDiscoveryRequestBuilder`. Having two objects with similar responsibility is confusing, too. For the reader it is unclear which one to use.
---
> Make DiscoveryRequest immutable.

- documentation/src/docs/asciidoc/api-evolution.adoc
This project uses the `@API` annotation for information about API compatibility. The rules defined for this purpose do not comply with the [semantic versioning specification](http://semver.org/).
---
> Remove section about semantic versioning.

- documentation/src/docs/asciidoc/writing-tests.adoc
User guide fix: #376 
I have found only 2 instances of `@InjectMock`.
---
> User guide fix: @InjectMock -> @Mock

- junit-platform-console/junit-platform-console.gradle
The script in the [M1 ConsoleLauncher-ZIP](https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console/1.0.0-M1/junit-platform-console-1.0.0-M1.zip) ends with
exec "$JAVACMD" "${JVM_OPTS[@]}" -classpath "$CLASSPATH" org.junit.platform.console.ConsoleRunner "$@"
But the class is now called `ConsoleLauncher`.
The proposed change seems to fix the only reference to `ConsoleRunner`, so I assume the script is generated from this information?
---
> Replace reference to `ConsoleRunner` with `ConsoleLauncher`

- documentation/src/test/java/example/TestingAStackDemo.java
According to our own documentation `assertThrows` should be used if the test does not deal with the return value of `expectThrows`.
---
> Use assertThrows instead of expectThrows.

- junit-platform-surefire-provider/junit-platform-surefire-provider.gradle
- junit-platform-surefire-provider/src/main/java/org/junit/platform/surefire/provider/JUnitPlatformProvider.java
- junit-platform-surefire-provider/src/main/java/org/junit/platform/surefire/provider/RunListenerAdapter.java
- junit-platform-surefire-provider/src/test/java/org/junit/platform/surefire/provider/JUnitPlatformProviderTests.java
- junit-platform-surefire-provider/src/test/java/org/junit/platform/surefire/provider/RunListenerAdapterTests.java
- junit-platform-surefire-provider/src/test/java/org/junit/platform/surefire/provider/TestPlanScannerFilterTests.java
Forking requires two methods to be implemented in JUnitPlatformProvider:
1) `#getSuites()` - defines set of test classes for the future forks to execute
2) `#invoke(Object)` - called inside a fork with a `Class` argument from (1)
This PR adds implementation of `#getSuits()` and alters `#invoke(Object)` to support forking. It also adds unit tests for all classes in junit-platform-surefire-provider module.
Fixes #362 #363 
---
> Add forking support in surefire provider

- junit-platform-commons/src/main/java/org/junit/platform/commons/meta/API.java
Making @API public allows Extension and TestEngine developers to adopt JUnit 5's API "typing".  This also makes the API tools proposed in #144 more useful as they'd be applicable to the other projects.
---
> Make @API public to allow Extensions and TestEngines to adopt API semantics

- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/DefaultLauncher.java
When creating a new TestEngine by extending HierarchicalTestEngine, there's a Precondition failure if the getId() method returns null, but an NPE is thrown if the discover() method returns null.  If the createExecutionContext() method returns null, it's up to the test engine to decide whether that's a problem.  This pull request adds a precondition (with message) after calling discover()  and before adding the engine's TestDescriptor to the root.
For reference, here's the stack trace that occurs if the discover() method returns null:
```
java.lang.NullPointerException
at org.junit.platform.launcher.core.Root.lambda$acceptInAllTestEngines$2(Root.java:85)
at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:600)
at org.junit.platform.launcher.core.Root.acceptInAllTestEngines(Ro …
```
> Eliminate NPE when TestEngine's discovery() method returns null

- junit-platform-commons/src/main/java/org/junit/platform/commons/meta/API.java
`API` annotation could be retrieved from byte code (e.g. by using `org.reflections`), however it would be much more convenient (for #144) to retrieve annotations via _Java Reflection_.
---
> Make @API annotation available via Java reflection

- junit-jupiter-api/src/main/java/org/junit/jupiter/api/Assertions.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/AssertionsTests.java
This commit introduces `assertTimeout()` methods in `Assertions` that support both lazy and preemptive timeouts for blocks of code supplied as lambda expressions.
For example, the following assertion would pass:
`assertTimeout(ofMillis(500), () -> Thread.sleep(10));`
Whereas, the following assertion would fail:
`assertTimeout(ofMillis(10), () -> Thread.sleep(500));`
The above examples execute the code block in the same thread as the caller. To perform the same assertion as the last example and have the code executed in a separate thread and then preemptively aborted, the above can be rewritten as follows.
`assertTimeoutPreemptively(ofMillis(10), () -> Thread.sleep(500));`
Issue: #438
---
> Introduce lambda based timeout assertions

- documentation/src/docs/asciidoc/writing-tests.adoc
Added a paragraph documenting the use of 3rd party matchers in JUnit Jupiter in section 3.4 of the user guide.
This resolves #428 
---
> Document interoperability with third-party assertion Matchers in User Guide

- build.gradle
This partially fixes #480, only calling `git status´ once per build. That's already a great improvement from 1.6s down to 0.7s for `gradle help`.
> Reduce configuration time impact of versioning plugin

- junit-platform-commons/src/main/java/org/junit/platform/commons/util/Preconditions.java
- platform-tests/src/test/java/org/junit/platform/commons/util/PreconditionsTests.java
- As discussed in #496
---
Precondition.notNull(Object[]).
Null elements in the collection will no longer be accepted. This
is part of #496.
> Make behavior of Precondition.notEmpty(Collection) consistent with

- documentation/src/test/java/example/TestingAStackDemo.java
- AfterPushing context contained a typo, `isEmpty()` is changed to `isNotEmpty()`. After pushing an element in a stack it is no longer empty. The display name is correct but method name was not reflecting the intention. 
---
There was a typo in `AfterPushing` context, `isEmpty` is changed to `isNotEmpty`
> Fixed typo in TestingAStackDemo

- junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/ExtensionContext.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/execution/ExecutableInvoker.java
This overload, just like the one on `TestReporter`, makes it easier to publish a single key-value pair.
There is also a small fix of a collection emptiness check in there.
---
> Add overload of 'ExtensionContext::publishReportEntry'

- junit-jupiter-api/src/main/java/org/junit/jupiter/api/Assertions.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/AssertionsTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/IterableFactory.java
This is a follow-on to #167 to introduce prototype `assertIterableEquals` methods to `Assertions`.
Would the JUnit team find this contribution useful? If so, is there any way it could be improved?
---
> Introduce assertIterableEquals() methods in Assertions

- junit-platform-gradle-plugin/src/main/groovy/org/junit/platform/gradle/plugin/JUnitPlatformExtension.groovy
- junit-platform-gradle-plugin/src/main/groovy/org/junit/platform/gradle/plugin/JUnitPlatformPlugin.groovy
- junit-platform-gradle-plugin/src/test/groovy/org/junit/platform/gradle/plugin/JUnitPlatformPluginSpec.groovy
Before this change, there was an assumption that all users use the
project directory as the buildDir. In some cases, they are re-mapped to
a single buildDir at the root of the project to make management easier.
This change uses the builDir from the project to set where the output
will be.
Also to make the plugin nicer to use, users can set the reportsDir to be
a GString (or any object really) and rely on the behavior of
Project.file(..) to resolve it to the correct path.
---
> Gradle plugin will honor the build dir, and making extension more usable

- build.gradle
This will make debugging CI build easier without having to keep track of
all the artifacts that get generated.
---
> Test will now print the error to the console when they fail

- junit-jupiter-api/src/main/java/org/junit/jupiter/api/Assertions.java
Since javadocs are produced and published to Maven Central for both the JUnit 5 and OpenTest4J projects, Eclipse and other IDES don't have a problem linking imported Javadocs between the projects.  The JUnit 5 javadocs published at http://junit.org/junit5/docs/current/api/ cannot however resolve these links, so providing the FQCN provides readers with additional information to locate the related javadocs.
---
Resolves #560.
> Updates references to AssertionFailedError to use its FQCN.

- junit-platform-commons/src/main/java/org/junit/platform/commons/meta/API.java
While working on #144 I noticed that public-scoped fields (presumably constants) can only inherit their @API Usage from the enclosing class.  This change would, at a minimum, allows constants to be marked with Usage.Deprecated or Usage.Internal while their enclosing class remains accessible.
---
> Allows @API on ElementType.FIELD

- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/DiscoveryFilterApplierTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/DynamicTestGenerationTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/NestedTestClassesTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/StandardTestClassTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/discovery/DiscoverySelectorResolverTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/discovery/DiscoveryTests.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/TestDescriptor.java
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/discovery/UniqueIdFilter.java
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/execution/TestRun.java
Rename `getAllDescendants()` to `getDescendants()`. The word all is redundant. I always expect to get all `X` when I call a method `getX()`.
---
> Rename getAllDescendants() to getDescendants().

- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/TestReporterParameterResolverTests.java
- platform-tests/src/test/java/org/junit/platform/launcher/core/LauncherFactoryTests.java
Solves #587 by renaming the 3 test methods.
---
> Remove test literal from method names.

- platform-tests/src/test/java/org/junit/platform/commons/util/PackageUtilsTests.java
Assume that two tests using `Class::getPackage::getXyz()` are not executed on Java 9 -- until the reason why those methods return `null` is understood and fixed. Create new ticket to track this issue?
---
> Prevent Java 9 on Travis CI from failing

- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertThrows.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/Assertions.java
For this case, instead of using a wildcard declared as `? extends Throwable`, we use a type T as the type argument of a given generic type.
It will help compiler to infer correct concrete return type for method instead of returning `Throwable` every time.
For example, in IDEA, press *Cmd+Option+V*
Before:
```java
Throwable t = assertThrows(AwesomeException.class, () -> { /* smth */ });
```
After:
```java
AwesomeException e = assertThrows(AwesomeException.class, () -> { /* smth */ });
```
---
> Regression: assertThrows should not use wildcard for expected exception type

- platform-tests/src/test/java/org/junit/platform/commons/util/PackageUtilsTests.java
This PR replaces `vendorFromObjectClassIsPresent()` with `attributesFromValueWrapperClassArePresent()`  which works on Java 8 and 9, as the `ValueWrapper` class is loaded from an external JAR with all its metadata initialized from the encapsulated manifest file.
The second test, that was guarded by a _do not start on Java 9_ assumption, is removed as it didn't provide real additional test value.
Might resolve #600
---
> Use class from external JAR file for testing

- build.gradle
- documentation/src/test/java/example/JUnit4ClassDemo.java
- added removeUnusedImports() rule
- removed lamda fix (no longer needed)
- changed groovy target to `src/**/*.groovy`,
because it is faster to resolve than `**/*.groovy`.
- renamed `customReplaceRegex` to its new name
`replaceRegex`.
Time for a `spotlessCheck` to execute before this commit: 8.4s config, 5s execution (total 13.4s)
Time for a `spotlessCheck` to execute after this commit: 5.5s config, 0.3s execution (total 5.8s).
So about twice as fast.
---
> Updated to Spotless 3.0.0.

- documentation/src/docs/asciidoc/release-notes-5.0.0-M4.adoc
- junit-platform-engine/src/main/java/org/junit/platform/engine/discovery/ClassNameFilter.java
- junit-platform-runner/src/main/java/org/junit/platform/runner/JUnitPlatform.java
- platform-tests/src/test/java/org/junit/platform/runner/JUnitPlatformRunnerTests.java
- Remove deprecated ```includeClassNamePattern(String)``` and ```@IncludeClassNamePattern```as described in #547.
---
> Remove includeClassNamePattern(String) with all dependencies

- junit-platform-console/src/main/java/org/junit/platform/console/options/AvailableOptions.java
- junit-platform-console/src/main/java/org/junit/platform/console/options/DetailsConverter.java
- platform-tests/src/test/java/org/junit/platform/console/options/JOptSimpleCommandLineOptionsParserTests.java
PR #524 pretended to parse option details case insensitive -- but it did not. This PR fixes that issue and provides tests ensuring all of case-wise permutations from `NONE` to `none` are allowed and valid for `--details`.
---
> Add details parsing fix and tests.

- junit-platform-gradle-plugin/junit-platform-gradle-plugin.gradle
Fixes #631 by removing `path` and `configuration` from compile-time dependency declaration.
With the change applied, Gradle can quickly pass a sequence like `gradlew clean test; gradlew test; gradlew test` from the second `test` on with:
```
[...]
:junit-platform-gradle-plugin:test UP-TO-DATE
BUILD SUCCESSFUL
Total time: 1.103 secs
11:33:56: External task execution finished 'test'.
```
---
> Revise task inputs for Gradle plugin regarding incremental builds (#631)

- junit-platform-console/junit-platform-console.gradle
Executing `gradlew clean test; gradlew test; gradlew test` resulted in
all tests being executed thrice instead of just once. By generating the
shadowed `junit-platform-console-x.y.z.jar` only if code changes are
made, Gradles' UP-TO-DATE checks succeed again.
Copied from `build.gradle` file:
```
// Generate JAR manifest only if code was compiled or recompiled;
// otherwise the junitPlatformTest task will always be executed even if
// no code changes were made. The reason is that the generation of
// the buildDate and buildTime causes JAR manifests to be modified
// which triggers unnecessary rebuilding of the dependent JARs.
```
Fixes #631
---
> Make Gradle incremental build work

- junit-platform-console/src/main/java/org/junit/platform/console/options/AvailableOptions.java
- junit-platform-console/src/main/java/org/junit/platform/console/options/CommandLineOptions.java
- junit-platform-console/src/main/java/org/junit/platform/console/tasks/DiscoveryRequestCreator.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/discovery/AbstractClassNameFilter.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/discovery/ClassNameFilter.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/discovery/ExcludeClassNameFilter.java
- junit-platform-gradle-plugin/src/main/groovy/org/junit/platform/gradle/plugin/FiltersExtension.groovy
- junit-platform-gradle-plugin/src/main/groovy/org/junit/platform/gradle/plugin/JUnitPlatformPlugin.groovy
- junit-platform-gradle-plugin/src/test/groovy/org/junit/platform/gradle/plugin/JUnitPlatformPluginSpec.groovy
- junit-platform-runner/src/main/java/org/junit/platform/runner/ExcludeClassNamePatterns.java
- junit-platform-runner/src/main/java/org/junit/platform/runner/JUnitPlatform.java
- platform-tests/src/test/java/org/junit/platform/console/ConsoleLauncherIntegrationTests.java
- platform-tests/src/test/java/org/junit/platform/console/options/JOptSimpleCommandLineOptionsParserTests.java
- platform-tests/src/test/java/org/junit/platform/console/subpackage/OneTest.java
- platform-tests/src/test/java/org/junit/platform/console/subpackage/TwoTest.java
- platform-tests/src/test/java/org/junit/platform/console/tasks/DiscoveryRequestCreatorTests.java
- platform-tests/src/test/java/org/junit/platform/engine/discovery/ClassNameFilterTests.java
- platform-tests/src/test/java/org/junit/platform/runner/JUnitPlatformRunnerTests.java
This PR addresses issue #314.  
It adds support for filtering classes for exclusion in the ConsoleLauncher, the Gradle JUnit 5 plugin, and the JUnitPlatform runner.
---
> Issue314 exclude classname patterns

- platform-tests/src/test/java/org/junit/platform/console/ConsoleLauncherIntegrationTests.java
Replace `System.out.println` instruction with actual assertion.
---
> Replace sout instruction with assertion

- documentation/src/docs/asciidoc/release-notes-5.0.0-M4.adoc
- documentation/src/docs/asciidoc/running-tests.adoc
After-math of https://github.com/junit-team/junit5/pull/630 adding information regarding `--exclude-classname` option  to the user documentation and release notes.
---
> Update documentation regarding exclude classname option

- junit-platform-console/junit-platform-console.gradle
- junit-platform-console/src/test/java/integration/JupiterIntegration.java
- junit-platform-console/src/test/java/integration/VintageIntegration.java
Fixes #648 by running some sample tests (which includes failing and passing tests)
reads the output, and ensures that we get the expected result. This integration test
relies on external test plan execution using the standalone jar.
When the something similar to the incorrect usage of a Stream's filter() method
that removed all tests from being run happens, this integration test will fail.
---
> Add integration test

- junit-platform-console/src/main/java/org/junit/platform/console/tasks/TreePrintingListener.java
- platform-tests/src/test/java/org/junit/platform/console/tasks/TestExecutionListenerSupport.java
- platform-tests/src/test/java/org/junit/platform/console/tasks/TreePrintingListenerTests.java
Fixes #658 by handling potential multi-line messages within the
TreePrintingListener. Before this commit, the vertical test tree
tiles were interrupted when a multi-line message was provided.
---
---
~~Change is documented in the [User Guide](http://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](http://junit.org/junit5/docs/snapshot/user-guide/#release-notes)~~
> Continue the tree structure across line breaks

- documentation/src/docs/asciidoc/release-notes-5.0.0-M4.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertionUtils.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/Assertions.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/AssertionsFailTests.java
This PR adds two additional signatures for the ```Assertions.fail()``` methods:
-   ```Assertions.fail(String message, Throwable cause)```
-   ```Assertions.fail(Throwable cause)```
---
---
> Adds fail() methods that pass Throwables - closes #656.

- junit-platform-commons/src/main/java/org/junit/platform/commons/util/ToStringBuilder.java
- junit-platform-console/src/main/java/org/junit/platform/console/tasks/XmlReportWriter.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/TestExecutionListenerRegistry.java
`ToStringBuilder.java` was unnecessarily creating both a `StringBuilder` and a `Stream` within `toString()`, where regular string concatenation and `String.join()` would have been equally performant and probably more readable.
`XmlReportWriter.java` was also creating a `StringBuilder` where regular string concatenation would have worked just as well. Whether it is more readable though is up for debate.
`TestExecutionListenerRegistry.java` was adding things to a collection via manual looping, where calling `Collections.addAll` would have been shorter and probably more readable.
---
---
> Apply IntelliJ-suggested code changes

- documentation/src/docs/asciidoc/extensions.adoc
- documentation/src/docs/asciidoc/index.adoc
- documentation/src/docs/asciidoc/release-notes-5.0.0-M4.adoc
- junit-platform-commons/src/main/java/org/junit/platform/commons/support/AnnotationSupport.java
- junit-platform-commons/src/main/java/org/junit/platform/commons/support/MethodSortOrder.java
- junit-platform-commons/src/main/java/org/junit/platform/commons/support/ReflectionSupport.java
- junit-platform-commons/src/main/java/org/junit/platform/commons/support/package-info.java
- junit-platform-commons/src/main/java/org/junit/platform/commons/util/AnnotationUtils.java
- junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java
- platform-tests/src/test/java/org/junit/platform/commons/support/AnnotationSupportTests.java
- platform-tests/src/test/java/org/junit/platform/commons/support/ReflectionSupportTests.java
Fixes #246 and #352 by publishing useful internal helper methods via an API facade. Members of the support package are maintained, which is reflected by the `@API(Maintained)` annotation. The current support facade only delegates to the internal utility methods.
---
---
> Publish maintained utilities to dedicated support package

- documentation/src/docs/asciidoc/release-notes-5.0.0-M4.adoc
- junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java
- platform-tests/src/test/java/org/junit/platform/commons/util/ReflectionUtilsTests.java
`ReflectionUtils#findMethods` did already filter bridge methods, but
let other synthetic methods through. For example a field like:
Predicate<String> allNames = name -> true;
may yield a synthetic method to be declared in the encapsulating class.
Now, all synthetic methods (including bridge methods) are filtered.
---
> Ignore all synthetic methods in ReflectionUtils#findMethod(s)

- junit-platform-commons/src/main/java/org/junit/platform/commons/support/AnnotationSupport.java
- junit-platform-commons/src/main/java/org/junit/platform/commons/support/ReflectionSupport.java
- junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java
- platform-tests/src/test/java/org/junit/platform/commons/support/ReflectionSupportTests.java
This commit publishes method ReflectionSupport#findMethods which in turn delegates to the internal utility performing hierarchical method searches.
---
> Add findMethods to reflection support API

- junit-platform-console/junit-platform-console.gradle
- junit-platform-console/src/test/resources/logging.properties
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/ServiceLoaderTestEngineRegistry.java
Fixes #513 by using log level CONFIG instead of DEBUG.
If you want to see the information which engines were detected, use "-Djava.util.logging.config.file=LOG" with the content of LOG something similar to:
```
handlers=java.util.logging.ConsoleHandler
java.util.logging.ConsoleHandler.level=CONFIG
org.junit.level=CONFIG
```
---
> Reduce log level for detected test engines

- documentation/src/docs/asciidoc/release-notes-5.0.0-M4.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/ExtensionContext.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/execution/ExtensionValuesStoreTests.java
Not taking into account the order of parts made namespace behavior
non-intuitive.
Closes: #646
---
---
> Change Namespace equality to consider parts order.

- build.gradle
- documentation/documentation.gradle
- junit-jupiter-api/junit-jupiter-api.gradle
- junit-jupiter-engine/junit-jupiter-engine.gradle
- junit-jupiter-migration-support/junit-jupiter-migration-support.gradle
- junit-platform-console/junit-platform-console.gradle
- junit-platform-engine/junit-platform-engine.gradle
- junit-platform-gradle-plugin/junit-platform-gradle-plugin.gradle
- junit-platform-launcher/junit-platform-launcher.gradle
- junit-platform-runner/junit-platform-runner.gradle
- junit-platform-surefire-provider/junit-platform-surefire-provider.gradle
- junit-vintage-engine/junit-vintage-engine.gradle
- platform-tests/platform-tests.gradle
Modify existing configuration names by `api` or `implementation`.
See gh-691
---
---
- [] Change is documented in the [User Guide](http://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](http://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
> Move to java-library plugin

- documentation/src/docs/asciidoc/release-notes-5.0.0-M4.adoc
- junit-platform-gradle-plugin/src/main/groovy/org/junit/platform/gradle/plugin/JUnitPlatformPlugin.groovy
- junit-platform-gradle-plugin/src/test/groovy/org/junit/platform/gradle/plugin/JUnitPlatformPluginSpec.groovy
Currently, the `JUnitPlatformPlugin` makes assumptions that the `'java'` plugin has been applied by looking at `sourceSets` and tasks that are created by it.
If the `'java'` plugin is not applied, the configuration will fail during the `afterEvaluate`
This change makes it so that the `'java'` plugin is also applied.
* I'm not sure how this should be documented in the release notes
---
---
> Apply the 'java' plugin when the `JunitPlatformPlugin` is applied

- junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/ConditionEvaluationResult.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestTemplateTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/JavaElementsResolver.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TestInfoParameterResolver.java
- junit-platform-commons/src/main/java/org/junit/platform/commons/support/AnnotationSupport.java
- junit-platform-commons/src/main/java/org/junit/platform/commons/support/ReflectionSupport.java
- junit-platform-commons/src/main/java/org/junit/platform/commons/util/AnnotationUtils.java
- junit-platform-commons/src/main/java/org/junit/platform/commons/util/CollectionUtils.java
- junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/FilterResult.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/TestDescriptor.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/TestExecutionResult.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/UniqueId.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/discovery/DiscoverySelectors.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/listeners/MutableTestExecutionSummary.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/listeners/TestExecutionSummary.java
- platform-tests/src/test/java/org/junit/platform/commons/util/CollectionUtilsTests.java
I've made a number of cleanup- and immutability-related changes to the JUnit 5 codebase in my spare time, mainly for fun, but also in the hope that it makes things a little easier to maintain in the future. However, it's not clear to me if all the changes I've made are actually desirable for backwards-compatibility or other reasons.
Are all the changes I've made here OK? If not, I wonder if someone on the JUnit 5 team would kindly let me know either where I can improve or where I've overstepped my boundaries. :)
Here's a summary of the main changes I've made, as I've written in my commit message:
```
Clean up and encourage immutability within the codebase
- `Collections::unmodifiable*` has been used more for the return values
of public, non-internal, collection-returning methods, with the …
```
> Clean up and encourage immutability within the codebase

- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/bridge/AbstractNonGenericTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/bridge/BridgeMethodTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/bridge/NumberResolver.java
- junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java
- platform-tests/src/test/java/org/junit/platform/commons/util/ReflectionUtilsTests.java
Code introduced by https://github.com/junit-team/junit5/commit/82174c15aba026a52a2566ee8643af89917fc1a1 broke standard support for test class hierarchies without bridge or synthetic methods present.
This commit fixes the regression by comparing the default and generic string representation of the upper method. If they are equal, the upper method does not shadow the lower one.
---
---
> Fix regression for class hierarchies without synthetic methods

- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/predicates/IsTestClassWithTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/discovery/predicates/IsTestClassWithTestsTests.java
`@TestTemplate` methods are now recognized as **test** ones by the Discovery phase (see `DiscoverySelectorResolver`).
---
---
> Classes containing @TestTemplate methods are detected as Test classes

- documentation/src/docs/asciidoc/release-notes-5.0.0-M4.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertLinesMatch.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/Assertions.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/AssertionsAssertLinesMatchTests.java
- platform-tests/src/test/java/org/junit/platform/console/ConsoleDetailsTests.java
- platform-tests/src/test/resources/console/details/fail/Fail-failWithMultiLineMessage-flat-ascii.out.txt
- platform-tests/src/test/resources/console/details/fail/Fail-failWithMultiLineMessage-flat-unicode.out.txt
- platform-tests/src/test/resources/console/details/fail/Fail-failWithMultiLineMessage-verbose-ascii.out.txt
- platform-tests/src/test/resources/console/details/fail/Fail-failWithMultiLineMessage-verbose-unicode.out.txt
- platform-tests/src/test/resources/console/details/fail/Fail-failWithSingleLineMessage-flat-ascii.out.txt
- platform-tests/src/test/resources/console/details/fail/Fail-failWithSingleLineMessage-flat-unicode.out.txt
- platform-tests/src/test/resources/console/details/fail/Fail-failWithSingleLineMessage-verbose-ascii.out.txt
- platform-tests/src/test/resources/console/details/fail/Fail-failWithSingleLineMessage-verbose-unicode.out.txt
This is PR promotes an assertion utility developed for internal `List<String>` comparsion to the public Jupiter API as `org.junit.jupiter.api.Assertions.assertLinesMatch(List<String> expected, List<String> actual)`
Simple example:
```
List<String> expected = Arrays.asList("^first.+line", ".[[oO)", "last line$");
List<String> actual = Arrays.asList("first line", ".[[oO)", "last line");
assertLinesMatch(expected, actual);
```
File/System.out-based [example](https://github.com/junit-team/junit5/blob/assert_lines_match/platform-tests/src/test/java/org/junit/platform/console/ConsoleDetailsTests.java#L207):
```
List<String> expectedLines = Files.readAllLines(path, UTF_8);
List<String> actualLines = asList(result.out.split("\\R"));
assertLinesMatch(expectedLines, actualLines);
```
The new …
> Assertions.assertLinesMatch(List<String>, List<String>) proposal

- documentation/src/docs/asciidoc/release-notes-5.0.0-M4.adoc
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ClassTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/DynamicTestTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/MethodTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestFactoryTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestTemplateTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/DiscoverySelectorResolver.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/descriptor/TestTemplateTestDescriptorTests.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/TestDescriptor.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/descriptor/EngineDescriptor.java
- junit-platform-engine/src/test/java/org/junit/platform/engine/test/TestDescriptorStub.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/TestIdentifier.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/Root.java
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/descriptor/VintageTestDescriptor.java
- platform-tests/src/test/java/org/junit/platform/console/tasks/TreePrinterTests.java
- platform-tests/src/test/java/org/junit/platform/engine/support/descriptor/AbstractTestDescriptorTests.java
- platform-tests/src/test/java/org/junit/platform/engine/support/descriptor/DemoClassTestDescriptor.java
- platform-tests/src/test/java/org/junit/platform/engine/support/descriptor/DemoMethodTestDescriptor.java
- platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/DemoHierarchicalContainerDescriptor.java
- platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/DemoHierarchicalTestDescriptor.java
- platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/HierarchicalTestExecutorTests.java
- platform-tests/src/test/java/org/junit/platform/launcher/listener/SummaryGenerationTests.java
- platform-tests/src/test/java/org/junit/platform/runner/JUnitPlatformRunnerTests.java
Fixes #508 by replacing logic behind `isTest()` and `isContainer()` from two independent boolean properties into an enumeration based one:
```java
enum TestDescriptor.Type {
ENGINE, CONTAINER, TEST, CONTAINER_AND_TEST;
public boolean isContainer() {
return this == ENGINE || this == CONTAINER || this == CONTAINER_AND_TEST;
}
public boolean isTest() {
return this == TEST || this == CONTAINER_AND_TEST;
}
}
```
Convenient and code duplicate remover methods `TestDescriptor.prune()` and `TestDescriptor.pruneTree()` are introduced.
---
---
> Redesign isTest() and isContainer() in TestDescriptor

- documentation/src/docs/asciidoc/release-notes-5.0.0-M4.adoc
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/NestedTestClassesTests.java
- junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java
- platform-tests/src/test/java/org/junit/platform/commons/util/ReflectionUtilsTests.java
Fixes #717 by traversing superclasses to find all declared classes in the hierarchy of the class to scan. Declared classes of implemented (super-) interfaces are also included.
---
---
> Include "inherited" nested classes in findNestedClasses()

- documentation/src/docs/asciidoc/release-notes-5.0.0-M4.adoc
- documentation/src/test/java/example/UsingTheLauncherDemo.java
- junit-platform-console/src/main/java/org/junit/platform/console/tasks/ConsoleTestExecutor.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/Launcher.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/DefaultLauncher.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/TestExecutionListenerRegistry.java
- junit-platform-runner/src/main/java/org/junit/platform/runner/JUnitPlatform.java
- junit-platform-surefire-provider/src/main/java/org/junit/platform/surefire/provider/JUnitPlatformProvider.java
- platform-tests/src/test/java/org/junit/platform/console/tasks/XmlReportsWritingListenerTests.java
- platform-tests/src/test/java/org/junit/platform/launcher/core/DefaultLauncherTests.java
Addresses #628 by adding an overloaded execute(LauncherDiscoveryRequest, TestExecutionListener) method that uses the supplied TestExecutionListeners in addition to already registered listeners but only for the supplied LauncherDiscoveryRequest.
---
---
> Add Launcher.execute(Request, Listener…) overload

- documentation/src/docs/asciidoc/release-notes-5.0.0-M4.adoc
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/TestIdentifier.java
- junit-platform-surefire-provider/src/test/java/org/junit/platform/surefire/provider/RunListenerAdapterTests.java
- platform-tests/src/test/java/org/junit/platform/launcher/TestIdentifierTests.java
This PR addresses part of #407 by using the new `TestDescriptor.Type` enum as new property of `TestIdentifier`. `TestIdentifier.isContainer()` and `TestIdentifier.isTest()` now also only delegate their work to `TestDescriptor.Type#isContainer()/isTest()`.
This PR also removes unnecessary Optional-wrapper usages within the creation of `TestIdentifier`s.
---
---
> TestIdentifier now uses TestDescriptor.Type

- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/MethodTestDescriptor.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/TestExecutionExceptionHandlerTests.java
I think extensions should behave consistently whenever the test method is exited. This requires calling exception handlers in reversed order, the same way as after callbacks are called. In particular, if two extensions a and b implement before and exception handling callbacks, one would expect
- before-a
- before-b
- handle-exception-b
- handle-exception-a
to provide an around like behavior (same as JUnit 4 rule chains).
---
---
> Invoke TestExecutionExceptionHandlers in reversed order, analogous to After*Callbacks

- junit-platform-console-standalone/junit-platform-console-standalone.gradle
- junit-platform-console-standalone/src/test/java/standalone/JupiterParamsIntegration.java
> Include junit-jupiter-params in standalone JAR

- .travis.yml
- build.gradle
- junit-platform-gradle-plugin/junit-platform-gradle-plugin.gradle
- junit-platform-gradle-plugin/src/main/groovy/org/junit/platform/gradle/plugin/JUnitPlatformPlugin.groovy
- junit-platform-gradle-plugin/src/test/groovy/org/junit/platform/gradle/plugin/JUnitPlatformPluginFunctionalSpec.groovy
- junit-platform-gradle-plugin/src/test/groovy/org/junit/platform/gradle/plugin/JUnitPlatformPluginSpec.groovy
Fixes https://github.com/junit-team/junit5/issues/708 and adds functional tests for validating Gradle plugin until the Gradle team can start implementing built-in support.
- No changelog updated yet, wasn't sure if this would get in.
- Testing Uses locally built components by providing the classpath of those components as dependencies
- Does not currently use the [`java-gradle-plugin`](https://docs.gradle.org/current/userguide/javaGradle_plugin.html) - I wasn't sure how that would fare with the current signing and other components used right now, so I didn't add that in (can be done later)
*Questions*
- Should we run the functional tests on every build?
- Should we run the functional tests with multiple Gradle versions (very easy to add)?
- Is the formatting for writing build files, java …
> Gradle plugin improvements

- documentation/documentation.gradle
- documentation/src/docs/asciidoc/index.adoc
Revise the Asciidoctor build task configuration / setup in the following ways:
- remove dedicated task to copy images as this is built into the plugin
- use AsciidoctorJ Diagram instead of low-level asciidoctor-diagram gem dependency
- don't set imagesoutdir as it defaults to destination dir + imagesdir
- set imagesdir in document instead of build configuration to avoid breaking HTML
- no need to activate Gradle plugin defined using plugins clause
- correct a few bad AsciiDoc attribute declarations
---
---
> revise Asciidoctor task configuration

- documentation/documentation.gradle
- documentation/src/docs/asciidoc/index.adoc
- set outdir instead of imagesoutdir
- allows imagesdir for PDF can be derived from default imagesdir
You want to avoid setting imagesoutdir in the plugin configuration because then you have to remember to update it if you change the imagesdir in the document. Instead, you want to set the outdir attribute based on the plugin setting. That way, you can build the imagesdir for PDF based on the outdir and the default imagesdir. This mimics what Asciidoctor Diagram does internally.
---
---
> set outdir instead of imagesoutdir

- build.gradle
Replace deprecated github-pages with git-publish
CloudBees Jenkins build task needs to be changed, @marcphilipp 
Replace "githubPages" with "gitPublish".
---
> Replace deprecated github-pages with git-publish

- documentation/src/docs/asciidoc/release-notes-5.0.0-M5.adoc
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/discovery/IsPotentialJUnit4TestClass.java
- junit-vintage-engine/src/test/java/org/junit/vintage/engine/discovery/IsPotentialJUnit4TestClassTests.java
The IsPotentialJunit4TestClass now checks if a memberclass is declared static.
If so it lets it through the filter.
Also includes unit tests for the IsPotentialJUnit4TestClass. It might be nice to use the
parameters support for these tests.
---
---
> Consider static nested classes as potential JUnit4 tests

- documentation/src/docs/asciidoc/release-notes-5.0.0-M5.adoc
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/discovery/JUnit4DiscoveryRequestResolver.java
- junit-vintage-engine/src/test/java/org/junit/vintage/engine/VintageTestEngineExecutionTests.java
- junit-vintage-engine/src/test/java/org/junit/vintage/engine/discovery/VintageDiscoveryRequestResolverTests.java
- junit-vintage-engine/src/test/java/org/junit/vintage/engine/samples/junit4/AbstractJunit4TestCaseWithConstructorParameter.java
The Junit4DiscoveryRequestResolver did not take the isPotentialJunit4TestClass
predicate in consideration. This is now added in the TestClassCollector, so
Abstract classes are properly filtered.
Multiple tests however used non-JUnit 4 compliant classes as test input.
These are now moved to make them proper JUnit 4 test classes.
Perhaps some of these test classes should be given better names, since they are now on the top level.
The logging follows the output maven generated for the same class when it was being
run from the jupiter engine.
---
---
> Do not execute abstract tests in VintageTestEngine

- documentation/src/docs/asciidoc/release-notes-5.0.0-M5.adoc
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/ExtensionRegistry.java
- junit-platform-commons/src/main/java/org/junit/platform/commons/util/ClassLoaderUtils.java
- junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java
- junit-platform-console-standalone/junit-platform-console-standalone.gradle
- junit-platform-console/src/main/java/org/junit/platform/console/tasks/ConsoleTestExecutor.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/ServiceLoaderTestEngineRegistry.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/ServiceLoaderTestExecutionListenerRegistry.java
- platform-tests/src/test/java/org/junit/platform/commons/util/ClassLoaderUtilsTests.java
- platform-tests/src/test/java/org/junit/platform/commons/util/ClasspathScannerTests.java
- platform-tests/src/test/java/org/junit/platform/commons/util/ReflectionUtilsTests.java
- platform-tests/src/test/java/org/junit/platform/console/tasks/ConsoleTestExecutorTests.java
This commit enhances the configuration-level log statement with the location URL from where the classloader loaded the engine class.
Also introduce dedicated `ClassLoaderUtils` class that encapsulates static class-related helper methods. As a first action, this commit moves `getDefaultClassLoader()` to `ClassLoaderUtils` helper.
---
> Add ClassLoaderUtils and log the location from which an engine was loaded

- junit-platform-commons/src/main/java/org/junit/platform/commons/util/StringUtils.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/discovery/DiscoverySelectors.java
This PR uses the `String#isEmpty()` method to clean up the code and make it easier to read. The patches contained in it replace usages of `someString.equals("")` and `someString.length() == 0`.
---
---
> String#isEmpty() usage

- junit-platform-commons/src/main/java/org/junit/platform/commons/support/HierarchyTraversalMode.java
- junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java
This patch removes redundant semicolons in the end of enum constants
lists.
While these semicolons aren't technically wrong, they're redundant.
---
---
> Remove semicolons at the end of enums

- platform-tests/src/test/java/org/junit/platform/console/options/ThemeTests.java
I have created tests for the enum Theme. The tests verify that the correct Theme be given for a certain character set. The tests also verify that for each Theme, the correct result string be given from Theme.status() based on a TestExecutionResult.
---
---
> Introduce tests for Theme class

- documentation/src/docs/asciidoc/release-notes-5.0.0-M5.adoc
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/JupiterTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestFactoryTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestTemplateTestDescriptor.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/ExecutionTracker.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/HierarchicalTestExecutor.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/Node.java
- platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/DemoHierarchicalContainerDescriptor.java
- platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/DemoHierarchicalEngineDescriptor.java
- platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/DemoHierarchicalTestDescriptor.java
- platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/HierarchicalTestExecutorTests.java
> Replace Node.isLeaf() with explicit tracking of executed descriptors

- documentation/src/test/java/example/DynamicTestsDemo.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/DynamicContainer.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/DynamicNode.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/DynamicTest.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/DynamicContainerTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/DynamicTestTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestFactoryTestDescriptor.java
Addresses #695 and #604 
Add dynamic container support in @TestFactory methods.
https://travis-ci.org/junit-team/junit5/builds/228235319#L596 is generated by:
```java
Stream.of("A", "B", "C")
.map(input -> dynamicContainer("Container " + input, Stream.of(
dynamicTest("not null", () -> assertNotNull(input)),
dynamicContainer("properties", Stream.of(
dynamicTest("length > 0", () -> assertTrue(input.length() > 0)),
dynamicTest("not empty", () -> assertFalse(input.isEmpty()))
))
)));
```
---
---
> Add dynamic container support in @TestFactory methods

- platform-tests/src/test/java/org/junit/platform/engine/support/descriptor/MethodSourceTests.java
I have written tests for the MethodSource class that verify MethodSource preconditions, equality, and HashCode equality. I have also introduced reflection into the tests to verify MethodSource object equality that are built with reflected methods. 
The tests also ensure that class names and method names remain consistent when MethodSource objects are built with a reflected method. Say "java.lang.String" is a reflected class, and we reflect the "valueOf" method with "int" as its argument type, "valueOf" should be returned when we call MethodSource.getMethodName() and "java.lang.String" should be returned when we call MethodSource.getClassName().
---
---
> Introduce tests for MethodSource class

- documentation/src/docs/asciidoc/release-notes-5.0.0-M5.adoc
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/JupiterEngineDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/JupiterEngineExtensionContext.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/execution/ExtensionContextTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/ExtensionContextExecutionTests.java
> Introduce engine-level ExtensionContext

- .travis.yml
- junit-jupiter-migration-support/src/main/java/org/junit/jupiter/migrationsupport/rules/member/TestRuleAnnotatedField.java
- junit-jupiter-params/src/test/java/org/junit/jupiter/params/ParameterizedTestNameFormatterTests.java
- junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/ServiceLoaderTestEngineRegistry.java
Current state of getting jdk-9 back to build JUnit 5 - not only on Travis CI.
With https://github.com/junit-team/junit5/commit/4e401dd72f2157cb6dc8a9db615e491007dba4cf the `'-Werror'` compiler option is untouched, i.e. remains activated.
Fixes #775 
Travis CI (debian trusty) is still on JDK9-B162, due to [webupd8team](https://launchpad.net/~webupd8team/+archive/ubuntu/java?field.series_filter=trusty) is on 162.
Using a manually installed JDK9-B168 with https://github.com/junit-team/junit5/pull/842/commits/d0443a35b8700cee1a2b28493981e99efb3b1591 for now.
---
---
- [na] Method [preconditions](http://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the …
> Get jdk-9 back to build JUnit 5

- junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTestNameFormatter.java
- junit-jupiter-params/src/test/java/org/junit/jupiter/params/ParameterizedTestNameFormatterTests.java
Without this change an invalid test name pattern results in an error message that does not immediately point to the problem.
Before:
```
java.lang.IllegalArgumentException: Unmatched braces in the pattern.
at java.text.MessageFormat.applyPattern(MessageFormat.java:508)
at java.text.MessageFormat.<init>(MessageFormat.java:362)
at java.text.MessageFormat.format(MessageFormat.java:840)
at org.junit.jupiter.params.ParameterizedTestNameFormatter.format(ParameterizedTestNameFormatter.java:39)
at org.junit.jupiter.params.ParameterizedTestInvocationContext.getDisplayName(ParameterizedTestInvocationContext.java:35)
at org.junit.jupiter.engine.descriptor.TestTemplateInvocationTestDescriptor.<init>(TestTemplateInvocationTestDescriptor.java:39)
at …
```
> Provide informative error message if parameterized test name pattern is invalid

- documentation/src/docs/asciidoc/release-notes-5.0.0-M5.adoc
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestFactoryTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestTemplateTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/DiscoverySelectorResolver.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/TestDescriptor.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/TestPlan.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/DefaultLauncher.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/Root.java
- junit-platform-surefire-provider/src/main/java/org/junit/platform/surefire/provider/TestPlanScannerFilter.java
- junit-platform-surefire-provider/src/test/java/org/junit/platform/surefire/provider/TestPlanScannerFilterTests.java
- platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/DemoHierarchicalContainerDescriptor.java
- platform-tests/src/test/java/org/junit/platform/launcher/TestPlanTests.java
This pull request is an attempt to solve #732, #508, and #879 in three independent but related commits.
---
> Clean up TestDescriptor API to enable reasoning about a TestPlan before executing it

- README.md
- documentation/src/docs/asciidoc/index.adoc
- documentation/src/docs/asciidoc/overview.adoc
Add getting help section to README.md file and the User Guide with links to SO and Gitter.
Closes #707
---
> Add getting help section with links to SO and Gitter

- documentation/src/docs/asciidoc/release-notes-5.0.0-M6.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/Assertions.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/AssertionsFailTests.java
Prior to this commit the return type `void` prevented the use of a `fail`-method as an expression. For example, the user has to wrap the `fail` call in a lambda like:
```java
Stream.of().map(entry -> { fail("should not be called"); return ""; })
```
Now, the line can be written more clearly as:
```java
Stream.of().map(entry -> fail("should not be called"))
```
Addresses #845
---
---
> Allow Assertions.fail methods to be used as expressions

- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/discovery/DiscoveryTests.java
The code that checks the precondition was not tested.
---
---
> Add test for precondition of discover method

- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/JupiterTestEngine.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/discovery/DiscoveryTests.java
Engines are called by a launcher. The DefaultLauncher never calls an engine with a null request. We trust all callers of the `discover` method to use the engine properly. Hence there is no need to check for null. (This change was proposed by @marcphilipp in #918.)
---
---
> Don't check that the discovery request is not null

- junit-platform-engine/src/main/java/org/junit/platform/engine/TestEngine.java
Add info the parameters must not be null.
---
---
> Add info the parameters must not be null.

- junit-vintage-engine/src/main/java/org/junit/vintage/engine/discovery/ClassSelectorResolver.java
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/discovery/ClasspathRootSelectorResolver.java
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/discovery/DiscoverySelectorResolver.java
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/discovery/JUnit4DiscoveryRequestResolver.java
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/discovery/MethodSelectorResolver.java
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/discovery/PackageNameSelectorResolver.java
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/discovery/UniqueIdSelectorResolver.java
- junit-vintage-engine/src/test/java/org/junit/vintage/engine/discovery/UniqueIdSelectorResolverTests.java
Each DiscoverySelectorResolver is now responsible for discovering test classes based on the provided EngineDiscoveryRequest. This minimizes the interface of DiscoverySelectorResolvers and makes it easier to use them.
---
---
> Provide request to DiscoverySelectorResolver.

- documentation/src/docs/asciidoc/release-notes-5.0.0-M6.adoc
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/DiscoveryFilterApplier.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/EngineDiscoveryRequest.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/filter/ClasspathScanningSupport.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/DefaultDiscoveryRequest.java
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/discovery/JUnit4DiscoveryRequestResolver.java
- platform-tests/src/test/java/org/junit/platform/console/tasks/DiscoveryRequestCreatorTests.java
- platform-tests/src/test/java/org/junit/platform/launcher/core/LauncherDiscoveryRequestBuilderTests.java
- platform-tests/src/test/java/org/junit/platform/runner/JUnitPlatformRunnerTests.java
Provide a consistent API. The method for retrieving selectors already has the name `getSelectorsByType` instead of `getDiscoverySelectorsByType`. I think it is helpful to omit the word discovery in the method name because it reduces its length but the reader still can deduce from the context (it's an `EngineDiscoveryRequest`) that the methods return `DiscoveryFilter`s and `DiscoverySelector`s.
---
---
> Rename method to getFilterByType.

- .travis.yml
- documentation/src/docs/asciidoc/release-notes-5.0.0-M6.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/ExtensionContext.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/AbstractExtensionContext.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/execution/ExtensionContextTests.java
- junit-jupiter-params/src/test/java/org/junit/jupiter/params/ParameterizedTestExtensionTests.java
This commit adds a convenient accessor that retrieves the root context of the current one. It eases the work of extension authors that want to store a value in the top-most, the root context.
---
---
> Add ExtensionContext.getRoot() accessor

- .travis.yml
Build with maximum heap limit at Travis CI to prevent 'build error 137': out of memory
---
> Build with maximum heap limit at Travis CI

- junit-platform-engine/src/main/java/org/junit/platform/engine/support/filter/ClasspathScanningSupport.java
Although `ClasspathScanningSupport` is an `@API(Experimental)` utilities class, it can be subclassed, which doesn't seem to make sense to allow. This PR ensures that it cannot be subclassed.
---
---
> Prevent subclassing of a utilities class

- junit-platform-console/src/main/java/org/junit/platform/console/tasks/Color.java
Although the `static` instances in the `Color` class are effectively constants, they aren't declared as idiomatic constants, so they're technically mutable. This PR ensures that they are proper constants.
---
---
> Apply `final` modifiers to Color static instances

- junit-platform-console/src/main/java/org/junit/platform/console/tasks/XmlReportWriter.java
This PR simplifies a usage of `Map.entrySet().forEach()` in `XmlReportWriter` to the equivalent `Map.forEach()`, which removes a number of unneeded characters.
---
---
> Simplify `Map.entrySet().forEach()` usage to `Map.forEach()`

- build.gradle
With #860 the mavenCentral configuration in buildscript of all projects was required.
[As promised](https://github.com/junit-team/junit5/pull/860/files#r121257206), this PR contains a new version of Spotless (3.4.1) which allows to remove the previous change. 
---
---
> Spotless 3.4.1 only requires mavenCentral in buildscript of root project

- documentation/src/docs/asciidoc/release-notes-5.0.0-M6.adoc
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/JavaElementsResolver.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/UniqueId.java
Make UniqueId segment list immutable and turn `getSegments()` into a simple getter, i.e. it does no longer create a copy of the internal list on each invocation. The single place where a modifiable list was expected was in `JavaElementsResolver`. There a copy is created explicitly.
This commit also removes the defensive copy creation of the segment list from the package-private constructor. All two internal callers do not modify the underlying list, they actually drop their list reference.
---
> Make UniqueId segment list immutable

- documentation/src/docs/asciidoc/release-notes-5.0.0-M6.adoc
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ClassTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/DynamicContainerTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/DynamicTestTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/JupiterTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/MethodBasedTestDescriptor.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/descriptor/AbstractTestDescriptor.java
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/descriptor/RunnerTestDescriptor.java
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/descriptor/VintageTestDescriptor.java
- platform-tests/src/test/java/org/junit/platform/engine/support/descriptor/DemoClassTestDescriptor.java
- platform-tests/src/test/java/org/junit/platform/engine/support/descriptor/DemoMethodTestDescriptor.java
- platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/DemoHierarchicalContainerDescriptor.java
- platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/DemoHierarchicalTestDescriptor.java
Source has been set by the method `setSource` that was always called in the constructor. By adding a constructor with an additional `source` parameter we can make the field `source` final and remove the setter. This means we don't have to care about proper changes of the field anymore.
---
---
> Provide TestSource in constructors

- .travis.yml
Travis CI upgraded their jdk-9 version to 175. This version supports all features JUnit 5 needs for its build process. Newer jkd-9 versions like the recent build 178 only contain fixes for bugs that don't prevent JUnit 5 to build.
---
> Use jdk-9 provided by Travis CI

- junit-vintage-engine/src/main/java/org/junit/vintage/engine/descriptor/VintageTestDescriptor.java
The deleted constructor was only used internally by one of the other constructors.
---
---
> Delete unnecessary constructor

- junit-vintage-engine/src/main/java/org/junit/vintage/engine/descriptor/RunnerTestDescriptor.java
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/descriptor/VintageTestDescriptor.java
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/discovery/TestClassRequestResolver.java
- junit-vintage-engine/src/test/java/org/junit/vintage/engine/execution/RunListenerAdapterTests.java
Make the creation of `VintageTestDescriptor` independent from the `EngineDescriptor`. This enables us to simplify the `TestClassRequestResolver` by letting it only create `TestClassRequest`s.
---
---
> Provide UniqueId instead of parent descriptor

- .travis.yml
Specify which branches/tags that we do not want to be built, like: r5.0.0-M5
```
branches:
except:
- /^r\d.*$/
```
See https://docs.travis-ci.com/user/customizing-the-build/#Safelisting-or-blocklisting-branches
---
> Exclude release tag from Travis CI build

- documentation/src/docs/asciidoc/release-notes-5.0.0-M6.adoc
- junit-jupiter-params/src/test/java/org/junit/jupiter/params/provider/MethodArgumentsProviderTests.java
- junit-platform-commons/src/main/java/org/junit/platform/commons/util/CollectionUtils.java
- platform-tests/src/test/java/org/junit/platform/commons/util/CollectionUtilsTests.java
Prior to this commit simple 1-dimensional arrays with primitive component types were not supported. The user could circumvent the issue by using an IntStream like:
```
static IntStream data() {
return IntStream.of(3, 24, 12);
}
```
Now all primitive array types (from `boolean[]` to `short[]`) are supported as a return type of static argument providing methods for parameterized tests. For example:
```
static int[] data() {
return new int[] { 3, 24, 12 };
}
```
Fixes #953
---
---
> Support primitive array types as argument providers

- build.gradle
In the interest of keeping up-to-date with the most modern, safest APIs, I have migrated the use of `Date` and `SimpleDateFormatter` in `build.gradle` to `java.time.OffsetDateTime` and `java.time.DateTimeFormatter` for calculating build dates and times.
I've manually confirmed that the artifact produced by `gradlew clean shadowJar` for subproject _junit-platform-console-standalone_ has the same format for both the `Build-Date` and `Build-Time` in its MANIFEST.MF.
---
---
> Use the modern java.time API to get build times

- documentation/src/docs/asciidoc/release-notes-5.0.0-RC1.adoc
- documentation/src/docs/asciidoc/release-notes.adoc
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/Launcher.java
Prior to this commit the `execute(LauncherDiscoveryRequest)` method was temporarily available to restore binary compatibility with external tools using it.
Now the method is removed. External tools are now forced to recompile against the new SNAPSHOT version of the JUnit Platform.
Closes #740
---
---
> Remove deprecated execute method from Launcher

- platform-tests/src/test/java/org/junit/AutomaticModuleNameTests.java
Read the gradle modules from where they are actually defined.
The test `org.junit.AutomaticModuleNameTests#automaticModuleName` was failing on my local junit copy because I still had the directory `junit-jupiter-migration-support` that was later renamed to `junit-jupiter-migrationsupport`. The `Automatic-Module-Name` field was missing in the old build artifacts. It took me some time to figure out what the problem was and deleting the old directory fixed the failing test.
Reading the module information form settings.gradle will prevent this problem for good.
---
---
> Read the project modules from settings.gradle

- junit-vintage-engine/src/main/java/org/junit/vintage/engine/discovery/UniqueIdFilter.java
As described in the commit message:
```txt
- Use of `Optional.map` was reported by IntelliJ IDEA inspections.
- `ArrayDeque` javadoc states that it is likely to be "faster than
`LinkedList` when used as a queue".
```
---
---
> Use `Optional.map` and `ArrayDeque` more consistently

- build.gradle
Arguably, the variables affected by this PR weren't as informatively- and intuitively-named as they could have been. This PR attempts to fix that.
---
---
> Rename Spotless variables in build.gradle for clarity

- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertThrows.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/Assertions.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/AssertionsAssertThrowsTests.java
This PR adds overloads for `assertThrows` that accept either a `String` or a `Supplier<String>` as requested by issue #977 .
---
> Overloaded assertThrows() that accept a message or message supplier

- junit-platform-commons/src/main/java/org/junit/platform/commons/util/ClasspathScanner.java
`handleInternalError` should only be called when the class cannot be loaded because of a malformed class name. This means that the error is thrown by the `loadClass.apply` call. Therefore the `Class` object is never available when `handleInternalError` is called.
---
---
> Delete dead code

- documentation/src/docs/asciidoc/release-notes-5.0.0-RC1.adoc
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/execution/ExtensionValuesStore.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/execution/ExtensionValuesStoreTests.java
getOrComputeIfAbsent() was accessing the parent store's map without
acquiring the parent's lock.
---
---
> Fix thread-safety issue in ExtensionValuesStore

- documentation/src/docs/asciidoc/release-notes-5.0.0-RC3.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/ExtensionContext.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/execution/ExtensionContextTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/execution/ExtensionStoreConcurrencyTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/ExtensionContextExecutionTests.java
This PR removes the method `getStore()` from the `ExtensionContext` interface and renames `Namespace.DEFAULT` to `Namespace.GLOBAL`.
---
---
> Cleanup ExtensionContext Namespace API

- junit-vintage-engine/src/main/java/org/junit/vintage/engine/discovery/MethodSelectorResolver.java
- junit-vintage-engine/src/test/java/org/junit/vintage/engine/JUnit4ParameterizedTestCase.java
- junit-vintage-engine/src/test/java/org/junit/vintage/engine/JUnit4ParameterizedTests.java
When selecting a test method from a JUnit 4 parameterized test it, the method would run only once, without considering the parameters it should receive.
Resolves #549 
---
---
> Fix selection of method from JUnit 4 parameterized test

- junit-vintage-engine/src/main/java/org/junit/vintage/engine/discovery/ClassSelectorResolver.java
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/discovery/ClasspathRootSelectorResolver.java
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/discovery/DiscoverySelectorResolver.java
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/discovery/MethodSelectorResolver.java
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/discovery/PackageNameSelectorResolver.java
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/discovery/TestClassCollector.java
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/discovery/UniqueIdSelectorResolver.java
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/discovery/VintageDiscoverer.java
- junit-vintage-engine/src/test/java/org/junit/vintage/engine/discovery/UniqueIdSelectorResolverTests.java
This avoids that some class filters are applied twice. Now there is a dedicated place for applying the class filters.
---
---
> Resolvers apply class filter themselves

- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertAll.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertArrayEquals.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertEquals.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertFalse.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertIterableEquals.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertLinesMatch.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertNotEquals.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertNotNull.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertNotSame.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertNull.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertSame.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertThrows.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertTimeout.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertTrue.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/Assumptions.java
- junit-jupiter-migrationsupport/src/main/java/org/junit/jupiter/migrationsupport/rules/member/TestRuleAnnotatedMemberFactory.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/support/AnnotationConsumerInitializer.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/LauncherFactory.java
As requested by @sbrannen in https://github.com/junit-team/junit5/pull/961/files#r134089533, this PR takes a subset of the changes proposed for https://github.com/junit-team/junit5/pull/961/files and makes them a separate PR.
This is just a cleanup PR designed to add missing private constructors to various utilities classes.
---
---
> Add missing private constructors to utilities classes

- .gitignore
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertionUtils.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/AssertionsAssertArrayEqualsTests.java
As described in the commit message,
```
Beforehand it would print arrays via the arrays' toString() methods.
Now it prints them using `Arrays.toString()`, which produces the
expected result.
This is a prerequisite for #961.
```
This PR was requested by @sbrannen at https://github.com/junit-team/junit5/pull/961#discussion_r134114088.
---
---
> Fix bug in AssertionUtils.toString(Object)

- junit-vintage-engine/src/main/java/org/junit/vintage/engine/discovery/TestClassCollector.java
The requests are already distinct, because
1. TestClassRequest does not override equals.
2. CompleteRequests never have filters but filteredRequests always have. Therefore completeRequests and filteredRequests are disjunct.
3. CompleteRequests are created from a set of classes. Hence they are all different.
4. FilteredRequests are created from map entries. Hence they are all different.
---
---
> Don't call distinct on stream of requests

- platform-tests/platform-tests.gradle
- platform-tests/src/test/java/org/junit/PrintUsageOfApiAnnotation.java
Add program that prints usages of @API annotation.
See current result at https://gist.github.com/sormuras/2f3df0f4d35af83b625eff66d8a9f130
Addresses #856 
---
> Add program that prints usages of @API annotation

- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/DynamicTestTests.java
- junit-platform-console/src/main/java/org/junit/platform/console/tasks/DiscoveryRequestCreator.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/LauncherDiscoveryRequestBuilder.java
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/discovery/TestClassCollector.java
- junit-vintage-engine/src/test/java/org/junit/vintage/engine/RecordCollectingLogger.java
Motivated by the discussion here https://github.com/junit-team/junit5/pull/1039#discussion_r136281377 this PR replaces `LinkedList` usages with `ArrayList` where appropriate.
---
---
> Use ArrayList instead of LinkedList

- build.gradle
As the bug was fixed in Kotlin 1.1.4 acording to youtrack this
workarround can be removed.
https://youtrack.jetbrains.com/issue/KT-18832
---
---
> Remove the workaround for Kotlin on JDK9

- documentation/src/docs/asciidoc/release-notes-5.0.0.adoc
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ClassTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/MethodBasedTestDescriptor.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/descriptor/ClassSource.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/descriptor/ClasspathResourceSource.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/descriptor/CompositeTestSource.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/descriptor/DirectorySource.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/descriptor/FilePosition.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/descriptor/FileSource.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/descriptor/MethodSource.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/descriptor/PackageSource.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/listeners/LoggingListener.java
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/descriptor/RunnerTestDescriptor.java
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/descriptor/VintageTestDescriptor.java
- platform-tests/src/test/java/org/junit/platform/engine/support/descriptor/AbstractTestSourceTests.java
- platform-tests/src/test/java/org/junit/platform/engine/support/descriptor/ClasspathResourceSourceTests.java
- platform-tests/src/test/java/org/junit/platform/engine/support/descriptor/CompositeTestSourceTests.java
- platform-tests/src/test/java/org/junit/platform/engine/support/descriptor/DemoClassTestDescriptor.java
- platform-tests/src/test/java/org/junit/platform/engine/support/descriptor/DemoMethodTestDescriptor.java
- platform-tests/src/test/java/org/junit/platform/engine/support/descriptor/FilePositionTests.java
- platform-tests/src/test/java/org/junit/platform/engine/support/descriptor/FileSystemSourceTests.java
- platform-tests/src/test/java/org/junit/platform/engine/support/descriptor/GenericSourceTests.java
- platform-tests/src/test/java/org/junit/platform/engine/support/descriptor/MethodSourceTests.java
- platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/DemoHierarchicalTestEngine.java
- platform-tests/src/test/java/org/junit/platform/launcher/TestIdentifierTests.java
- platform-tests/src/test/java/org/junit/platform/launcher/listener/SummaryGenerationTests.java
- platform-tests/src/test/java/org/junit/platform/runner/JUnitPlatformRunnerTests.java
This pull request includes changes discussed in #939.
---
---
> Replace constructors with static factory methods

- documentation/src/docs/asciidoc/release-notes-5.1.0-M1.adoc
- junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/TestEngine.java
- platform-tests/src/test/java/org/junit/platform/commons/util/ReflectionUtilsTests.java
Use module descriptor for artifact and version information retrieval, if the Java Platform Module System in available on the current runtime.
Closes #600
---
---
> Use module descriptor for artifact and version information retrieval

- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/DiscoveryFilterApplier.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/JupiterTestEngine.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/DiscoveryFilterApplier.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/DiscoverySelectorResolver.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/DiscoveryFilterApplierTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/discovery/DiscoveryFilterApplierTests.java
This PR includes two refactorings:
- Reuse ClasspathScanningSupport to simplify DiscoveryFilterApplier
- Use same ClassFilter for classpath scanning and post-discovery filtering
---
---
> Simplify Jupiter filtering

- junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTestExtension.java
- junit-jupiter-params/src/test/java/org/junit/jupiter/params/ParameterizedTestIntegrationTests.java
Redundant arguments are filtered out in `ParameterizedTestExtension`, so only consumed arguments are passed to invocation context and used in name formatter. Filtering is applied only when number of arguments is greater than number of test method parameters. It should work with other extensions like parameter resolvers - when there are eg. 3 columns provided and only 2 test method parameters consumes them and the 3rd one is resolved by another extension, then exception about incorrect configuration will be thrown.
Please notice that some unchanged code in `ParameterizedTestIntegrationTests.java` is reformatted. I used formatter from `junit5/src/eclipse` and assume it was formatted incorrectly before. If it was correct, please let me know and I'll revert those changes.
> Display name for @ParameterizedTest should only include consumed arguments

- .appveyor.yml
- .travis.yml
- Jenkinsfile
- build.gradle
- documentation/documentation.gradle
- gradle.properties
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/RepeatedTest.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/discovery/ClassNameFilter.java
- src/javadoc/stylesheet.css
Remove JDK build matrix on Travis CI and use `--release 8` javac option.
The JUnit 5 build requires JDK-9 or higher.
The JUnit 5 runtime environment needs to be Java 8 or higher.
Travis CI now sets "-Xmx" by default.
---
---
> Build with JDK-9 only

- junit-platform-commons-java-9/src/main/java/org/junit/platform/commons/util/ModuleUtils.java
- junit-platform-commons-java-9/src/test/java/org/junit/platform/commons/util/ModuleUtilsTests.java
- junit-platform-commons/src/main/java/org/junit/platform/commons/util/ModuleUtils.java
- junit-platform-console/src/main/java/org/junit/platform/console/tasks/DiscoveryRequestCreator.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/discovery/DiscoverySelectors.java
> Translate `--scan-module-path` into multiple module selectors

- build.gradle
Fixes a bug regarding Kotlin files. See the plugin's changelog: https://github.com/diffplug/spotless/blob/master/plugin-gradle/CHANGES.md
---
---
> Update Spotless plugin from 3.5.2 to 3.6.0

- documentation/src/docs/asciidoc/running-tests.adoc
- junit-platform-gradle-plugin/junit-platform-gradle-plugin.gradle
- junit-platform-gradle-plugin/src/main/groovy/org/junit/platform/gradle/plugin/JUnitPlatformExtension.groovy
- junit-platform-gradle-plugin/src/main/groovy/org/junit/platform/gradle/plugin/JUnitPlatformPlugin.groovy
- junit-platform-gradle-plugin/src/main/groovy/org/junit/platform/gradle/plugin/SelectorsExtension.groovy
- junit-platform-gradle-plugin/src/test/groovy/org/junit/platform/gradle/plugin/JUnitPlatformPluginSpec.groovy
Add --select-module support to Gradle JUnitPlatformPlugin.
Test it using jitpack: https://jitpack.io/com/github/junit-team/junit5/issues~1119-gradle-plugin-modules-support-SNAPSHOT/build.log
Closes #1119
---
---
> Add --select-module support to Gradle JUnitPlatformPlugin

- documentation/src/docs/asciidoc/release-notes-5.1.0-M1.adoc
- junit-platform-surefire-provider/src/main/java/org/junit/platform/surefire/provider/JUnitPlatformProvider.java
- junit-platform-surefire-provider/src/main/java/org/junit/platform/surefire/provider/RunListenerAdapter.java
- junit-platform-surefire-provider/src/test/java/org/junit/platform/surefire/provider/JUnitPlatformProviderTests.java
- junit-platform-surefire-provider/src/test/java/org/junit/platform/surefire/provider/RunListenerAdapterTests.java
Fixes #1113.
- Move testSetStarting/testSetCompleted into RunListenerAdapter
- Start a test set for every child of an engine descriptor that
is a container and has a ClassSource
- Ensure every reported test belongs to a test set (for engines
that do not use ClassSource)
---
---
> Surefire: Run all TestsToRun in one execution using a single TestPlan

- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/TestInstanceLifecycleTests.java
- junit-jupiter-engine/src/test/kotlin/org/junit/jupiter/engine/kotlin/ArbitraryNamingKotlinTestCase.kt
Just want to make sure that tests with names having strange characters will continue to work moving forward.
---
---
> Add a kotlin test with a name with strange characters

- junit-platform-gradle-plugin/gradle/functional-test.gradle
- junit-platform-gradle-plugin/junit-platform-gradle-plugin.gradle
- junit-platform-gradle-plugin/src/functTest/groovy/org/junit/platform/gradle/plugin/AbstractFunctionalSpec.groovy
- junit-platform-gradle-plugin/src/functTest/groovy/org/junit/platform/gradle/plugin/JUnitPlatformPluginDependenciesFunctionalSpec.groovy
- junit-platform-gradle-plugin/src/functTest/groovy/org/junit/platform/gradle/plugin/JUnitPlatformPluginFunctionalSpec.groovy
- junit-platform-gradle-plugin/src/test/groovy/org/junit/platform/gradle/plugin/JUnitPlatformPluginSpec.groovy
`ProjectBuilder` should be avoided for writing functional tests. The runtime behavior has its quirks and sometimes requires [calling an internal Gradle API](https://github.com/junit-team/junit5/blob/master/junit-platform-gradle-plugin/src/test/groovy/org/junit/platform/gradle/plugin/JUnitPlatformPluginSpec.groovy#L401) (which might break if you change Gradle versions). The appropriate API to use here is TestKit.
Refactors the setup logic for TestKit and separates build logic needed for functional testing. Translates two existing tests from the use of `ProjectBuilder` to TestKit. No more internal API is required.
---
---
> Avoid use of Gradle's internal APIs for testing

- .travis.yml
As [suggested by Travis](https://docs.travis-ci.com/user/languages/java/#Caching), cache downloaded, external dependencies and Gradle Wrapper. Subsequent builds will reuse existing files which should significantly speed up CI execution.
---
---
> Cache downloaded external dependencies and Gradle Wrapper

- documentation/src/docs/asciidoc/release-notes/release-notes-5.1.0-M2.adoc
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/listeners/MutableTestExecutionSummary.java
- platform-tests/src/test/resources/console/details/fail/Fail-failWithMultiLineMessage-none-ascii.out.txt
- platform-tests/src/test/resources/console/details/fail/Fail-failWithMultiLineMessage-none-unicode.out.txt
- platform-tests/src/test/resources/console/details/fail/Fail-failWithMultiLineMessage-summary-ascii.out.txt
- platform-tests/src/test/resources/console/details/fail/Fail-failWithMultiLineMessage-summary-unicode.out.txt
- platform-tests/src/test/resources/console/details/fail/Fail-failWithMultiLineMessage-tree-ascii.out.txt
- platform-tests/src/test/resources/console/details/fail/Fail-failWithMultiLineMessage-tree-unicode.out.txt
- platform-tests/src/test/resources/console/details/fail/Fail-failWithSingleLineMessage-none-ascii.out.txt
- platform-tests/src/test/resources/console/details/fail/Fail-failWithSingleLineMessage-none-unicode.out.txt
- platform-tests/src/test/resources/console/details/fail/Fail-failWithSingleLineMessage-summary-ascii.out.txt
- platform-tests/src/test/resources/console/details/fail/Fail-failWithSingleLineMessage-summary-unicode.out.txt
- platform-tests/src/test/resources/console/details/fail/Fail-failWithSingleLineMessage-tree-ascii.out.txt
- platform-tests/src/test/resources/console/details/fail/Fail-failWithSingleLineMessage-tree-unicode.out.txt
Prior to this commit only the "toString()" representation of the failure throwable was printed.
Now some of the initial stack trace lines are printed by the console launcher to better describe the location of the failure.
Closes #1203
---
---
> Print initial lines of failure stack traces

- documentation/src/docs/asciidoc/release-notes/release-notes-5.1.0-M2.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/ExtensionContext.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/AbstractExtensionContext.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ClassExtensionContext.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ClassTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/JupiterEngineDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/JupiterEngineExtensionContext.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/MethodExtensionContext.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestMethodTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestTemplateExtensionContext.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestTemplateTestDescriptor.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/execution/ExtensionContextTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/execution/JUnit5EngineExecutionContextTests.java
- junit-jupiter-params/src/test/java/org/junit/jupiter/params/ParameterizedTestExtensionTests.java
- platform-tests/src/test/java/org/junit/platform/launcher/core/LauncherConfigurationParametersTests.java
Provide access to configuration parameters via adding method `Optional<String> getConfigurationParameter(String key)` to interface `ExtensionContext`.
Closes #1196
---
---
> Introduce method getConfigurationParameter() in ExtensionContext

- documentation/src/docs/asciidoc/release-notes/release-notes-5.1.0-M2.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/ExtensionContext.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/AbstractExtensionContext.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/DynamicContainerTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/DynamicNodeTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/DynamicTestTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/JupiterEngineDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/JupiterTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/execution/ExtensionValuesStore.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/execution/JupiterEngineExecutionContext.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/EngineExecutionContext.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/HierarchicalTestExecutor.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/Node.java
- platform-tests/src/test/java/org/junit/jupiter/extensions/Heavyweight.java
- platform-tests/src/test/java/org/junit/jupiter/extensions/HeavyweightAlphaTests.java
- platform-tests/src/test/java/org/junit/jupiter/extensions/HeavyweightBetaTests.java
- platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/HierarchicalTestExecutorTests.java
An extension context store is bound to its extension context lifecycle. When an extension context lifecycle ends it closes its associated store. All stored values that are instances of `ExtensionContext.Store.CloseableResource` are notified by invoking their `close()` method.
Addresses https://github.com/junit-team/junit5/issues/456#issuecomment-341120548 -- enhance the "engine level context store" with a **cleanup** hook.
Closes #742
---
---
> Introduce lifecycle support for objects stored in ExtensionContext.Store

- documentation/src/docs/asciidoc/release-notes/release-notes-5.1.0-M2.adoc
- documentation/src/docs/asciidoc/writing-tests.adoc
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/converter/DefaultArgumentConverter.java
- junit-jupiter-params/src/test/java/org/junit/jupiter/params/converter/DefaultArgumentConverterTests.java
Add argument conversions for [Currency](https://docs.oracle.com/javase/8/docs/api/java/util/Currency.html), [Locale](https://docs.oracle.com/javase/8/docs/api/java/util/Locale.html), and [URI](https://docs.oracle.com/javase/8/docs/api/java/net/URI.html)
Related issue: #1218
---
---
> Add argument conversions for Currency, Locale, and URI

- documentation/src/docs/asciidoc/release-notes/release-notes-5.1.0-M2.adoc
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/DynamicContainerTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/DynamicNodeTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/DynamicTestTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestFactoryTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestTemplateInvocationTestDescriptor.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/DynamicNodeGenerationTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/TestTemplateInvocationTests.java
- junit-jupiter-params/src/test/java/org/junit/jupiter/params/ParameterizedTestIntegrationTests.java
- junit-platform-console/src/main/java/org/junit/platform/console/tasks/XmlReportWriter.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/TestIdentifier.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/listeners/LegacyReportingUtils.java
- junit-platform-surefire-provider/src/main/java/org/junit/platform/surefire/provider/RunListenerAdapter.java
- junit-platform-surefire-provider/src/test/java/org/junit/platform/surefire/provider/RunListenerAdapterTests.java
- platform-tests/src/test/java/org/junit/platform/launcher/listeners/LegacyReportingUtilsTest.java
Fixes #1182. This pull request provides fixes related to XML reports emitted by `ConsoleLauncher`, Gradle plugin, and Maven Surefire.
1. Output class name also for dynamic tests and test template invocations
1. Suffix names with invocation indexes for dynamic tests and test template invocations
1. Output method parameter types also for Maven Surefire but as `testMethod{Type}` instead of `testMethod(Type)` due to a limitation of Surefire
Here's a reference test:
```java
class JUnit5Tests {
@Test
void myNormalTest() {}
@RepeatedTest(3)
void myRepeatedTest() {}
@ParameterizedTest
@ValueSource(strings = {
"hello",
"world"
})
void myParametrizedTest(String s) {}
@TestFactory
Stream<DynamicNode> myTestFactory() {
return Stream.of(dynamicContainer("foo", Stream.of(dynamicTest("bar", () -> …
```
> Fixes for XML reporting

- documentation/src/docs/asciidoc/release-notes/release-notes-5.1.0-M2.adoc
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/DynamicContainerTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/DynamicDescendantFilter.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/Filterable.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestFactoryTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestTemplateTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/JavaElementsResolver.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/TestMethodResolver.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/AbstractJupiterTestEngineTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/DynamicNodeGenerationTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/TestTemplateInvocationTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/TrackLogRecords.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/discovery/DiscoverySelectorResolverTests.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/UniqueId.java
- platform-tests/src/test/java/org/junit/platform/engine/UniqueIdTests.java
> Allow executing dynamic tests/test template invocations by unique ID

- .travis.yml
- README.md
Integrates codecov with Travis build.
Example result from my fork: https://codecov.io/gh/hisener/junit5
Also, adds the codecov badge to `README.md`. It looks like this:
[![codecov](https://codecov.io/gh/hisener/junit5/branch/master/graph/badge.svg)](https://codecov.io/gh/hisener/junit5)
Related issue: #240 
---
---
> Integrate codecov with Travis build

- documentation/src/docs/asciidoc/release-notes/release-notes-5.1.0-M2.adoc
- documentation/src/docs/asciidoc/user-guide/writing-tests.adoc
- documentation/src/test/java/example/ParameterizedTestDemo.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/MethodArgumentsProvider.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/MethodSource.java
- junit-jupiter-params/src/test/java/org/junit/jupiter/params/ParameterizedTestIntegrationTests.java
- junit-jupiter-params/src/test/java/org/junit/jupiter/params/provider/MethodArgumentsProviderTests.java
> Make @MethodSource `value` attribute optional

- build.gradle
Update Gradle script so that subproject `junit-platform-commons-java-9` is really built with source, target and API of Java 9.
Before, two things were happening:
- `--release` compiler option was missing and all modules were compiler against JDK9 API
- `javacRelease = 9` did not work for the subproject, because compiler settings were configured too early.
This was spotted while trying to import the project to IntelliJ IDEA https://youtrack.jetbrains.com/issue/IDEA-186344 
---
---
> Fix junit-platform-commons-java-9 subproject build

- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/ScriptExecutionCondition.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/ScriptExecutionEvaluator.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/script/ScriptExecutionManager.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/ScriptExecutionConditionTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/ScriptExecutionEvaluatorTests.java
Copied from http://mail.openjdk.java.net/pipermail/jigsaw-dev/2018-February/013581.html
> [...] The more general issue is of course that you are 
deploying a module that does not know what modules it depends. In these 
cases you have to help the module system by specifying --add-modules to 
force the modules that it depends on to be resolved. You got lucky with 
the Oracle JDK build because jdk.deploy pulled in the java.scripting module.
Addresses #1282
---
---
> Make dependency on "javax.script" optional

- documentation/src/docs/asciidoc/release-notes/release-notes-5.1.0.adoc
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/CsvArgumentsProvider.java
- junit-jupiter-params/src/test/java/org/junit/jupiter/params/provider/CsvArgumentsProviderTests.java
> Fix handling of trailing null elements in @CsvSource

- gradle.properties
Main feature: Cglib was replaced with Byte-Buddy.
See http://joel-costigliola.github.io/assertj/assertj-core-news.html#assertj-core-3.9.1 for details.
> Upgrade AssertJ to 3.9.1

- junit-platform-console/src/main/java/org/junit/platform/console/options/AvailableOptions.java
- junit-platform-console/src/main/java/org/junit/platform/console/options/JOptSimpleCommandLineOptionsParser.java
- platform-tests/src/test/java/org/junit/platform/console/options/JOptSimpleCommandLineOptionsParserTests.java
Prior to this commit a bug [1] in Java 8's stream toMap() collector did report the value instead of the duplicated key in the exception message.
Now, a custom list-to-map helper always emits a helpful error message.
[1] https://bugs.openjdk.java.net/browse/JDK-8040892
Closes #1308
---
---
> Emit helpful message when a configuration key is not unique

- build.gradle
- junit-platform-commons-java-9/junit-platform-commons-java-9.gradle
Currently when java is not on the path or the java/jar executable is on path, but the version is not 9+, junit5 cannot be build.
It would be nice if project can be build using command something like 
```
JAVA_HOME=/usr/lib/jvm/java-9-jdk ./gradlew  clean build
```
The proposed change uses gradle's internal api which is probably not ok, but couldn't find better solution.
> Build should respect JAVA_HOME when running executables

- .appveyor.yml
- .travis.yml
- Jenkinsfile
- README.md
- documentation/documentation.gradle
- platform-tests/platform-tests.gradle
_Drop 9, play on 10._
This PR promotes JDK 10 to our underlying build JDK. The `--release` target is still and remains Java 8.
---
> Switch to JDK 10

- documentation/src/docs/asciidoc/user-guide/running-tests.adoc
The commit here updates the user guide and adds a section for documenting the recent support available in Ant build tool for launching JUnit 5 tests. This relates to issue https://github.com/junit-team/junit5/issues/1352
> Briefly explain support in Ant build tool for JUnit 5 tests

- documentation/src/docs/asciidoc/release-notes/release-notes-5.2.0-M1.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertionUtils.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/Assertions.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/AssertionTestUtils.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/FailAssertionsTests.java
Issue: #1333
Implemented as discussed to achieve a reasonable behaviour with both, the current and the upcoming versions of `opentest4j`.
---
---
> Introduce variant of Assertions.fail() without arguments

- build.gradle
- documentation/documentation.gradle
- documentation/src/docs/asciidoc/release-notes/release-notes-5.2.0-M1.adoc
- documentation/src/docs/asciidoc/user-guide/overview.adoc
- gradle.properties
- gradle/maven.gradle
- junit-bom/README.md
- junit-bom/junit-bom.gradle
- junit-jupiter-api/junit-jupiter-api.gradle
- junit-jupiter-engine/junit-jupiter-engine.gradle
- junit-jupiter-migrationsupport/junit-jupiter-migrationsupport.gradle
- junit-jupiter-params/junit-jupiter-params.gradle
- junit-platform-commons/junit-platform-commons.gradle
- junit-platform-console-standalone/junit-platform-console-standalone.gradle
- junit-platform-console/junit-platform-console.gradle
- junit-platform-engine/junit-platform-engine.gradle
- junit-platform-gradle-plugin/junit-platform-gradle-plugin.gradle
- junit-platform-launcher/junit-platform-launcher.gradle
- junit-platform-runner/junit-platform-runner.gradle
- junit-platform-suite-api/junit-platform-suite-api.gradle
- junit-platform-surefire-provider/junit-platform-surefire-provider.gradle
- junit-vintage-engine/junit-vintage-engine.gradle
- platform-tests/src/test/java/org/junit/AutomaticModuleNameTests.java
- settings.gradle
This pull request introduces the `junit-bom` subproject. In order to reuse build logic it was moved to `gradle/maven.gradle`. In addition, `gradle install` and `gradle uploadArchives` now use the same POM configuration.
Resolves #316.
> Introduce JUnit BOM

- documentation/src/docs/asciidoc/link-attributes.adoc
- documentation/src/docs/asciidoc/user-guide/writing-tests.adoc
I added a link to `RepetitionInfoParameterResolver.java` from User Guide ("3.11. Dependency Injection for Constructors and Methods") because other two resolvers (i.e. `TestInfoParameterResolver` and `TestReporterParameterResolver`) have links to their source code.
---
> Add link to RepetitionInfoParameterResolver in User Guide

- documentation/src/docs/asciidoc/release-notes/release-notes-5.3.0-M1.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertThrows.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/Assertions.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/AssertThrowsAssertionsTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/AssertionTestUtils.java
If the given ThrowingSupplier fails to throw the expected exception and
instead returns a value, the string representation of the value is
included in the failure message to aide debugging.
Fixes #1394
> Add assertThrows overloads that take a ThrowingSupplier

- documentation/src/docs/asciidoc/release-notes/release-notes-5.3.0-M1.adoc
- documentation/src/docs/asciidoc/user-guide/running-tests.adoc
- junit-platform-console/src/main/java/org/junit/platform/console/ConsoleLauncher.java
- junit-platform-console/src/main/java/org/junit/platform/console/ConsoleLauncherExecutionResult.java
- junit-platform-console/src/main/java/org/junit/platform/console/options/AvailableOptions.java
- junit-platform-console/src/main/java/org/junit/platform/console/options/CommandLineOptions.java
- platform-tests/src/test/java/org/junit/platform/console/ConsoleLauncherExecutionResultTests.java
- platform-tests/src/test/java/org/junit/platform/console/tasks/ConsoleTestExecutorTests.java
This PR implements the `--fail-if-no-tests` command line option for the `ConsoleLauncher` as discussed in #1298.
---
---
> Add --fail-if-no-tests command line option to ConsoleLauncher

- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/DefaultLauncher.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/EngineDiscoveryResultValidator.java
- platform-tests/src/test/java/org/junit/platform/engine/support/descriptor/AbstractTestDescriptorTests.java
- platform-tests/src/test/java/org/junit/platform/launcher/core/EngineDiscoveryResultValidatorTests.java
Prior this commit only a null-check was performed by the `DefaultLauncher` against the root test descriptor returned by an engine. Other properties where not checked, especially if the graph of that root descriptor contained cycles it could lead to stack overflow errors when traversing
the graph for execution.
This commit addresses this issue by explicitly checking the returned graph of the root test descriptor for cycles. If a cycle is detected a `PreconditionViolationException` is thrown.
Fixes: #1447
> Ensure discovered descriptor graphs are acyclic

- documentation/src/docs/asciidoc/release-notes/release-notes-5.3.0-M1.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/DynamicContainer.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/DynamicNode.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/DynamicTest.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestFactoryTestDescriptor.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/DynamicTestTests.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/descriptor/DefaultUriSource.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/descriptor/FilePosition.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/descriptor/UriSource.java
- platform-tests/src/test/java/org/junit/platform/console/ConsoleDetailsTests.java
- platform-tests/src/test/java/org/junit/platform/engine/support/descriptor/AbstractTestSourceTests.java
- platform-tests/src/test/java/org/junit/platform/engine/support/descriptor/ClasspathResourceSourceTests.java
- platform-tests/src/test/java/org/junit/platform/engine/support/descriptor/CompositeTestSourceTests.java
- platform-tests/src/test/java/org/junit/platform/engine/support/descriptor/DefaultUriSourceTests.java
- platform-tests/src/test/java/org/junit/platform/engine/support/descriptor/FilePositionTests.java
- platform-tests/src/test/java/org/junit/platform/engine/support/descriptor/FileSystemSourceTests.java
- platform-tests/src/test/java/org/junit/platform/engine/support/descriptor/GenericSourceTests.java
> Add TestSource support to dynamic containers and tests

- documentation/src/docs/asciidoc/user-guide/overview.adoc
A link to JUnit 5 User Guide(Japanese) is attached.
The repository is [here](https://github.com/udzuki/junit5-user-guide-ja).
---
---
> Add Japanese translation link to Translation sec

- junit-platform-commons-java-9/junit-platform-commons-java-9.gradle
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/descriptor/RunnerTestDescriptor.java
- junit-vintage-engine/src/test/java/org/junit/vintage/engine/VintageLauncherIntegrationTests.java
- junit-vintage-engine/src/test/java/org/junit/vintage/engine/VintageTestEngineDiscoveryTests.java
- junit-vintage-engine/src/test/java/org/junit/vintage/engine/VintageTestEngineExecutionTests.java
Resolves Issue: #970
The changes involve the default display name of JUnit Vintage test classes. It was different from the Jupiter tests because it was the FQCN. This pull request makes the display names the same, and it fixes the tests that failed upon change.
---
> Use simple class name as display name in JUnit Vintage

- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ClassExtensionContext.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ClassTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/MethodExtensionContext.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestMethodTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/execution/ExtensionValuesStore.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/execution/JupiterEngineExecutionContext.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/execution/ThrowableCollector.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/ExceptionHandlingTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/descriptor/TestFactoryTestDescriptorTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/execution/ExtensionContextTests.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/HierarchicalTestEngine.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/HierarchicalTestExecutor.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/NodeTestTask.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/OpenTest4JAwareThrowableCollector.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/SingleTestExecutor.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/ThrowableCollector.java
- platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/HierarchicalTestExecutorTests.java
- platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/NodeTestTaskWalkerIntegrationTests.java
- platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/SingleTestExecutorTests.java
> Ensure failures in lifecycle methods take precedence over earlier TestAbortedExceptions

- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/MethodBasedTestDescriptor.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/descriptor/JupiterTestDescriptorTests.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/descriptor/MethodSource.java
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/descriptor/VintageTestDescriptor.java
- junit-vintage-engine/src/test/java/org/junit/vintage/engine/VintageTestEngineDiscoveryTests.java
- junit-vintage-engine/src/test/java/org/junit/vintage/engine/descriptor/VintageTestDescriptorTests.java
- platform-tests/src/test/java/org/junit/platform/engine/support/descriptor/MethodSourceTests.java
`MethodBasedTestDescriptor` and `VintageTestDescriptor` did not preserve original class of the discovered method and instead obtained it from the `java.lang.reflect.Method`. This happened to be problematic for inherited test methods. They appeared to come from the abstract class instead of the concrete class. Surefire provider failed to match such methods when executing tests matching a mask (via `-Dtest=*MaskTest`).
This PR fixes the problem by making the underlying `MethodSource` preserve the original concrete class.
Fixes: #1406
---
---
> Use correct class for method-based test descriptors

- documentation/documentation.gradle
- documentation/src/test/java/org/junit/api/tools/ApiReportGenerator.java
Not ready to merge (final 4.0.0 release not yet available).
Followed migration guide at: https://github.com/classgraph/classgraph/wiki/Porting-FastClasspathScanner-code-to-ClassGraph
Just to provide some feedback for classgraph/classgraph#215.
---
---
> Migrate to ClassGraph (formerly FastClasspathScanner) 4.0

- documentation/src/docs/asciidoc/release-notes/release-notes-5.3.0-RC1.adoc
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ClassTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/DynamicNodeTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/JupiterTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/MethodBasedTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/NestedClassTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/DiscoverySelectorResolver.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/NestedTestsResolver.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/TestContainerResolver.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/TestInstanceLifecycleExecutionModeTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/descriptor/JupiterTestDescriptorTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/descriptor/TestDescriptorBuilder.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/execution/ExtensionContextTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/execution/JupiterEngineExecutionContextTests.java
- junit-platform-surefire-provider/src/test/java/org/junit/platform/surefire/provider/RunListenerAdapterTests.java
- junit-platform-surefire-provider/src/test/java/org/junit/platform/surefire/provider/TestMethodFilterTests.java
Tests in classes that use `Lifecycle.PER_CLASS` now use `ExecutionMode.SAME_THREAD` by default when parallel execution is enabled. In the case of nested classes, as soon as one enclosing class uses `Lifecycle.PER_CLASS` all contained nested classes and tests use `ExecutionMode.SAME_THREAD`.
Fixes #1511.
> Lifecycle.PER_CLASS ⇒ ExecutionMode.SAME_THREAD

- platform-tooling-support-tests/platform-tooling-support-tests.gradle
- platform-tooling-support-tests/src/main/java/platform/tooling/support/Request.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/JdepsTests.java
Add `jdeps`-based checks to `platform-tooling-support-tests` ensuring we don't introduce unwanted or cyclic module and package references.
Might replace usage of Degraph.
Addresses part of #1437
---
> Add `jdeps`-based cycle checks

- junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/ExtendWith.java
Adds `TestInstanceFactory` to `@ExtendWith` javadoc.
I've put (EXPERIMENTAL) after TestInstanceFactory in the doc. Not sure if that's needed or desired.
---
---
> Add TestInstanceFactory to ExtendWith doc

- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/DefaultLauncher.java
- platform-tests/src/test/java/org/junit/platform/launcher/core/DefaultLauncherTests.java
The `junit-` prefix is owned by the JUnit Team. It's akin to using **"org.junit"** as a base package. No other entity in the world should do that. Only two engines should use the prefix at the moment:
- `junit-jupiter`
- `junit-vintage`
This commit enforces these rules.
Closes #1557
---
---
> Emit warning when TestEngine ID starts with "junit-"

- documentation/src/docs/asciidoc/release-notes/release-notes-5.3.0.adoc
- documentation/src/docs/asciidoc/user-guide/writing-tests.adoc
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/converter/DefaultArgumentConverter.java
- junit-jupiter-params/src/test/java/org/junit/jupiter/params/converter/DefaultArgumentConverterTests.java
Arguments like "java.lang.Integer" should be converted to `Class` by calling `Class.forName(String)`. Automatic string-to-object conversion with `FallbackStringToObjectConverter` doesn't handle that case because `Class` has a second applicable static factory method (`getPrimitiveClass(String)`).
It is thus necessary to explicitly implement the call to `forName`.
Closes #1562
---
---
> Add implicit argument converter for String to Class

- documentation/documentation.gradle
- documentation/src/test/java/org/junit/api/tools/ApiReportGenerator.java
Update ClassGraph and follow suggestions from the release notes: https://github.com/classgraph/classgraph/releases
This seems to be a one off command, so resource leaks are unlikely to be a problem, but otherwise @lukehutch might send you a reminder like this one: https://github.com/BrynCooke/cdi-unit/issues/141
Related: https://github.com/junit-team/junit5/pull/1512
---
---
> Update ClassGraph and use try-with-resources

- documentation/src/docs/asciidoc/release-notes/release-notes-5.4.0-M1.adoc
- documentation/src/test/java/example/DynamicTestsDemo.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestFactoryTestDescriptor.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/DynamicNodeGenerationTests.java
Support single dynamic node as return type of a `@TestFactory`-annotated method.
Closes #1521 
---
---
> Support single dynamic node as return type

- junit-jupiter-api/src/main/java/org/junit/jupiter/api/condition/OS.java
fixes #1603 
This pr also detects `SunOS` as Solaris (e.g. used for `@DisabledOnOs`).
---
---
> Fix Solaris OS detection for @[Enabled|Disabled]OnOs

- documentation/src/docs/asciidoc/release-notes/release-notes-5.4.0-M1.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertionUtils.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/Assertions.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/AssertEqualsAssertionsTests.java
> Allow 0 as a delta in assertEquals methods

- documentation/src/docs/asciidoc/docinfos/index-docinfo.html
When visiting the documentation page modern browsers will issue a mixed content warning, because the documentation is served from https://junit.org/ but it references the junit5-logo.png from via http://junit.org.
---
---
_does not apply_
> Fix mixed content warning issued from documentation page

- documentation/src/docs/asciidoc/release-notes/release-notes-5.4.0-M1.adoc
- documentation/src/docs/asciidoc/user-guide/writing-tests.adoc
- documentation/src/test/java/example/ParameterizedTestDemo.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/converter/DefaultArgumentConverter.java
- junit-jupiter-params/src/test/java/org/junit/jupiter/params/converter/DefaultArgumentConverterTests.java
Use PrimitiveType#decode to convert strings to the primitive
integral types. This allows the values to be specified in the following
format:
```
DecodableString:
Signopt DecimalNumeral
Signopt 0x HexDigits
Signopt 0X HexDigits
Signopt # HexDigits
Signopt 0 OctalDigits
Sign:
-
+
```
Addresses #1624
---
---
> Support converting integral types in hex and octal

- documentation/src/docs/asciidoc/link-attributes.adoc
- documentation/src/docs/asciidoc/release-notes/release-notes-5.4.0-M1.adoc
- documentation/src/docs/asciidoc/user-guide/extensions.adoc
- junit-platform-commons/src/main/java/org/junit/platform/commons/support/ModifierSupport.java
- platform-tests/src/test/java/org/junit/platform/commons/support/ModifierSupportTests.java
For the [Testcontainers extension](https://github.com/testcontainers/testcontainers-java/pull/887) I needed to use some APIs from `ReflectionUtils` to find out whether annotated fields are declared `static` or not.
Since `ReflectionUtils` is considered a private API it would be nice to have an official API for this. I decided to create a dedicated class to work with modifiers of classes and fields: `ModifierSupport`.
---
---
> Expose selected modifier related methods from ReflectionUtils

- documentation/src/docs/asciidoc/release-notes/release-notes-5.4.0-M1.adoc
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/ForkJoinPoolHierarchicalTestExecutorService.java
- platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/ParallelExecutionIntegrationTests.java
Prior to this commit the `ForkJoinPoolHierarchicalTestExecutorService` used the default `ForkJoinWorkerThreadFactory` which in turn sets the context class loader to `ClassLoader.getSystemClassLoader()`. In runtime environments that create and use a tailored context
class loader this leads to `ClassNotFoundException` when only the `ClassLoader.getSystemClassLoader()` is available.
Now the `ForkJoinPoolHierarchicalTestExecutorService` creates `ForkJoinWorkerThread` instances that set the context class loader to the one available at creation time of the service.
Fixes #1646
---
---
> Set context class loader parallel execution mode

- CODE_OF_CONDUCT.md
As discussed within the team, we'd like to adopt the Contributor Covenant code of conduct.
> Adopt Contributor Covenant code of conduct

- README.md
- build.gradle.kts
- documentation/src/docs/asciidoc/release-notes/release-notes-5.4.0-M1.adoc
- documentation/src/docs/asciidoc/user-guide/appendix.adoc
- junit-jupiter-api/junit-jupiter-api.gradle.kts
- junit-jupiter/junit-jupiter.gradle.kts
- platform-tooling-support-tests/projects/gradle-starter/build.gradle
- platform-tooling-support-tests/projects/jar-describe-module/junit-jupiter.expected.txt
- platform-tooling-support-tests/projects/maven-starter/pom.xml
- platform-tooling-support-tests/src/test/java/platform/tooling/support/HelperTests.java
- settings.gradle.kts
Introduce `junit-jupiter` aggregator module with the following Maven coordinates:
```
<groupId>org.junit.jupiter</groupId>
<artifactId>junit-jupiter</artifactId>
<version>5.4.0-SNAPSHOT</version>
```
The generated `jar` is almost empty, it only contains a `MANIFEST.MF` file and a `pom.xml` with the following dependencies:
```xml
<dependencies>
<dependency>
<groupId>org.junit.jupiter</groupId>
<artifactId>junit-jupiter-api</artifactId>
<version>5.4.0-SNAPSHOT</version>
<scope>compile</scope>
</dependency>
<dependency>
<groupId>org.junit.jupiter</groupId>
<artifactId>junit-jupiter-params</artifactId>
<version>5.4.0-SNAPSHOT</version>
<scope>compile</scope>
</dependency>
<dependency>
<groupId>org.apiguardian</groupId>
<artifactId>apiguardian-api</artifactId>
<version>1.0.0</version> …
```
> Introduce 'junit-jupiter' aggregator module

- README.md
Using an HTTP connection to an artifact server can leave you vulnerable to MITM attack. Linked below is a POC created back in the days when Maven Central didn't support HTTPS that dynamically re-writes jar files as they are downloaded by maven.
https://max.computer/blog/how-to-take-over-the-computer-of-any-java-or-clojure-or-scala-developer/
The README isn't currently really advising people to use this url directly, but still, best to be safe.
---
---
> README Junit5 repo link as HTTPS

- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertDoesNotThrow.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/AssertDoesNotThrowAssertionsTests.java
If an unexpected error is thrown, the throwable message is added to the resulting `AssertionFailedError`.
Issue: #1703
---
---
> Improve message of Assertions.assertDoesNotThrow

- junit-vintage-engine/src/main/java/org/junit/vintage/engine/descriptor/VintageTestDescriptor.java
- junit-vintage-engine/src/test/java/org/junit/vintage/engine/descriptor/VintageTestDescriptorTests.java
Prior to this PR VintageTestDescriptor was always using displayName
for legacy reporting purposes. As a result of #1475 displayName for
vintage tests was updated to be the simple class name which in turn
affected test reports that are based on legacy reporting name.
This PR updates VintageTestDescriptor to use fully-qualified class name
for legacy reporting if that is available.
For example:
Running following vintage tests
org.example.third.TestClassOneTest, org.example.second.TestClassOneTest, org.example.first.TestClassOneTest
started to produce the following output:
```
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ example ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] …
```
> Use fully-qualified class name as legacy reporting name for Vintage tests

- documentation/src/docs/asciidoc/release-notes/release-notes-5.4.0-RC1.adoc
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/Launcher.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/TestPlan.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/DefaultLauncher.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/Root.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/UnmodifiableTestPlan.java
- junit-platform-runner/src/main/java/org/junit/platform/runner/JUnitPlatform.java
- junit-platform-runner/src/main/java/org/junit/platform/runner/JUnitPlatformTestTree.java
- platform-tests/src/test/java/org/junit/platform/launcher/core/DefaultLauncherTests.java
This commit adds a new overload for `Launcher.execute()` that accepts a
`TestPlan` directly thus avoiding running test discovery twice when
`discover()` is called prior to `execute()`. The `JUnitPlatform` runner
is changed to make use of this new feature.
Resolves #1695.
> Introduce Launcher.execute(TestPlan)

- documentation/src/docs/asciidoc/release-notes/release-notes-5.4.0-RC1.adoc
- junit-platform-commons/src/main/java/org/junit/platform/commons/util/StringUtils.java
- junit-platform-console/src/main/java/org/junit/platform/console/tasks/TreeNode.java
- platform-tests/src/test/java/org/junit/platform/commons/util/StringUtilsTests.java
- platform-tests/src/test/java/org/junit/platform/console/tasks/TreeNodeTests.java
Prior to this commit new line and other ISO control characters disrupted the layout of the tree-based test plan rendering emitted by the console launcher. Now, all ISO control characters found in display names are replaced by a single dot: '.'
Closes #1713
---
---
> Replace ISO control characters in display names

- documentation/src/docs/asciidoc/user-guide/running-tests.adoc
It took me some hours to understand why my integration tests run with JUnit4 provider although I configured maven surefire plugin as described in the guide. It turned out that I had to update maven-failsafe plugin version too. My pull request to the documentation reflects my learnings.
---
---
> Mention maven-failsafe-plugin version to be considered in User Guide

- junit-platform-commons/src/main/java/org/junit/platform/commons/support/ModifierSupport.java
- junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java
- platform-tests/src/test/java/org/junit/platform/commons/support/ModifierSupportTests.java
- platform-tests/src/test/java/org/junit/platform/commons/util/ReflectionUtilsTests.java
Added `isFinal`/`isNotFinal` methods to both `ReflectionUtils` and `ModifierSupport` to check for `final` modifier on classes or methods/fields. Methods for classes are added for symmetry with others. Tests included.
---
---
> Introduce support for final modifiers in ModifierSupport and ReflectionUtils

- documentation/src/docs/asciidoc/release-notes/release-notes-5.5.0-M1.adoc
- documentation/src/docs/asciidoc/user-guide/writing-tests.adoc
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/ValueArgumentsProvider.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/ValueSource.java
- junit-jupiter-params/src/test/java/org/junit/jupiter/params/provider/ValueArgumentsProviderTests.java
Issue: #1780
adding additional support for boolean to `@ValueSource` based on feature request #1780 
---
---
> Add support for boolean to @ValueSource

- documentation/src/docs/asciidoc/release-notes/release-notes-5.5.0-M1.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertFalse.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertTrue.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/AssertFalseAssertionsTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/AssertTrueAssertionsTests.java
Solution for #1781 
Supply actual and expected values to `org.opentest4j.AssertionFailedError` constructor in  `assertTrue()` and `assertFalse()` methods in `org.junit.jupiter.api.Assertions`. 
This will make assertions APIs consistent & these values are used by tools like Eclipse.
---
---
> Supply expected and actual values for failed boolean assertions for enhanced IDE support. Issue: #1781

- azure-pipelines.yml
- src/azure/azure-gradle-step.yml
A more complete port of the Travis configuration.  I talked with @brunoborges about porting more of the CI invocation over to Azure Pipelines; this picks up from his #1796 with a few differences:
1. For the Java 11 (Linux), macOS and Windows-based builds, this runs directly on the Azure Pipelines build agents, since they have Java 11 installed.
2. For the Java 12 and Java 13 based builds, this runs within the OpenJDK docker images.  The Azure Pipelines build agents do not have a Java 12 or 13 runtime installed, so the preferred mechanism is to [run within a docker image](https://devblogs.microsoft.com/devops/cross-platform-container-builds-with-azure-pipelines/).
3. Just run gradle on the command line instead of trying to run the gradle task.  This allows us to use the same script …
> azure-pipelines: more complete port of travis conf

- azure-pipelines.yml
Enable shallow clone during Azure Pipelines CI.
(Unfortunately, this is configurable for each individual build run, so it needs to be repeated.)
---
---
>  Shallow clone during Azure Pipelines CI

- junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java
Follow up for #1763. Added `@API` annotations with correct `since` values for modifier-related methods in `ModifierSupport` and `ReflectionUtils`.
---
---
> Add @API to modifier-related methods

- documentation/src/docs/asciidoc/user-guide/running-tests.adoc
The user guide instructions used `testCompile` and `testRuntime` Gradle configurations, which are deprecated for quite a long time now (see file:///Users/jb/projects/gradle/subprojects/docs/build/docs/userguide/java_plugin.html#tab:configurations). This PR replaces them by `testImplementation` and `testRuntimeOnly`
---
---
> Avoid using deprecated gradle configurations in user guide

- azure-pipelines.yml
Only run the publish steps when the build was successful, per https://github.com/junit-team/junit5/issues/1810#issuecomment-473516522.
Note that since the publish dependencies _only_ depend on the `linux_11` build, it's possible to publish even if the macOS (for instance) build fails.  I'm happy to tweak this if requested.
---
---
> ci: only publish on success

- junit-vintage-engine/src/main/java/org/junit/vintage/engine/execution/EventType.java
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/execution/RunListenerAdapter.java
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/execution/TestRun.java
- junit-vintage-engine/src/test/java/org/junit/vintage/engine/VintageTestEngineExecutionTests.java
- junit-vintage-engine/src/test/java/org/junit/vintage/engine/samples/junit4/IgnoredParameterizedTestCase.java
Since JUnit 4 does report events for intermediate containers, the
Vintage engine has to synthesize them. Until now this was done lazily
for start events, i.e. when the first child was started, but eagerly for
finish events, i.e. when the last static child of a container was
finished. However, the latter approach is problematic for containers
that contain both static and dynamic children, for example a Spock
specification with a regular and an unrolled feature method. Instead,
intermediate containers are now reported as finished as soon as a test
is started for which the container is not an ancestor.
Fixes #1819.
> Report intermediate containers finished lazily

- junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTestNameFormatter.java
- junit-jupiter-params/src/test/java/org/junit/jupiter/params/ParameterizedTestNameFormatterTests.java
- junit-jupiter-params/src/test/kotlin/org/junit/jupiter/params/aggregator/DisplayNameTests.kt
Prior to this commit `Arrays.copyOf()` was used without specifying the resulting array type in order to create a human-readable names for parameterized tests. Now, type `Object[]` is passed as an argument to ensure the resulting array may contain any valid instance, here an instance of `String`.
Fixes #1836
---
---
> Fix regression when creating human-readable test names

- data/events.json
Added a new event, a workshop at [DevSum19](http://devsum.se/). This workshop is commercial, i.e. attendees pay for it on top of the conference ticket (in case this matters).
> Add workshop at DevSum19

- documentation/src/docs/asciidoc/release-notes/release-notes-5.5.0-M2.adoc
- documentation/src/docs/asciidoc/user-guide/writing-tests.adoc
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/CsvArgumentsProvider.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/CsvFileArgumentsProvider.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/CsvFileSource.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/CsvSource.java
- junit-jupiter-params/src/test/java/org/junit/jupiter/params/provider/CsvArgumentsProviderTests.java
- junit-jupiter-params/src/test/java/org/junit/jupiter/params/provider/CsvFileArgumentsProviderTests.java
When using `@CsvSource` or `@CsvFileSource` in a parameterized test,
if the CSV parser does not read any character from the input, and the
input is within quotes, and emptyValue is configured, an emptyValue is
returned instead of default `""`.
---
---
Closes #1788
---
> Make emptyValue configurable in @CsvSource and @CsvFileSource

- documentation/src/docs/asciidoc/release-notes/release-notes-5.5.0-M2.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertLinesMatch.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/Assertions.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/AssertLinesMatchAssertionsTests.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/JarDescribeModuleTests.java
Prior to this commit, `Assertions.assertLinesMatch` was the only assertion that didn't support user-supplied error messages. This commit adds overloads that take a String or Supplier<String> as a custom message. That message is prepended to the automatically generated detail message.
This commit also improves the textual layout of the automatically generated detail message by emitting each expected and actual line into a dedicated new line.
Closes #1855
---
---
> Add assertLinesMatch overloads taking a custom message

- documentation/src/docs/asciidoc/user-guide/running-tests.adoc
Apache Ant 1.10.6 has been released this week and it contains enhanced support in `junitlauncher` task to support launching the tests in a forked JVM[1]. The commit in this PR, updates the documentation to make a note of this new support.
[1] https://jaitechwriteups.blogspot.com/2019/05/apache-ant-1106-released-fork-mode-for.html
> Update the documentation to note the enhancement in Ant's junitlauncher task 

- documentation/src/docs/asciidoc/release-notes/release-notes-5.5.0-M2.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/DisplayNameGenerator.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/DisplayNameGenerationTests.java
Implements the improvement suggested in #1875.
---
---
> Remove parentheses when generating display name with ReplaceUnderscores

- buildSrc/src/main/kotlin/java-library-conventions.gradle.kts
- documentation/src/docs/asciidoc/release-notes/release-notes-5.5.0-RC1.adoc
- documentation/src/docs/asciidoc/user-guide/writing-tests.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/condition/DisabledIf.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/condition/EnabledIf.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/ExtensionRegistry.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/ScriptExecutionCondition.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/ScriptExecutionEvaluator.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/script/Script.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/script/ScriptAccessor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/script/ScriptExecutionManager.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/ScriptExecutionConditionTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/ScriptExecutionEvaluatorTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/script/ScriptExecutionManagerTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/script/ScriptTests.java
- platform-tests/src/test/java/org/junit/jupiter/extensions/DisabledIfTests.java
- platform-tests/src/test/java/org/junit/jupiter/extensions/EnabledIfTests.java
> Deprecate "Script-based Conditions" for removal

- junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/ExtensionContext.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/execution/ExtensionContextStoreConcurrencyTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/execution/ExtensionContextStoreTests.java
> Introduce getOrDefault() in ExtensionContext.Store

- documentation/src/docs/asciidoc/user-guide/writing-tests.adoc
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/converter/DefaultArgumentConverter.java
- junit-jupiter-params/src/test/java/org/junit/jupiter/params/converter/DefaultArgumentConverterTests.java
Add support for Duration, Period, MonthDay, ZoneId and ZoneOffset
Closes #1929
Five new types added to the implicit converter. As far as I know, these only need to be added in one place. Tests have been added. Docs updated.
---
---
> Add more java.time types to implicit conversion

- documentation/src/docs/asciidoc/release-notes/index.adoc
- documentation/src/docs/asciidoc/release-notes/release-notes-5.5.1.adoc
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ClassBasedTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ClassTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/NestedClassTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/ClassSelectorResolver.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/MethodSelectorResolver.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/NestedClassSelector.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/NestedMethodSelector.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/NestedTestClassesTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/descriptor/JupiterTestDescriptorTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/discovery/DiscoveryTests.java
The discovery algorithm introduced in 5.5 remembers already the
resolution of each discovery selector. Prior to this commit, nested
classes were resolved by adding a ClassSelector for the nested class.
If that ClassSelector has been resolved before, discovery is assumed to
be finished. Similarly, when resolving MethodSelectors for methods
within a nested test class that have been resolved before, discovery
will stop.
This commit introduces dedicated selectors for nested classes and their
methods which take into account the actual enclosing classes that will
be present at runtime. These selectors are package-private for now but
could be made publicly available in a future release.
Fixes #1954.
> Fix discovery of inherited nested classes

- documentation/src/docs/asciidoc/release-notes/release-notes-5.6.0-M1.adoc
- documentation/src/docs/asciidoc/user-guide/writing-tests.adoc
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/CsvFileSource.java
- junit-jupiter-params/src/test/java/org/junit/jupiter/params/provider/CsvFileArgumentsProviderTests.java
Solves #1782 by adding documentation about the support of comments in @CsvFileSource.
Also added a unit test covering this use case.
---
---
> Document comment support in @CsvFileSource

- documentation/src/docs/asciidoc/release-notes/release-notes-5.6.0-M1.adoc
- documentation/src/docs/asciidoc/user-guide/writing-tests.adoc
- documentation/src/test/java/example/ParameterizedTestDemo.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/EnumArgumentsProvider.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/EnumSource.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/NullEnum.java
- junit-jupiter-params/src/test/java/org/junit/jupiter/params/provider/EnumArgumentsProviderTests.java
- platform-tests/src/test/java/org/junit/platform/console/options/PicocliCommandLineOptionsParserTests.java
- platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/DefaultParallelExecutionConfigurationStrategyTests.java
The `value` parameter of the `EnumSource` annotation is now optional.
When omitted, the declared type of the first method parameter is used.
The test will fail if it does not reference an enum type.
Resolves #1973.
---
> Auto-detect enum type from method signature

- documentation/src/docs/asciidoc/release-notes/release-notes-5.6.0-M1.adoc
- junit-platform-commons/src/main/java/org/junit/platform/commons/util/PackageUtils.java
- junit-platform-commons/src/module/org.junit.platform.commons/module-info.java
- platform-tests/src/test/java/org/junit/platform/commons/util/PackageUtilsTests.java
- platform-tooling-support-tests/projects/jar-describe-module/junit-platform-commons.expected.txt
Solves #1995 by implementing a custom version of `SourceVersion.isName()`.
---
---
> Drop java.compiler dependence in org.junit.platform.commons

- platform-tooling-support-tests/platform-tooling-support-tests.gradle.kts
- platform-tooling-support-tests/projects/ant-starter/build.xml
- platform-tooling-support-tests/projects/gradle-starter/build.gradle.kts
- platform-tooling-support-tests/projects/maven-starter/pom.xml
- platform-tooling-support-tests/projects/vintage/pom.xml
- platform-tooling-support-tests/src/main/java/platform/tooling/support/Request.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/AntStarterTests.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/GradleKotlinExtensionsTests.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/GradleMissingEngineTests.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/GradleStarterTests.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/JavaVersionsTests.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/MavenStarterTests.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/MultiReleaseJarTests.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/VintageGradleIntegrationTests.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/VintageMavenIntegrationTests.java
Instead of disabling the tests on Java 14, we now run tests for Gradle/Maven/Ant builds with JDK 8. Not only does that remove the need for Gradle to support the latest EA release, it also provides basic coverage that ensures that we can run on Java 8.
---
> Run Gradle/Maven/Ant tests with Java 8

- data/events.json
Changing Devoxx "Junit: time to shift into 5th gear" event date since the schedule has been released.
> Change Devoxx Belgium talk date

- .lgtm.yml
Fix lgtm build due to requiring JDK 12
https://lgtm.com/projects/g/junit-team/junit5
GitHub has acquired Semmle (creators of LGTM).
https://blog.semmle.com/secure-software-github-semmle/?utm_content=101286158&utm_medium=social&utm_source=twitter&hss_channel=tw-4896799426
I wanted to see if Semmle caught any errors against JUnit5 but the build fails because it attempts to use the wrong JDK version. Also, it's currently not possible to use the QL language to query the Java source of Junit5 due to not being able to build properly.
---
---
> Add support for LGTM scanner

- CONTRIBUTING.md
> Fix link to LICENSE.md

- documentation/src/docs/asciidoc/release-notes/release-notes-5.6.0-M1.adoc
- documentation/src/docs/asciidoc/user-guide/writing-tests.adoc
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/CsvArgumentsProvider.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/CsvFileArgumentsProvider.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/CsvFileSource.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/CsvSource.java
- junit-jupiter-params/src/test/java/org/junit/jupiter/params/provider/CsvArgumentsProviderTests.java
- junit-jupiter-params/src/test/java/org/junit/jupiter/params/provider/CsvFileArgumentsProviderTests.java
- junit-jupiter-params/src/test/java/org/junit/jupiter/params/provider/CsvFileSourceMock.java
This PR implements the proposed enhancement in https://github.com/junit-team/junit5/issues/1856 .
It will introduce a `nullSymbols` attribute in the `CsvSource` and `CsvFileSource` Annotation. 
The `nullSymbols` will be converted into `null` if it is found in the CSV.
Resolves #1856 
---
---
> Add null value attribute to CsvSource and CsvFileSource

- junit-platform-engine/src/main/java/org/junit/platform/engine/UniqueId.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/UniqueIdFormat.java
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/execution/TestRun.java
Improves performance Parameterized vintage engine with the following
changes:
- add map to TestRun to track in progress TestDescriptors
- memoize UniqueId#hashCode
- memoize UniqueId#toString
- avoid intermediate char[] allocation when formatting UniqueId
Issue: #2030
---
---
> Improve performance of Vintage engine

- junit-platform-commons/src/main/java/org/junit/platform/commons/util/LruCache.java
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/VintageTestEngine.java
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/descriptor/TestSourceProvider.java
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/descriptor/VintageEngineDescriptor.java
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/descriptor/VintageTestDescriptor.java
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/discovery/RunnerTestDescriptorPostProcessor.java
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/discovery/VintageDiscoverer.java
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/execution/RunListenerAdapter.java
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/execution/RunnerExecutor.java
- junit-vintage-engine/src/test/java/org/junit/vintage/engine/descriptor/TestSourceProviderTests.java
- junit-vintage-engine/src/test/java/org/junit/vintage/engine/descriptor/VintageTestDescriptorTests.java
- junit-vintage-engine/src/test/java/org/junit/vintage/engine/discovery/RunnerTestDescriptorPostProcessorTests.java
- junit-vintage-engine/src/test/java/org/junit/vintage/engine/execution/TestRunTests.java
- junit-vintage-engine/src/test/java/org/junit/vintage/engine/samples/junit4/AbstractJUnit4TestCase.java
- junit-vintage-engine/src/test/java/org/junit/vintage/engine/samples/junit4/ConcreteJUnit4TestCase.java
- platform-tests/src/test/java/org/junit/platform/commons/util/LruCacheTests.java
Prior to this commit, we scanned the hierarchy of a test class for
methods once for every test method. This lead to quadratic runtime
behavior and was problematic for large test classes. Now, the new
`TestSourceProvider` caches the methods of a class so that we only need
to filter that list once for every test method.
Resolves #1965.
---
---
> Cache methods to improve performance of TestSource creation

- junit-platform-reporting/src/main/java/org/junit/platform/reporting/legacy/xml/XmlReportWriter.java
- platform-tests/src/test/java/org/junit/platform/reporting/legacy/xml/XmlReportWriterTests.java
This PR changes the implementation of `XmlReportWriter. writeCDataSafely(...)` to be even safer by always passing valid CDATA content to `javax.xml.stream.XMLStreamWriter.writeCData(...)`.
The current implementation passes a String to `javax.xml.stream.XMLStreamWriter.writeCData(...)` that might not be valid CDATA content, i.e. it might contain `]]>`. This causes issues if the implementation of that method validates its parameter value.
The PR does not change the produced XML, which is covered by `XmlReportWriterTests.writesValidXmlEvenIfExceptionMessageContainsCData()`.
---
---
> Implement safer variant to ensure CDATA end markers result in valid XML

- platform-tests/src/test/java/org/junit/platform/commons/util/GenericClassHierarchiesReflectionUtilsTests.java
Issue #981
These tests show that generic interfaces with a default implementation can lead to unwanted behaviour when selecting a method with a parameter type that extends the used generic type.
---
---
> Reflection testcases

- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TempDirectory.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/TempDirectoryTests.java
Removal of read-only files fails (e.g. for Windows),
so the engine should try making the file writable first.
see #2046
---
---
> Remove read-only files under TempDir

- .github/workflows/main.yml
- README.md
- buildSrc/src/main/kotlin/JavaLibraryExtension.kt
- settings.gradle.kts
We rely on tools such as Gradle, JaCoCo, Asciidoctor, and others and the
past few months have shown that's it's unrealistic to expect all of
them to be compatible with the latest JDK as soon as it's released. For
example, we're currently stuck on JDK 12 because Asciidoctor does not
yet support JDK 13. Since we don't want to compromise the safety of our
contributors, we should not rely on outdated non-LTS releases. Instead,
we now switch back the build to be compatible with the JDK 11 LTS
release which will get security patches until JDK 17 is released.
Closes #2018. Closes #2061. Closes #1906.
> Revert build to use Java 11

- documentation/src/docs/asciidoc/user-guide/writing-tests.adoc
Added information in `writing-tests.adoc` about conditional handling, as it is already present in `extensions.adoc`.
---
---
- [/] There are no TODOs left in the code
- [/] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [/] [Coding conventions](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [/] Change is covered by [automated …
> Improve documentation for writing tests and contional test execution

- junit-platform-launcher/src/main/java/org/junit/platform/launcher/listeners/MutableTestExecutionSummary.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/listeners/TestExecutionSummary.java
Make the `TestExecutionSummary.Failure` interface serializable.
The `Throwable` and `TestIdentifier` classes that are used by this interface are serializable, so it is safe to make it serializable also.
The default implementation `org.junit.platform.launcher.listeners.MutableTestExecutionSummary.DefaultFailure` is also safe to make serializable as it's a simple Java Bean with these two serializable fields.
I need to be able to serialize to disk the failures of a test for [QuickPerf](https://github.com/quick-perf), a tool that I works on a JUnit5 implementation that allows to make rapid performance test with JUnit4 and soon 5. 
As QuickPerf needs to launch a test in a separate JVM we need a way to pass the failures from one JVM to the other, and serializing them to disk is the easiest way …
> Make TestExecutionSummary.Failure serializable

- documentation/src/docs/asciidoc/release-notes/release-notes-5.6.0-M2.adoc
- documentation/src/docs/asciidoc/user-guide/writing-tests.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/condition/AbstractRepeatableAnnotationCondition.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/condition/DisabledIfEnvironmentVariable.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/condition/DisabledIfEnvironmentVariableCondition.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/condition/DisabledIfEnvironmentVariables.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/condition/DisabledIfSystemProperties.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/condition/DisabledIfSystemProperty.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/condition/DisabledIfSystemPropertyCondition.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/condition/EnabledIfEnvironmentVariable.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/condition/EnabledIfEnvironmentVariableCondition.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/condition/EnabledIfEnvironmentVariables.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/condition/EnabledIfSystemProperties.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/condition/EnabledIfSystemProperty.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/condition/EnabledIfSystemPropertyCondition.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/DisabledIfEnvironmentVariableConditionTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/DisabledIfEnvironmentVariableIntegrationTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/DisabledIfSystemPropertyConditionTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/DisabledIfSystemPropertyIntegrationTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/EnabledIfEnvironmentVariableConditionTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/EnabledIfEnvironmentVariableIntegrationTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/EnabledIfSystemPropertyConditionTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/EnabledIfSystemPropertyIntegrationTests.java
Prior to this commit, built-in conditions could not be declared
multiple times for a given annotated element (i.e., class or method).
This prevents users from specifying multiple system properties or
environment variables for which an element should be enabled or
disabled.
This commit introduces repeatable annotation support for
@EnabledIfEnvironmentVariable, @DisabledIfEnvironmentVariable,
@EnabledIfSystemProperty, and @DisabledIfSystemProperty.
Closes: #1793
---
> Support repeatable annotations for built-in conditions

- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/APIGuardianAnnotations.kt
- buildSrc/src/main/kotlin/Versions.kt
- buildSrc/src/main/kotlin/java-library-conventions.gradle.kts
- documentation/src/docs/asciidoc/release-notes/release-notes-5.6.0-M2.adoc
- gradle.properties
- junit-jupiter-migrationsupport/junit-jupiter-migrationsupport.gradle.kts
- junit-platform-console-standalone/junit-platform-console-standalone.gradle.kts
- junit-platform-console/junit-platform-console.gradle.kts
- junit-platform-runner/junit-platform-runner.gradle.kts
- junit-platform-suite-api/junit-platform-suite-api.gradle.kts
- junit-vintage-engine/junit-vintage-engine.gradle.kts
- platform-tooling-support-tests/platform-tooling-support-tests.gradle.kts
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/ManifestTests.java
fixes  #195
Signed-off-by: Raymond Augé <raymond.auge@liferay.com>
Provide JARs with OSGi metadata
---
---
> Provide JARs with OSGi metadata

- documentation/src/docs/asciidoc/release-notes/release-notes-5.6.0-M2.adoc
- documentation/src/docs/asciidoc/user-guide/writing-tests.adoc
- documentation/src/test/java/example/ParameterizedTestDemo.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTest.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTestExtension.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTestMethodContext.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTestNameFormatter.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTestParameterResolver.java
- junit-jupiter-params/src/test/java/org/junit/jupiter/params/ParameterizedTestIntegrationTests.java
- junit-jupiter-params/src/test/java/org/junit/jupiter/params/ParameterizedTestNameFormatterTests.java
Introduced a new `{arguments_with_names}` pattern in `@ParameterizedTest`, which is now used in the default name pattern. The parameter names are included only if they are present in the bytecode and if the parameter types are known (`ArgumentsAccessor` and `ArgumentsAggregator` are therefore ignored).
Closes #2040.
---
---
> Include parameter names in default name of @ParameterizedTest

- junit-platform-reporting/src/main/java/org/junit/platform/reporting/legacy/LegacyReportingUtils.java
- junit-platform-reporting/src/main/java/org/junit/platform/reporting/legacy/xml/XmlReportWriter.java
- platform-tests/src/test/java/org/junit/platform/reporting/legacy/LegacyReportingUtilsTests.java
Moved LegacyReportingUtils from junit-platform-launcher to junit-platform-reporting as being more appropriate. Old implementation in the launcher package left in place for compatibility with 3rd party code, but deprecated for future removal. Resolves #1978.
Left the old unit test in-place to guard against regressions. Future dev should be done in the new copy.
---
> Move LegacyReportingUtils to junit-platform-reporting

- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertIterableEquals.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/AssertIterableEqualsAssertionsTests.java
Prior to this commit an iterable of iterables (here instances of java.nio.file.Path) passed to method `assertIterableEquals` in class `Assertions` of the JUnit Jupiter API yielded a `StackOverflowError`.
This commit prevent the eternal while-loop by leveraging the `equals()`-implementation of the non-null expected element.
Fixes #2157
---
---
> Fix stack overflow error in assertIterableEquals

- buildSrc/src/main/kotlin/java-library-conventions.gradle.kts
- buildSrc/src/main/kotlin/junit4-compatibility.gradle.kts
- dependencies/dependencies.gradle.kts
- documentation/documentation.gradle.kts
- junit-bom/junit-bom.gradle.kts
- junit-jupiter-api/junit-jupiter-api.gradle.kts
- junit-jupiter-engine/junit-jupiter-engine.gradle.kts
- junit-jupiter-migrationsupport/junit-jupiter-migrationsupport.gradle.kts
- junit-jupiter-params/junit-jupiter-params.gradle.kts
- junit-jupiter/junit-jupiter.gradle.kts
- junit-platform-commons/junit-platform-commons.gradle.kts
- junit-platform-console-standalone/junit-platform-console-standalone.gradle.kts
- junit-platform-console/junit-platform-console.gradle.kts
- junit-platform-engine/junit-platform-engine.gradle.kts
- junit-platform-launcher/junit-platform-launcher.gradle.kts
- junit-platform-reporting/junit-platform-reporting.gradle.kts
- junit-platform-runner/junit-platform-runner.gradle.kts
- junit-platform-suite-api/junit-platform-suite-api.gradle.kts
- junit-platform-testkit/junit-platform-testkit.gradle.kts
- junit-vintage-engine/junit-vintage-engine.gradle.kts
- platform-tests/platform-tests.gradle.kts
- platform-tooling-support-tests/platform-tooling-support-tests.gradle.kts
- settings.gradle.kts
The new `dependencies` subproject declares dependency contraints that
are imported in all other subprojects using an `internal` configuration
that is _not_ published in the dependency management section of the
generated POMs nor in Gradle Module Metadata.
> Use platform subproject to manage dependencies

- documentation/src/docs/asciidoc/release-notes/release-notes-5.7.0-M1.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/TestTemplateInvocationContextProvider.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestTemplateTestDescriptor.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/TestTemplateInvocationTests.java
Fix javadoc about empty streams from template invocation context providers and produce more helpful error message.
Resolves #2166.
---
---
**This link is broken... probably should be [this](https://junit.org/junit5/docs/current/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html)**
> Improve error message for TestTemplateInvocationContextProvider

- .github/workflows/cross-version.yml
- .github/workflows/main.yml
- build.gradle.kts
- gradle/build-scan-user-data.gradle
- settings.gradle.kts
This PR configures the Gradle Enterprise plugin to use the https://ge.junit.org Gradle Enterprise server to publish build scans. Build scans are now always published if the user is [authenticated](https://docs.gradle.com/enterprise/gradle-plugin/#authenticating_with_gradle_enterprise). I will create individual users for all core team members so you can create your own access keys for publishing.
The hostname and IP addresses of local builds are now cleared before the build is being published and CI builds always use "github" as their user name to make the [scans list](https://ge.junit.org/scans) more consistent.
Moreover, the build is now configured to use the remote build cache that is built-in to the Gradle Enterprise server so that local builds can reuse task outputs of that have been …
> Use Gradle Enterprise server to upload scans and as remote build cache

- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/LockManager.java
We are conducting a research project on re-ordering Stream APIs for improving program execution speed.
Before and after re-ordering, we measured running time of tests which execute target Stream.
Command for running tests is : 
`time ./gradlew clean -Dtest.single=LockManagerTests test`
and the result is :
```
the order of Stream API      test running time
===============================================
distinct().sorted()                 15.527s
sorted().distinct()                 15.440s
```
---
---
> Re-order Stream API calls

- documentation/src/docs/asciidoc/release-notes/release-notes-5.7.0-M1.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/DisplayNameGenerator.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/DisplayNameUtils.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/DisplayNameGenerationTests.java
This new generator extends `Standard` and removes parenthesis
at the end of method names if they have no parameters.
Resolves #1961.
---
---
> Introduce new `DisplayNameGenerator` named `Simple`

- buildSrc/src/main/kotlin/Versions.kt
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/ArchUnitTests.java
> Upgrade ArchUnit to 0.13.1

- build.gradle.kts
- buildSrc/src/main/kotlin/publishing-conventions.gradle.kts
- platform-tooling-support-tests/platform-tooling-support-tests.gradle.kts
- platform-tooling-support-tests/projects/gradle-kotlin-extensions/build.gradle.kts
- platform-tooling-support-tests/projects/gradle-missing-engine/build.gradle.kts
- platform-tooling-support-tests/projects/gradle-starter/build.gradle.kts
- platform-tooling-support-tests/projects/java-versions/pom.xml
- platform-tooling-support-tests/projects/maven-starter/pom.xml
- platform-tooling-support-tests/projects/multi-release-jar/default/pom.xml
- platform-tooling-support-tests/projects/vintage/build.gradle.kts
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/GradleKotlinExtensionsTests.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/GradleMissingEngineTests.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/GradleStarterTests.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/JavaVersionsTests.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/MavenStarterTests.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/MultiReleaseJarTests.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/VintageGradleIntegrationTests.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/VintageMavenIntegrationTests.java
Instead of polluting the local Maven repository and being potentially
influenced by its other contents, we now publish to a standalone file
repo in build/repo and use it in our Maven/Gradle integration tests.
> Publish to standalone file repo instead of mavenLocal()

- .github/workflows/reproducible-build.yml
- .gitignore
- build.gradle.kts
- buildSrc/src/main/kotlin/java-repackage-jars.gradle.kts
- documentation/src/docs/asciidoc/user-guide/appendix.adoc
- junit-platform-commons/junit-platform-commons.gradle.kts
- junit-platform-console/junit-platform-console.gradle.kts
- src/checkBuildReproducibility.sh
This PR makes the java bytecode generated by this project [reproducible](https://reproducible-builds.org/). This means that under identical builds condition (for example Java version), repeated builds should provide the same output byte-for-byte.
It achieves this by:
* supporting [`SOURCE_DATE_EPOCH`](https://reproducible-builds.org/specs/source-date-epoch/) as a way of fixing build-time-specific metadata added to JARs
* using Gradle's [reproducible archives](https://docs.gradle.org/current/userguide/working_with_files.html#sec:reproducible_archives) functionality to fix timestamps and file ordering within JARs
* re-archiving JARs that are non-deterministic because they use `jar` to rewrite their contents after build.
```shell
#!/bin/bash -e
rm -f checksums*
export …
```
> Make JAR builds reproducible

- build.gradle.kts
- buildSrc/src/main/kotlin/ProjectExtensions.kt
- buildSrc/src/main/kotlin/Versions.kt
- buildSrc/src/main/kotlin/java-library-conventions.gradle.kts
- dependencies/dependencies.gradle.kts
- documentation/documentation.gradle.kts
- gradle.properties
- gradle/testing.gradle.kts
- junit-jupiter-migrationsupport/junit-jupiter-migrationsupport.gradle.kts
- junit-platform-runner/junit-platform-runner.gradle.kts
- junit-platform-suite-api/junit-platform-suite-api.gradle.kts
- junit-vintage-engine/junit-vintage-engine.gradle.kts
- platform-tests/platform-tests.gradle.kts
- platform-tooling-support-tests/platform-tooling-support-tests.gradle.kts
This reduces Gradle script recompilation, and it enables to specify
dependency versions from the command line.
fixes #2234
---
---
> Move versions to gradle.properties

- documentation/src/docs/asciidoc/release-notes/release-notes-5.7.0-M1.adoc
- junit-platform-engine/src/main/java/org/junit/platform/engine/EngineExecutionListener.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/Node.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/NodeTestTask.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/NodeTestTaskContext.java
- junit-platform-launcher/src/testFixtures/java/org/junit/platform/launcher/core/ConfigurationParametersFactoryForTests.java
- platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/HierarchicalTestExecutorTests.java
- Add `Node.DynamicTestExecutor#execute(TestDescriptor,
EngineExecutionListener)` for engines that wish to pass a custom
`EngineExecutionListener` and cancel or wait for the execution of a
submitted test via the returned `Future`.
- Add `EngineExecutionListener.NOOP` and change all declared methods to
have empty default implementations.
Resolves #2188.
---
> Allow using DynamicTestExecutor with custom listener

- dependencies/dependencies.gradle.kts
- documentation/src/docs/asciidoc/release-notes/release-notes-5.7.0-M1.adoc
- gradle.properties
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/MethodSelectorResolver.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/discovery/DiscoverySelectorResolverTests.java
- junit-vintage-engine/junit-vintage-engine.gradle.kts
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/discovery/MethodSelectorResolver.java
- junit-vintage-engine/src/test/java/org/junit/vintage/engine/VintageTestEngineExecutionTests.java
- junit-vintage-engine/src/testFixtures/groovy/org/junit/vintage/engine/samples/spock/SpockTestCaseWithUnrolledAndRegularFeatureMethods.groovy
Spock uses a Groovy AST transform to generate methods during compilation. Thus, `MethodSelector.getJavaMethod()` always threw an exception when selecting a test method by its name in the source code. Thus, the Vintage engine now uses `MethodSelector.getMethodName()` instead of `MethodSelector.getJavaMethod().getName()` which is then correctly used by Spock's Runner for filtering as demonstrated by the added integration test. Moreover, when both Vintage and Jupiter are present, such a `MethodSelector` caused the Jupiter engine to fail during discovery because it could not resolve `MethodSelector.getJavaMethod()` either. Its `MethodSelectorResolver` now checks if a test class is a Jupiter test class before making that call.
---
> Fix selecting Spock methods via MethodSelector

- documentation/src/docs/asciidoc/release-notes/release-notes-5.7.0-M1.adoc
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TempDirectory.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/TempDirectoryTests.java
> Delete files in read-only dirs by making them writable

- documentation/src/docs/asciidoc/release-notes/release-notes-5.7.0-M2.adoc
- junit-platform-reporting/src/main/java/org/junit/platform/reporting/legacy/xml/XmlReportWriter.java
- platform-tests/src/test/java/org/junit/platform/reporting/legacy/xml/XmlReportWriterTests.java
Prior to this commit, characters not allowed according to the XML 1.0
spec where written to the XML reports if present in exception messages
etc. Now, we detect them and replace them with their character
reference.
Fixes #2269.
---
> Replace illegal chars with their char reference

- documentation/src/docs/asciidoc/release-notes/release-notes-5.7.0-M2.adoc
- junit-platform-console/src/main/java/org/junit/platform/console/tasks/DiscoveryRequestCreator.java
- platform-tests/src/test/java/org/junit/platform/console/tasks/DiscoveryRequestCreatorTests.java
Add explicitly selected classes from `--select-class` and `--select-method` to the include patterns passed when constructing the `ClassNameFilter` so that these are always executed regardless of the implicit or explicit class name filter.
Resolves #2259.
---
---
> Execute explicitly selected classes regardless of class name filters

- documentation/src/docs/asciidoc/release-notes/release-notes-5.7.0-M2.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertLinesMatch.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/Assertions.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/AssertLinesMatchAssertionsTests.java
> Introduce Stream<String> variants of assertLinesMatch methods

- documentation/src/docs/asciidoc/release-notes/release-notes-5.7.0-M2.adoc
- junit-platform-commons/src/main/java/org/junit/platform/commons/util/ToStringBuilder.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/LauncherConfigurationParameters.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/LauncherDiscoveryRequestBuilder.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/LauncherFactory.java
- junit-platform-launcher/src/testFixtures/java/org/junit/platform/launcher/core/ConfigurationParametersFactoryForTests.java
- junit-platform-testkit/src/main/java/org/junit/platform/testkit/engine/EngineTestKit.java
- platform-tests/src/test/java/org/junit/platform/launcher/core/LauncherConfigurationParametersTests.java
- platform-tests/src/test/java/org/junit/platform/testkit/engine/EngineTestKitTests.java
> Ignore implicit config params in EngineTestKit by default

- documentation/documentation.gradle.kts
Now that https://github.com/asciidoctor/asciidoctorj/issues/429 is resolved, we can switch to Rouge, assuming it works on Windows.
@sormuras Could you please run `./gradlew asciidoctor asciidoctorPdf` to check the result on Windows?
Resolves #777.
> Switch to Rouge as Asciidoctor syntax highlighter

- documentation/documentation.gradle.kts
- documentation/src/docs/asciidoc/user-guide/index.adoc
- documentation/src/docs/asciidoc/user-guide/overview.adoc
- No longer build release notes PDF
- Link from PDF user guide to HTML release notes
Issue: #770
> Give PDF user guide a better name

- .github/PULL_REQUEST_TEMPLATE.md
The current link leads to a 404.
Note that I also edited the ["Definition of Done" wiki article](https://github.com/junit-team/junit5/wiki/Definition-of-Done), however there I switched to the `current` instead of `snapshot` link by accident. Sorry for this. Let me know if I should correct it.
---
> Fix broken Preconditions link in PULL_REQUEST_TEMPLATE

- .github/workflows/cross-version.yml
- documentation/src/docs/asciidoc/release-notes/release-notes-5.7.0-M2.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/condition/JRE.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/DisabledForJreRangeConditionTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/DisabledForJreRangeIntegrationTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/DisabledOnJreConditionTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/DisabledOnJreIntegrationTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/EnabledForJreRangeConditionTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/EnabledForJreRangeIntegrationTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/EnabledOnJreConditionTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/EnabledOnJreIntegrationTests.java
- Extend JRE enum to support Java 16
- Run additional GitHub Actions build using OpenJDK 16-ea
Resolves #2329.
> Add support for Java 16

- documentation/src/docs/asciidoc/release-notes/release-notes-5.7.0-M2.adoc
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ClassBasedTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ClassTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/NestedClassTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestMethodTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/execution/TestInstancesProvider.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/TestInstancePostProcessorAndPreDestroyCallbackTests.java
Prior to this commit, pre-destroy callbacks were not called when an
instance was created but post-processing it failed. Now, they are always
called if the instance was created, regardless if any subsequent step
failed.
We previously had a test that asserted the old behavior. However, IMHO
the new behavior is more consistent and changing it is ok since
`TestInstancePreDestroyCallback` is still experimental.
Resolves #2312.
> Always call pre-destroy callbacks if instance was created

- CONTRIBUTING.md
While working for #2336 we have found that it could be useful to document the deprecation procedure in more detail in the CONTRIBUTING.md.
---
---
> Describe deprecation in CONTRIBUTING.md

- .github/workflows/cross-version.yml
- .github/workflows/main.yml
- .github/workflows/reproducible-build.yml
This should speed up CI builds as Gradle distributions and external dependencies no longer have to be downloaded each time. Since there are also some Maven integration tests, the local Maven repository is also cached.
---
---
> Cache Gradle wrapper and dependencies on CI builds

- documentation/src/docs/asciidoc/release-notes/release-notes-5.7.0-M2.adoc
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/MethodBasedTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestMethodTestDescriptor.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/TestWatcherTests.java
> Report disabled TestTemplate methods to TestWatchers

- CONTRIBUTING.md
Hello! I want to contribute and found the simplest issue I could: #1007
It is unclear to me whether it was resolved or not since there is a javadoc section under contribute.md. 
I tried to read the linked issue but it seems like the latest versions have their own standards. 
So I added an example section for the javadoc section. If this is good for you I can continue updating the document. 
If the issue is no longer valid then you can discard this merge request. 
Resolves #1007
---
---
> Add examples to Javadoc section in CONTRIBUTING.md

- documentation/README.md
…f the user guide
Hello! I was taking a look at this issue: https://github.com/junit-team/junit5/issues/2315 and I was trying to generate the pdf 
version of the user guide. I had to look around a bit and noticed that the readme was missing information on generating the pdf 
report.
I am actually tacking the issue #2315 now but thought that it would be good to update the readme. Also some outdated stuff
---
---
> Update Asciidoctor instructions

- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertLinesMatch.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/AssertLinesMatchAssertionsTests.java
Prior to this PR, a small number (`42`) of lines were always included in the error message string of `assertLinesMatch`. This arbitrary number of lines did not always contain the lines that did not match. This PR removes the constant number and always emits the two non-matching lines entirely.
The staged matching logic is still working in a "fail-fast mode". The first non-mathing line pair is reported. Subsequent lines are not processed.
Closes #2233
---
---
> Emit entire non-matching lines

- documentation/src/docs/asciidoc/release-notes/release-notes-5.7.0-M2.adoc
- documentation/src/docs/asciidoc/user-guide/writing-tests.adoc
- documentation/src/test/java/example/ParameterizedTestDemo.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/converter/SimpleArgumentConverter.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/converter/TypedArgumentConverter.java
- junit-jupiter-params/src/test/java/org/junit/jupiter/params/converter/TypedArgumentConverterTest.java
> Introduce `TypedArgumentConverter` as a more specific `ArgumentConverter`

- documentation/src/docs/asciidoc/release-notes/release-notes-5.7.0-M2.adoc
- documentation/src/docs/asciidoc/user-guide/writing-tests.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/ExtensionContext.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/config/CachingJupiterConfiguration.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/config/DefaultJupiterConfiguration.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/config/JupiterConfiguration.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/AbstractExtensionContext.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTestExtension.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTestNameFormatter.java
- junit-jupiter-params/src/test/java/org/junit/jupiter/params/ParameterizedTestExtensionTests.java
- junit-jupiter-params/src/test/java/org/junit/jupiter/params/ParameterizedTestIntegrationTests.java
- junit-jupiter-params/src/test/java/org/junit/jupiter/params/ParameterizedTestNameFormatterTests.java
> Truncate arguments in display name if they exceed max length

- documentation/src/docs/asciidoc/release-notes/release-notes-5.7.0-M2.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertTimeout.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/AssertTimeoutAssertionsTests.java
Having a specific name prefix is useful when debugging stack traces to
quickly identify which threads are created by the junit framework and
from where exactly.
---
---
> Use specific name prefix in preemptive timeout threads

- documentation/src/docs/asciidoc/release-notes/release-notes-5.7.0-M2.adoc
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/ForkJoinPoolHierarchicalTestExecutorService.java
This change adds a new constructor `ForkJoinPoolHierarchicalTestExecutorService(ParallelExecutionConfiguration configuration)` so that engines can pass in an instance of `ParallelExecutionConfiguration` directly, instead of having to map it to `ConfigurationParameters` first.
---
---
> Make ForkJoinPoolHierarchicalTestExecutorService easier to use

- documentation/src/docs/asciidoc/release-notes/release-notes-5.7.0-M2.adoc
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/Launcher.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/EngineExecutionOrchestrator.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/InternalTestPlan.java
- platform-tests/src/test/java/org/junit/platform/launcher/core/DefaultLauncherTests.java
The `Launcher` now fails with a descriptive error message when a
previously executed `TestPlan` is attempted to be executed again. The
Javadoc of `Launcher` now clearly states that a TestPlan must not be
executed more than once.
Resolves #2379.
> Prevent multiple executions of a TestPlan

- documentation/src/docs/asciidoc/link-attributes.adoc
- documentation/src/docs/asciidoc/release-notes/release-notes-5.7.0-M2.adoc
- documentation/src/docs/asciidoc/user-guide/writing-tests.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/parallel/Execution.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/parallel/Isolated.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/parallel/ResourceLock.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/ExclusiveResource.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/LockManager.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/NodeTreeWalker.java
- platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/LockManagerTests.java
- platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/NodeTreeWalkerIntegrationTests.java
- platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/ParallelExecutionIntegrationTests.java
- platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/ResourceLockSupport.java
This commit introduces a new global resource lock "__global__" that all
test descriptors that are children of the engine descriptor acquire by
default in READ mode. Using the `@Isolated` annotation in the Jupiter
API causes the mode to be changed to READ_WRITE.
Will eventually resolve #2142.
---
---
> Introduce global default lock to facilitate isolated test execution

- junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/CsvSource.java
- junit-jupiter-params/src/test/java/org/junit/jupiter/params/provider/CsvArgumentsProviderTests.java
Initially, I had intention to make `@CsvSource` support blank quoted strings. But after I made a test, it appeared that `@CsvSource` handles them already. So I just contribute you one unit test.
---
---
> Add tests for whitespace within CsvSource columns

- documentation/src/docs/asciidoc/user-guide/writing-tests.adoc
I removed an unnecessary "a" in the documentation
---
---
- [x ] There are no TODOs left in the code
- [x ] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [ x] [Coding conventions](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [x ] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#tests) including corner …
> Removed an unnecessary "a" in the documentation

- documentation/src/docs/asciidoc/release-notes/release-notes-5.7.0.adoc
- documentation/src/docs/asciidoc/user-guide/extensions.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/ExtensionContext.java
- junit-jupiter-api/src/testFixtures/java/org/junit/jupiter/api/extension/ExtensionContextParameterResolver.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/execution/ExtensionValuesStore.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/extension/CloseableResourceIntegrationTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/execution/ExtensionValuesStoreTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/ExtensionContextExecutionTests.java
- junit-platform-testkit/src/main/java/org/junit/platform/testkit/engine/EventConditions.java
> Close resource in inverse order of addition

- documentation/src/docs/asciidoc/release-notes/release-notes-5.7.0.adoc
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/TestableAnnotationTests.java
- junit-platform-commons/src/main/java/org/junit/platform/commons/annotation/Testable.java
> Let Testable annotation target any declaration element type

- README.md
- documentation/src/docs/asciidoc/user-guide/appendix.adoc
This commit also removes the dependency metadata from the `README.md` file and replaces it with a link to the user guide instead.
Closes #2403
---
---
> Add JUnit Platform JFR in Dependency Metadata and Diagram

- gradle.properties
- settings.gradle.kts
This updates the Gradle Enterprise Gradle plugin to the latest version. This also fixes the usage of an internal api that was moved packages.
---
---
> Update Gradle Enterprise Plugin

- .github/workflows/codeql-analysis.yml
[Blog: Code scanning is now available!](https://github.blog/2020-09-30-code-scanning-is-now-available/)
This adds GitHub's new code scanning feature and GitHub action to the Junit5 repository.
Once merged, scan results will appear (only for maintainers) under https://github.com/junit-team/junit5/security/code-scanning
You can also view the results here: https://lgtm.com/projects/g/junit-team/junit5/alerts
Currently there are no scan results/warnings.
Additionally, new potential vulnerabilities that get introduced via pull request will be flagged inline on the pull request.
---
---
> Enable GitHub Code Scanning Feature

- buildSrc/src/main/kotlin/java-repackage-jars.gradle.kts
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/JarContainsManifestFirstTests.java
Resolves  #2438
- always sort "META-INF/" and "META-INF/MANIFEST.MF" entries first
---
---
> junit-platform-commons 1.7.0 does not contain MANIFEST.MF as first JAR entry (#2438)

- documentation/src/docs/asciidoc/release-notes/release-notes-5.8.0-M1.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/DynamicTestInvocationContext.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/InvocationInterceptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/DynamicTestTestDescriptor.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/extension/ExtensionComposabilityTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/InvocationInterceptorTests.java
Allow dynamic test invocation interceptors to access the dynamic test executable.
Fixes #2399
---
---
> Expose DynamicTest executable to InvocationInterceptors

- buildSrc/src/main/kotlin/osgi-conventions.gradle.kts
We use late-binding to get the project description via Bnd's macro
support instead of having to use afterEvaluate to early-bind to the
project description in the gradle script. 
(I forgot to include this change in the build updates for Bnd 5.2.0.)
---
---
> osgi: Use Bnd macro processing to avoid gradle afterEvaluate

- junit-platform-launcher/src/main/java/org/junit/platform/launcher/listeners/MutableTestExecutionSummary.java
> Use Math.min instead of manual calculation

- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/DisabledCondition.java
- junit-jupiter-migrationsupport/src/main/java/org/junit/jupiter/migrationsupport/conditions/IgnoreCondition.java
> More straightforward usage of Optional

- documentation/src/docs/asciidoc/release-notes/release-notes-5.7.1.adoc
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/descriptor/RunnerTestDescriptor.java
- junit-vintage-engine/src/test/java/org/junit/vintage/engine/VintageTestEngineDiscoveryTests.java
Prior to this commit, legacy reporting names of JUnit 3 suites were not
the fully-qualified test class name but rather some textual description
of the test suite (e.g. "TestSuite with 42 tests [example: ...]"). Now,
the legacy reporting name of top-level test classes reported by the
Vintage engine is always the fully-qualified test class name.
> Ensure consistent top-level test class legacy reporting names

- documentation/src/docs/asciidoc/release-notes/release-notes-5.7.1.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/TestInstancePreDestroyCallback.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/extension/ExtensionComposabilityTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/TestInstanceLifecycleTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/TestInstancePreDestroyCallbackUtilityMethodTests.java
The new utility method helps to ensure all test instances are processed
by a `TestInstancePreDestroyCallback` when used in conjunction with
`@Nested` tests.
Resolves #2430.
---
> Introduce utility method for processing all destroyed test instances

- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/java-library-conventions.gradle.kts
- buildSrc/src/main/kotlin/java-repackage-jars.gradle.kts
- buildSrc/src/main/kotlin/kotlin-library-conventions.gradle.kts
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/DisplayNameGenerator.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/MethodOrderer.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/config/DefaultJupiterConfiguration.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/DisplayNameUtils.java
- junit-jupiter-engine/src/test/kotlin/org/junit/jupiter/engine/kotlin/ArbitraryNamingKotlinTestCase.kt
- junit-platform-engine/src/main/java/org/junit/platform/engine/reporting/ReportEntry.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/HierarchicalTestEngine.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/SameThreadHierarchicalTestExecutorService.java
Fixes existing Java/Kotlin compiler warnings and makes all compile tasks fail on warnings from now on.
---
---
> Fix compiler warnings

- build.gradle.kts
- dependencies/dependencies.gradle.kts
- documentation/src/docs/asciidoc/release-notes/release-notes-5.8.0-M1.adoc
- gradle.properties
- junit-platform-jfr/src/main/java/org/junit/platform/jfr/FlightRecordingListener.java
- platform-tests/platform-tests.gradle.kts
- platform-tests/src/test/java/org/junit/platform/jfr/FlightRecordingListenerIntegrationTests.java
Prior to this commit only tests were reported as JFR events. However,
it's also useful to see events for containers, e.g. test classes, in
particular when they require expensive setup that causes other JFR
events such as garbage collection.
Moreover, this commit adds an integration test using the new JfrUnit
Jupiter extension.
> Report containers as JFR events

- documentation/src/docs/asciidoc/release-notes/release-notes-5.8.0-M1.adoc
- documentation/src/test/java/example/ParameterizedTestDemo.java
- documentation/src/test/resources/two-column.csv
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/converter/DefaultArgumentConverter.java
- junit-jupiter-params/src/test/java/org/junit/jupiter/params/converter/DefaultArgumentConverterTests.java
Hello,
This change adds support for underscores in long numeric literals such as `700_000_000` in `CsvSource` and `CsvFileSource`.
This kind of notation was introduced in Java 1.7 to improve readability of long numbers (https://docs.oracle.com/javase/7/docs/technotes/guides/language/underscores-literals.html).
It is also available in Groovy and Kotlin.
This is the kind of thing that can be done with an `ArgumentConverter`, however it adds a lot of boilerplate code and loose the benefit of better readability / maintability.
Let me know if this is something that you would consider integrating to JUnit-Jupiter.
---
I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-co …
> Support underscores for numeric in CSV sources

- documentation/src/docs/asciidoc/release-notes/release-notes-5.8.0-M1.adoc
- junit-platform-jfr/src/main/java/org/junit/platform/jfr/FlightRecordingDiscoveryListener.java
- junit-platform-jfr/src/main/java/org/junit/platform/jfr/FlightRecordingExecutionListener.java
- junit-platform-jfr/src/main/java/org/junit/platform/jfr/UniqueId.java
- junit-platform-jfr/src/main/resources/META-INF/services/org.junit.platform.launcher.LauncherDiscoveryListener
- junit-platform-jfr/src/main/resources/META-INF/services/org.junit.platform.launcher.TestExecutionListener
- junit-platform-jfr/src/module/org.junit.platform.jfr/module-info.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/LauncherDiscoveryListener.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/DefaultLauncher.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/EngineDiscoveryOrchestrator.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/listeners/discovery/CompositeLauncherDiscoveryListener.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/listeners/discovery/LoggingLauncherDiscoveryListener.java
- junit-platform-launcher/src/testFixtures/java/org/junit/platform/launcher/core/LauncherFactoryForTestingPurposesOnly.java
- junit-platform-testkit/src/main/java/org/junit/platform/testkit/engine/EngineTestKit.java
- platform-tests/src/test/java/org/junit/platform/jfr/FlightRecordingDiscoveryListenerIntegrationTests.java
- platform-tests/src/test/java/org/junit/platform/jfr/FlightRecordingExecutionListenerIntegrationTests.java
- platform-tests/src/test/java/org/junit/platform/launcher/core/DefaultLauncherTests.java
- platform-tests/src/test/java/org/junit/platform/launcher/core/LauncherFactoryTests.java
- platform-tests/src/test/java/org/junit/platform/launcher/listeners/discovery/LoggingLauncherDiscoveryListenerTests.java
- platform-tooling-support-tests/projects/jar-describe-module/junit-platform-jfr.expected.txt
Since test discovery can take a considerable amount of time, we now also
report JFR events on the launcher and engine level.
> Add JFR events for test discovery

- .github/workflows/main.yml
According to their docs, GH Actions workflows don't require a token.
> Remove Codecov token

- documentation/src/docs/asciidoc/release-notes/release-notes-5.8.0-M1.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/parallel/Isolated.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/parallel/Resources.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/ExclusiveResource.java
By documenting the value of `ExclusiveResource.GLOBAL_KEY` test engines that
can not reference constants from a class file may use plain text configuration
to run tests in isolation.
Additionally by documenting the constants used in `Resources` the canonical
resource names are exposed and can be consistently used elsewhere.
Fixes: #2508
---
---
> Document constant value for ExclusiveResource.GLOBAL_KEY

- README.md
Add Revved up by Gradle Enterprise badge to readme.
---
---
> Add Revved up by Gradle Enterprise Badge to Readme

- documentation/src/docs/asciidoc/release-notes/release-notes-5.8.0-M1.adoc
- junit-platform-jfr/src/main/java/org/junit/platform/jfr/FlightRecordingDiscoveryListener.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/LauncherDiscoveryListener.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/listeners/discovery/AbortOnFailureLauncherDiscoveryListener.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/listeners/discovery/CompositeLauncherDiscoveryListener.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/listeners/discovery/LoggingLauncherDiscoveryListener.java
- platform-tests/src/test/java/org/junit/platform/launcher/TestLauncherDiscoveryListener.java
As discussed in today's team call, we're deliberately breaking backwards compatibility of the experimental abstract `LauncherDiscoveryListener` class by changing it to be an interface. This makes it more flexible and consistent with the rest of the codebase, e.g. `TestExecutionListener`.
---
> Make LauncherDiscoveryListener an interface

- documentation/src/docs/asciidoc/user-guide/running-tests.adoc
- documentation/src/test/java/example/testkit/EngineTestKitAllEventsDemo.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertLinesMatch.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/Assertions.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/condition/DisabledIfEnvironmentVariableCondition.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/condition/EnabledIfEnvironmentVariableCondition.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/InvocationInterceptor.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/TestInstanceFactoryTests.java
- junit-platform-commons/src/main/java/org/junit/platform/commons/support/AnnotationSupport.java
- junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/TestDescriptor.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/TestEngine.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/discovery/MethodSelector.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/discovery/SelectorResolver.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/TestIdentifier.java
- junit-platform-runner/src/main/java/org/junit/platform/runner/JUnitPlatform.java
The word simply is used in roughly two situations:
* When used in instructional documentation the word simply often conveys a
value judgement about the complexity of a task. Not only is this
unnecessary, it makes a number of assumptions about the readers familiarity
with the concepts involved and can come across as condescending.
* When used to describe a default implementation, the word simply is used to
to convey that the description is a complete description of the
implementation. This should be unnecessary given the context.
As such nearly all usages of the world simply can be removed without a loss of
clarity.
For more context and a longer argument I found the arguments made Jim Fisher in 
his talk "Don't Say Simply" at Write the Docs Prague 2018[1] to be quite
compelling.
1. …
> Remove spurious usage of the word simply

- documentation/src/docs/asciidoc/release-notes/release-notes-5.8.0-M1.adoc
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/CsvParserFactory.java
- junit-jupiter-params/src/test/java/org/junit/jupiter/params/provider/CsvArgumentsProviderTests.java
Issue: #2527
This change relates to the `@CsvSource` annotation and how its rows are parsed. The underlying library supports comments, by default with the number sign (#), and the support for them was left enabled for the `@CsvSource`. This does not make sense in that the tests just throw a `PreconditionViolationException` in case the number sign is used at the start of a row. So, this pull request disables comment processing for  `@CsvSource` but leaves it enabled for  `@CsvFileSource`, as not to disturb existing, documented functionality.
---
---
- ✓ There are no TODOs left in the …
> Allow rows in @CsvSource to start with a number sign (#)

- platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/ParallelExecutionIntegrationTests.java
Various tests in `ParallelExecutionIntegrationTests` verify that different
tests were indeed executed by different threads. To ensure that an incorrect
implementation does not block the test suite indefinitely these tests contain
an intentional race condition.
This race condition assumes awaiting at most 100ms will be sufficient to schedule
another thread. This assumption is hardware dependent and does not hold on
Github CI[1]. Increasing the maximum time spend waiting by a factor 10 while in CI
is hopefully sufficient.
1. https://github.com/junit-team/junit5/pull/2416/checks?check_run_id=1712237454
```
2021-01-16T02:00:44.8166959Z > Task :platform-tests:test
2021-01-16T02:00:44.8167430Z
2021-01-16T02:00:44.8168932Z ParallelExecutionIntegrationTests > customContextClassLoader() FAILED …
```
> Block parallel tests longer on CI

- documentation/src/docs/asciidoc/release-notes/release-notes-5.7.1.adoc
- junit-platform-engine/src/testFixtures/java/org/junit/platform/engine/support/hierarchical/DemoEngineExecutionContext.java
- junit-platform-engine/src/testFixtures/java/org/junit/platform/engine/support/hierarchical/DemoHierarchicalTestDescriptor.java
- junit-platform-engine/src/testFixtures/java/org/junit/platform/engine/support/hierarchical/DemoHierarchicalTestEngine.java
- junit-platform-reporting/src/main/java/org/junit/platform/reporting/legacy/xml/XmlReportData.java
- junit-platform-reporting/src/main/java/org/junit/platform/reporting/legacy/xml/XmlReportWriter.java
- platform-tests/src/test/java/org/junit/platform/reporting/legacy/xml/LegacyXmlReportGeneratingListenerTests.java
- platform-tests/src/test/java/org/junit/platform/reporting/legacy/xml/XmlReportDataTests.java
Please see individual commits.
Fixes #2537.
> Fix container failure XML reporting

- documentation/src/docs/asciidoc/release-notes/release-notes-5.8.0-M1.adoc
- junit-jupiter-engine/junit-jupiter-engine.gradle.kts
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/execution/ExtensionValuesStoreTests.java
- junit-platform-commons/junit-platform-commons.gradle.kts
- junit-platform-commons/src/testFixtures/java/org/junit/platform/commons/test/ConcurrencyTestingUtils.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/listeners/MutableTestExecutionSummary.java
- platform-tests/platform-tests.gradle.kts
- platform-tests/src/test/java/org/junit/platform/launcher/listeners/SummaryGenerationTests.java
Prior to this commit, concurrently reported failures were stored in an
unguarded `ArrayList` which caused a race condition that sometimes
caused failures to get lost and hence not reported. Now the list of
failures is wrapped in `synchronizedList` to make it thread-safe.
Fixes #2546.
---
> Make SummaryGeneratingListener thread-safe

- junit-jupiter-api/src/main/java/org/junit/jupiter/api/Assumptions.java
As discussed in https://github.com/junit-team/junit5/discussions/2553, improves the documentation of the `Assumptions.assumingThat(...)` methods by clarifying that, unlike the other assumptions methods, they do not cause a test to be aborted.
---
> Improve Javadoc for Assumptions.assumingThat

- .github/workflows/main.yml
- .github/workflows/reproducible-build.yml
- README.md
- buildSrc/src/main/kotlin/java-toolchain-conventions.gradle.kts
- junit-platform-commons/junit-platform-commons.gradle.kts
- junit-platform-console/junit-platform-console.gradle.kts
- junit-vintage-engine/junit-vintage-engine.gradle.kts
In preparation for the toolchain upgrade to JDK 16, we now run the build with the JDK 11 LTS version again.
> Use JDK 11 to run Gradle

- documentation/src/docs/asciidoc/user-guide/writing-tests.adoc
Currently the [JUnit 5 User Guide - 2.17.1. Dynamic Test Examples](https://junit.org/junit5/docs/current/user-guide/#writing-tests-dynamic-tests) includes several examples, but the documentation forgets to mention one of those:
```java
DynamicTest[] dynamicTestsFromArray() { ... }
```
---
> Document array of dynamic tests in the User Guide

- documentation/src/docs/asciidoc/release-notes/release-notes-5.8.0-M2.adoc
- junit-platform-commons/src/main/java/org/junit/platform/commons/util/ClasspathScanner.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/StandaloneTests.java
Fix `getRootUrisForPackage()` in class `ClasspathScanner` by looking for two "wordings" of a package name.
For example, package `foo.bar` is expanded to `foo/bar` and `foo/bar/`. The latter allows find package `foo.bar` in a module called `foo.bar`, and not `foo`.
Fixes #2500
Fixes #2600
Fixes #2612
---
---
> Fix package path computation in `ClasspathScanner`

- documentation/src/docs/asciidoc/release-notes/release-notes-5.7.2.adoc
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/NodeTreeWalker.java
- platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/NodeTreeWalkerIntegrationTests.java
- platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/ParallelExecutionIntegrationTests.java
Prior to this commit, the global read lock was not acquired for test
classes with `@ResourceLock` annotations causing `@Isolated` tests to
run in parallel.
Fixes #2605.
> Acquire global read lock in presence of other exclusive resources

- junit-jupiter-api/src/main/java/org/junit/jupiter/api/Assertions.java
Resolves #2567
See https://github.com/junit-team/junit5/issues/2567#issuecomment-806626091.
The changes currently only adjust the `Assertions` documentation. Should the user guide be adjusted as well?
And should this also be mentioned in the release notes? It is not a behavior change, so I am not sure how relevant it is for the release notes.
---
---
> Clarify intended usage of assert{Not}Equals

- documentation/src/docs/asciidoc/release-notes/release-notes-5.8.0-M2.adoc
- documentation/src/docs/asciidoc/user-guide/writing-tests.adoc
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestFactoryTestDescriptor.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/descriptor/ClassSource.java
- platform-tests/src/test/java/org/junit/platform/engine/support/descriptor/ClassSourceTests.java
* Adding `ClassSource.from(URI)` method, which accepts URIs with a new `class` scheme. The URI details the fully qualified class name and optional `line` and `column` query parameters.
* Hooking that new scheme into `TestFactoryTestDescriptor.fromUri(URI)`, so that such URIs can be supplied when creating dynamic tests
*  Associated unit test and documentation updates
This enables dynamic tests instances to be located using the information available in a StackTraceElement, so it becomes possible to automatically provide test locations by walking the call stack.
These changes are largely a subset of #2431. To the extent that they work, credit goes to @ST-DDT. To the extent that they're broken, blame falls upon me.
Resolves issue: #2635
---
I hereby agree to the terms of the [JUnit …
> Add 'class' URI scheme for dynamic test sources

- documentation/src/docs/asciidoc/release-notes/release-notes-5.8.0-M2.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/DisplayNameGenerator.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/IndicativeSentencesGeneration.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/DisplayNameUtils.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/DisplayNameGenerationTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/IndicativeSentencesNestedTestCase.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/IndicativeSentencesTopLevelTestCase.java
> Fix enclosing class bug in `IndicativeSentences`

- buildSrc/settings.gradle.kts
- buildSrc/src/main/kotlin/osgi-conventions.gradle.kts
- junit-jupiter-migrationsupport/junit-jupiter-migrationsupport.gradle.kts
- junit-platform-console-standalone/junit-platform-console-standalone.gradle.kts
- junit-platform-runner/junit-platform-runner.gradle.kts
- junit-vintage-engine/junit-vintage-engine.gradle.kts
Fixes #2547.
A "regression" in the context of this issue (compared with the current situation) would be if importing API Guardian suddenly became required, as that would break existing systems. To guard against such a regression, I modified the `verifyOSGi` task so that it excludes the API Guardian jar/bundle from consideration by the resolver. Thus the test will prove that API Guardian is not required for resolving JUnit 5 bundles.
---
---
> Optionally import org.apiguardian.api in OSGi metadata

- documentation/src/docs/asciidoc/release-notes/release-notes-5.8.0-M1.adoc
- documentation/src/docs/asciidoc/release-notes/release-notes-5.8.0-M2.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertThrowsExactly.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/Assertions.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/AssertThrowsExactlyAssertionsTests.java
Continuation of #2543.
---
---
> Add `assertThrowsExactly` assertion method

- buildSrc/settings.gradle.kts
- buildSrc/src/main/kotlin/osgi-conventions.gradle.kts
- gradle/libs.versions.toml
Because API Guardian 1.1.2-SNAPSHOT now has OSGi metadata, bumping to this dependency allows Bnd to automatically calculate the correct version of the package to import. This allows removing the extra gymnastics that were inserted to calculate it manually.
Fixes #2547 (again!)
---
---
> Bump API Guardian version to 1.1.2-SNAPSHOT

- documentation/src/docs/asciidoc/release-notes/release-notes-5.8.0-M2.adoc
- documentation/src/docs/asciidoc/user-guide/writing-tests.adoc
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTest.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTestParameterResolver.java
- junit-jupiter-params/src/test/java/org/junit/jupiter/params/ParameterizedTestIntegrationTests.java
> Support AutoCloseable for arguments provided to a @ParameterizedTest

- buildSrc/build.gradle.kts
- gradle/libs.versions.toml
As @gunnarmorling didn't release an early-access version of https://github.com/moditect/jfrunit yet, we want to refer to
a stable version of this library in our tests.
This is achieved by referring to a specific GIT tag and making use of JitPack's feature to build and server Maven-based artifacts.
---
---
> Use stable JfrUnit version via JitPack

- documentation/src/docs/asciidoc/release-notes/release-notes-5.8.0-M2.adoc
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/LauncherConfigurationParameters.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/LauncherDiscoveryRequestBuilder.java
- junit-platform-suite-api/src/main/java/org/junit/platform/suite/api/ConfigurationParameter.java
- junit-platform-suite-api/src/main/java/org/junit/platform/suite/api/DisableParentConfigurationParameters.java
- junit-platform-suite-api/src/main/java/org/junit/platform/suite/api/Suite.java
- junit-platform-suite-commons/src/main/java/org/junit/platform/suite/commons/SuiteLauncherDiscoveryRequestBuilder.java
- junit-platform-suite-engine/src/main/java/org/junit/platform/suite/engine/ClassSelectorResolver.java
- junit-platform-suite-engine/src/main/java/org/junit/platform/suite/engine/DiscoverySelectorResolver.java
- junit-platform-suite-engine/src/main/java/org/junit/platform/suite/engine/SuiteTestDescriptor.java
- platform-tests/src/test/java/org/junit/platform/launcher/core/LauncherConfigurationParametersTests.java
- platform-tests/src/test/java/org/junit/platform/suite/commons/SuiteLauncherDiscoveryRequestBuilderTests.java
- platform-tests/src/test/java/org/junit/platform/suite/engine/SuiteTestDescriptorTests.java
From a practical perspective the expectation is that a `@Suite` annotated class uses the same configuration parameters when discovering tests as the discovery request used to discover the suite.
For example:
When executing a suite with the the `ConsoleLauncher` providing a configuration via `--config=key=value` should have the same effect as configuring this value implicitly as an environment variable via `-Dvalue=key`. However when suites are involved this is not the case. Rather implicit variables are considered while explicit values are ignored.
This surprising to say the least.
This behavior occurs because the `junit-platform-suite-engine` creates a new discovery request - and this includes the implicit configuration by default.
There is also a use case where the suite should neither …
> Discover suite tests using parent configuration parameters

- junit-jupiter-api/src/main/java/org/junit/jupiter/api/ClassOrderer.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/MethodOrderer.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/config/EnumConfigurationParameterConverter.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/config/InstantiatingConfigurationParameterConverter.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/config/InstantiatingConfigurationParameterConverterTests.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/EngineDiscoveryOrchestrator.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/LauncherConfigurationParameters.java
Prior to this commit code in JUnit logged messages via its internal Logging Facade at information level. When a user, a framework, or a tool running JUnit-based tests doesn't explicitly configure logging, the default Java Util Logging frameworks is used, which in turn emits message via `System.err`. Since those messages then appear on some environments red color, they are confusing and somewhat distracting.
This commit replaces all calls of `Logger.info()` to their `config()` variants.
Closes #2664
---
---
> Reduce info logging noise

- documentation/src/docs/asciidoc/release-notes/release-notes-5.8.1.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/ExtensionContext.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/AbstractExtensionContext.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ClassExtensionContext.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/DynamicExtensionContext.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/JupiterEngineExtensionContext.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/MethodExtensionContext.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestTemplateExtensionContext.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/descriptor/ExtensionContextTests.java
- junit-jupiter-params/src/test/java/org/junit/jupiter/params/ParameterizedTestExtensionTests.java
> Provide access to the current ExecutionMode in ExtensionContext

- documentation/src/docs/asciidoc/release-notes/release-notes-5.8.1.adoc
- documentation/src/docs/asciidoc/user-guide/writing-tests.adoc
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/CsvArgumentsProvider.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/CsvSource.java
- junit-jupiter-params/src/test/java/org/junit/jupiter/params/ParameterizedTestIntegrationTests.java
- junit-jupiter-params/src/test/java/org/junit/jupiter/params/provider/CsvArgumentsProviderTests.java
- junit-jupiter-params/src/test/java/org/junit/jupiter/params/provider/MockCsvAnnotationBuilder.java
With the introduction of support for _text blocks_ as a first-class language feature in recent JDKs (preview feature in Java SE 15), we can improve the user experience with `@CsvSource` by allowing the user to provide a text block instead of an array of strings.
Given the following parameterized test using a text block...
```java
@ParameterizedTest
@CsvSource(textBlock = """
apple,         1
banana,        2
'lemon, lime', 0xF1
strawberry,    700_000
""")
void csvSourceWithTextBlock(String fruit, int rank) {
System.out.println(fruit + " : " + rank);
}
```
... the output is:
```
apple : 1
banana : 2
lemon, lime : 241
strawberry : 700000
```
> Introduce support for text blocks in `@CsvSource`

- documentation/src/docs/asciidoc/release-notes/release-notes-5.9.0-M1.adoc
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/EnumSource.java
- junit-jupiter-params/src/test/java/org/junit/jupiter/params/provider/EnumSourceTests.java
Addresses issue #2761 
Introduced MATCH_NONE mode in `EnumSource` which only selects the enum constant if none of the regex matches. Added tests in `EnumSourceTest`
Questions:
- Should I add usage in documentation? Current documentation `ParameterizedTestDemo` only contains `MATCH_ALL ` example. There is scope to add `MATCH_ANY` and `MATCH_NONE`
Todo:
---
---
> Add EnumSource.MATCH_NONE mode

- junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/MethodSource.java
This took me a while to figure out the syntax, so I thought improving the documentation could be beneficial.
As an aside, there are also no tests for `MethodSource` with an inner class.
---
---
Doco-only change, so DoD is not relevant.
> Add an example of inner class fully qualified method name

- documentation/src/docs/asciidoc/user-guide/running-tests.adoc
[Link to view rendered doc](https://github.com/aSemy/junit5/blob/5cb390d90eb29c6e6e957eb701f764af0eaaa59b/documentation/src/docs/asciidoc/user-guide/running-tests.adoc)
A really minor change, but I think using 'because' makes the comment more clear - that it's referring to the the `junit-platform-launcher` dependency.
From [the Gradle docs](https://docs.gradle.org/current/userguide/declaring_dependencies.html#sec:documenting-dependencies)
> ### Documenting Dependencies
>
> When you declare a dependency or a dependency constraint, you can provide a custom reason for the declaration. This makes the dependency declarations in your build script and the dependency insight report easier to interpret.
```kotlin
testImplementation(platform("org.junit:junit-bom:{bom-version}"))
// Only needed to …
```
> Use Gradle `because` to document `junit-platform-launcher` dependency

- documentation/src/docs/asciidoc/user-guide/running-tests.adoc
This enables you to use the compact "jar star" pattern in your classpath.
Partially addresses https://github.com/junit-team/junit5/issues/2788
---
---
> Document how to run the ConsoleLauncher with classpath wildcards

- junit-jupiter-api/src/main/java/org/junit/jupiter/api/Assertions.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/ClassOrderer.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/MethodOrderer.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/TestInfo.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/ParameterContext.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/Constants.java
- junit-platform-commons/src/main/java/org/junit/platform/commons/util/ExceptionUtils.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/TestTag.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/discovery/DiscoverySelectors.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/LauncherConstants.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/LauncherDiscoveryRequestBuilder.java
- junit-platform-testkit/src/main/java/org/junit/platform/testkit/engine/EngineTestKit.java
HTML headers in the documentation of type members (except for nested types) should start at `<h4>`, see https://docs.oracle.com/en/java/javase/17/docs/specs/javadoc/doc-comment-spec.html#html-content
Normally the javadoc tool warns about this, but it looks like this is not the case when executing the `javadoc` task for JUnit. Maybe the build scripts need to be adjusted?
The current usage of `<h3>` causes it to look rather strange because that is the same level as the member name itself.
Example:
([`org.junit.jupiter.api.TestInfo.getDisplayName()`](https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/TestInfo.html#getDisplayName()))
---
I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052 …
> Use correct HTML heading levels in Javadoc

- buildSrc/build.gradle.kts
- settings.gradle.kts
Bump up Gradle plugin dependencies
---
---
> Upgrade Gradle enterprise plugin dependencies

- .github/workflows/cross-version.yml
Use https://github.com/oracle-actions/setup-java to download and install an OpenJDK 18 build from https://jdk.java.net
---
---
> Use `oracle-actions/setup-java` to install JDK

- junit-jupiter-api/src/main/java/org/junit/jupiter/api/ClassOrderer.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/DisplayNameGeneration.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/DisplayNameGenerator.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/MethodOrderer.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/TestClassOrder.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/TestInstance.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/TestMethodOrder.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/Timeout.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/io/TempDir.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/parallel/Execution.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/Constants.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/config/JupiterConfiguration.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TempDirectory.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TimeoutConfiguration.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TimeoutExtension.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/TempDirectoryPerContextTests.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTest.java
Triggered by discussion in fd93eeca94479b71ce0d06d61df874a167a3fbf7.
> Use value references in Javadoc to eliminate duplication

- gradle/libs.versions.toml
- platform-tooling-support-tests/platform-tooling-support-tests.gradle.kts
- platform-tooling-support-tests/projects/ant-starter/build.xml
- platform-tooling-support-tests/src/main/java/platform/tooling/support/Request.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/AntStarterTests.java
- Resolve Ant from Maven Central via Gradle
- Resolve Maven from Maven Central via Gradle
---
---
> Fix integration tests by avoiding downloads from archive.apache.org

- documentation/src/docs/asciidoc/release-notes/release-notes-5.9.0-M1.adoc
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TempDirectory.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/CloseablePathCleanupTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/TempDirectoryPerDeclarationTests.java
> Only retry deleting directories when cleaning up `TempDir` once

- .gitattributes
This would avoid merge conflicts on release note files.
> Set merge strategy to `union` for release note files

- documentation/src/docs/asciidoc/release-notes/release-notes-5.9.0-M1.adoc
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/TestPlan.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/EngineDiscoveryOrchestrator.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/EngineExecutionOrchestrator.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/LauncherDiscoveryResult.java
- junit-platform-suite-engine/src/main/java/org/junit/platform/suite/engine/SuiteTestDescriptor.java
- platform-tests/src/test/java/org/junit/platform/suite/engine/SuiteEngineTests.java
- platform-tests/src/test/java/org/junit/platform/suite/engine/SuiteTestDescriptorTests.java
- platform-tests/src/test/java/org/junit/platform/suite/engine/testcases/JUnit4TestsTestCase.java
- platform-tests/src/test/java/org/junit/platform/suite/engine/testcases/TaggedTestTestCase.java
- platform-tests/src/test/java/org/junit/platform/suite/engine/testsuites/MultiEngineSuite.java
> Prune suite discovery result before use

- .github/actions/run-gradle/action.yml
- buildSrc/src/main/kotlin/testing-conventions.gradle.kts
- platform-tooling-support-tests/platform-tooling-support-tests.gradle.kts
This PR enables [Gradle Enterprise Predictive Test Selection](https://gradle.com/gradle-enterprise-solutions/predictive-test-selection/) ([user manual](https://docs.grdev.net/enterprise/predictive-test-selection/)) for local and PR builds. CI builds on `main` and `release/*` will continue to always execute all tests.
> Enable Predictive Test Selection for local and PR builds

- .github/dependabot.yml
Add dependabot configuration to monitor Gradle plugins
> Add dependabot configuration to monitor Gradle plugins

- documentation/src/docs/asciidoc/release-notes/release-notes-5.9.0-M1.adoc
- documentation/src/docs/asciidoc/user-guide/writing-tests.adoc
- documentation/src/test/java/example/MethodSourceParameterResolutionTestDemo.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/MethodArgumentsProvider.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/MethodSource.java
- junit-jupiter-params/src/test/java/org/junit/jupiter/params/provider/MethodArgumentsProviderTests.java
This PR adds the possibility to provide arguments to a `@MethodSource` factory method.
They will be resolved by any registered `ParameterResolver` supporting this type of parameter.
Closes #2191
---
---
> Use registered ParameterResolver(s) when invoking @MethodSource factory methods

- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertIterableEquals.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/AssertIterableEqualsAssertionsTests.java
Issue: #2915
The visited `Iterable` are tracked and the assert fails if a already visited `Iterable` is visited again. This avoids a StackOverflowError.
---
---
> Track already visited pairs of Iterables to avoid stack overflow

- documentation/src/docs/asciidoc/release-notes/release-notes-5.9.0-M2.adoc
- junit-platform-console/src/main/java/org/junit/platform/console/options/AvailableOptions.java
- junit-platform-console/src/main/java/org/junit/platform/console/options/ClasspathEntriesConverter.java
- platform-tests/src/test/java/org/junit/platform/console/options/PicocliCommandLineOptionsParserTests.java
Prior this commit absolute paths on Windows starting with a drive letter like `C:\foo.jar` were always split into two path entries:
- `C`
- `foo.jar`
This commit replaces the too simplistic `split = ";|:"` option conversion with a custom converter for classpath entries taking
current platform's path separator character into account.
Fixes #2905
---
---
> Fix support for absolute path entries on Windows

- documentation/src/docs/asciidoc/release-notes/release-notes-5.9.0-M2.adoc
- documentation/src/docs/asciidoc/user-guide/writing-tests.adoc
- documentation/src/test/java/example/TimeoutDemo.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/Timeout.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/Constants.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/SameThreadTimeoutInvocation.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/SeparateThreadTimeoutInvocation.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TimeoutConfiguration.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TimeoutDuration.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TimeoutExceptionFactory.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TimeoutExtension.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TimeoutInvocationFactory.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/SameThreadTimeoutInvocationTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/SeparateThreadTimeoutInvocationTest.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/TimeoutConfigurationTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/TimeoutExceptionFactoryTest.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/TimeoutExtensionTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/TimeoutInvocationFactoryTest.java
This PR is an attempt to solve the issue #2087, allowing to set the thread mode in the `@Timeout` annotation. 
Instead of calling the enum `Mode`, I called it `ThreadMode` since there was already a configuration parameter called `TIMEOUT_MODE_PROPERTY_NAME` which can lead to confusion.
`INFERRED` is used as default, in case no thread mode is provided by the configuration parameter `SAME_THREAD` is used as default.
---
---
> Add thread mode to @Timeout

- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/SeparateThreadTimeoutInvocationTest.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/TimeoutExtensionTests.java
> Improve stability of timeout tests

- documentation/src/docs/asciidoc/release-notes/index.adoc
- documentation/src/docs/asciidoc/release-notes/release-notes-5.9.0.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertArrayEquals.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertDoesNotThrow.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertEquals.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertFalse.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertInstanceOf.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertIterableEquals.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertLinesMatch.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertNotEquals.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertNotNull.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertNotSame.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertNull.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertSame.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertThrows.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertThrowsExactly.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertTimeout.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertTrue.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertionFailureBuilder.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertionUtils.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/AssertInstanceOfAssertionsTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/AssertThrowsAssertionsTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/AssertThrowsExactlyAssertionsTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/AssertionTestUtils.java
> Introduce AssertionFailureBuilder

- documentation/src/docs/asciidoc/user-guide/writing-tests.adoc
A small typo fix in user guide
---
> Fix @ArgumentsSource annotation name

- documentation/src/docs/asciidoc/release-notes/release-notes-5.9.0.adoc
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/JUnit4VersionCheck.java
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/execution/RunListenerAdapter.java
- junit-vintage-engine/src/main/java/org/junit/vintage/engine/execution/TestRun.java
- junit-vintage-engine/src/test/java/org/junit/vintage/engine/VintageTestEngineExecutionTests.java
- junit-vintage-engine/src/testFixtures/java/org/junit/vintage/engine/samples/junit4/ParameterizedTimingTestCase.java
- junit-vintage-engine/src/testFixtures/java/org/junit/vintage/engine/samples/junit4/ParameterizedWithAfterParamFailureTestCase.java
- junit-vintage-engine/src/testFixtures/java/org/junit/vintage/engine/samples/junit4/ParameterizedWithBeforeParamFailureTestCase.java
In 4.13 testSuiteStarted/Finished were introduced. While top-level test
class events were already reported at the appropriate time, events for
intermediate levels such as iterations of the `Parameterized` runner or
classes executed by the `Suite` runner were created synthetically when
the first test was started and the last test was finished, respectively.
---
---
> Use suite events for more accurate reporting

- documentation/src/docs/asciidoc/user-guide/writing-tests.adoc
- junit-platform-commons/src/main/java/org/junit/platform/commons/util/RuntimeUtils.java
I'm handling an upgrade from JUnit 4 to JUnit 5 and noticed that disabling our timeouts with `-Djunit.jupiter.execution.timeout.mode=disabled_on_debug` is not working as expected.
We use [VSCode](https://code.visualstudio.com/) as our editor/IDE. When using the [Debugger for Java extension](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-debug) to debug tests.
When _ran_ in my project, the following "test" prints `[-ea, -Djunit.jupiter.execution.timeout.mode=disabled_on_debug, -XX:+ShowCodeDetailsInExceptionMessages, -Dfile.encoding=UTF-8]`
When _ran with the debugger_ in my project, the following "test" prints `[-Xdebug, -Xnoagent, -Djava.compiler=NONE, -Xrunjdwp:transport=dt_socket,address=localhost:34399,server=n,suspend=y, -ea, …
> Improve debug mode detection in JUnit Jupiter

- documentation/src/docs/asciidoc/user-guide/running-tests.adoc
I assume `AssertJ` and not `AspectJ` was originally meant to be listed as one of the testing libraries included by `spring-boot-starter-test` 🙂
> Fix documentation typo

- buildSrc/src/main/kotlin/testing-conventions.gradle.kts
> Remove GH Actions specific env vars

- junit-platform-commons/src/main/java/org/junit/platform/commons/util/CollectionUtils.java
There was an invalid method reference in the javadoc for `CollectionUtils.toStream` method. This invalid reference caused `aggregateJavadocs` task to fail, which in turn **failed the whole CI build** (example - https://github.com/junit-team/junit5/runs/7990513854?check_suite_focus=true).
This PR fixes that invalid method reference.
---
---
> Fix CI build failing because of the invalid method reference in the javadoc

- documentation/src/docs/asciidoc/release-notes/release-notes-5.9.1.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertTimeout.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertTimeoutPreemptively.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/Assertions.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/SeparateThreadTimeoutInvocation.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/AssertTimeoutAssertionsTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/AssertTimeoutPreemptivelyAssertionsTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/SeparateThreadTimeoutInvocationTest.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/TimeoutExtensionTests.java
This solves the issue #3000 by allowing to specify which exception should be thrown by the preventive timeout assertion.
---
---
> Fix incorrect timeout failure when assertion fails in separate thread

- buildSrc/settings.gradle.kts
- buildSrc/src/main/kotlin/build-metadata.gradle.kts
- buildSrc/src/main/kotlin/java-library-conventions.gradle.kts
- buildSrc/src/main/kotlin/java-toolchain-conventions.gradle.kts
- buildSrc/src/main/kotlin/org/junit/gradle/java/ExecJarAction.kt
- buildSrc/src/main/kotlin/org/junit/gradle/java/ModulePathArgumentProvider.kt
- buildSrc/src/main/kotlin/org/junit/gradle/java/PatchModuleArgumentProvider.kt
- buildSrc/src/main/kotlin/org/junit/gradle/java/WriteArtifactsFile.kt
- buildSrc/src/main/kotlin/osgi-conventions.gradle.kts
- junit-platform-commons/junit-platform-commons.gradle.kts
- junit-platform-console-standalone/junit-platform-console-standalone.gradle.kts
- junit-platform-console/junit-platform-console.gradle.kts
- Extract ExecJarAction
- Extract CommandLineArgumentProviders to top-level classes
- Configure BND to be compatible with configuration cache
- Move local variables into Action for configuration cache compatibility
- Use local variable instead of project's extra properties
- Extract top-level task class
> Build changes towards configuration cache compatibility

- junit-platform-launcher/src/main/java/org/junit/platform/launcher/TestExecutionListener.java
This PR integrates [@marcphilipp 's comment](https://github.com/junit-team/junit5/issues/2539#issuecomment-766325555) as a note in `TestExecutionListener`'s Javadoc. There are no code changes.
Are there other documents to update as well (guide)?
Fixes: #2539
---
---
> Document concurrency considerations for TestExecutionListener implementations

- documentation/src/docs/asciidoc/release-notes/index.adoc
- documentation/src/docs/asciidoc/release-notes/release-notes-5.10.0-M1.adoc
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/ForkJoinPoolHierarchicalTestExecutorService.java
- platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/ForkJoinPoolHierarchicalTestExecutorServiceTests.java
When an invalid ParallelExecutionConfiguration is provided on Java 9+ the
`ForkJoinPoolHierarchicalTestExecutorService` will fall back to using the
since Java 7 constructor. As a result misconfiguration goes unnoticed. 
Separated the exceptions thrown by finding the Java 9+ constructor from those
thrown by invoking the constructor with an invalid configuration. The former
can be ignored, the latter should not be.
Fixes: #3045
---
---
> Fix fallback to ForkJoinPools Java 7 constructor on Java 9 and higher

- documentation/src/docs/asciidoc/release-notes/index.adoc
- documentation/src/docs/asciidoc/release-notes/release-notes-5.9.2.adoc
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/OverloadedTestMethodTests.java
- junit-platform-console/src/main/java/org/junit/platform/console/tasks/TreePrintingListener.java
- junit-platform-jfr/src/main/java/org/junit/platform/jfr/FlightRecordingExecutionListener.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/TestPlan.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/ExecutionListenerAdapter.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/InternalTestPlan.java
- junit-platform-reporting/src/main/java/org/junit/platform/reporting/legacy/xml/LegacyXmlReportGeneratingListener.java
- junit-platform-runner/src/main/java/org/junit/platform/runner/JUnitPlatform.java
- junit-platform-runner/src/main/java/org/junit/platform/runner/JUnitPlatformRunnerListener.java
- junit-platform-runner/src/main/java/org/junit/platform/runner/JUnitPlatformTestTree.java
- platform-tests/src/test/java/org/junit/platform/launcher/core/DefaultLauncherEngineFilterTests.java
- platform-tests/src/test/java/org/junit/platform/launcher/core/DefaultLauncherTests.java
- platform-tests/src/test/java/org/junit/platform/launcher/core/ExecutionListenerAdapterTests.java
- platform-tests/src/test/java/org/junit/platform/launcher/core/LauncherFactoryTests.java
- platform-tests/src/test/java/org/junit/platform/launcher/core/StreamInterceptingTestExecutionListenerIntegrationTests.java
- platform-tests/src/test/java/org/junit/platform/reporting/legacy/LegacyReportingUtilsTests.java
- platform-tests/src/test/java/org/junit/platform/reporting/legacy/xml/LegacyXmlReportGeneratingListenerTests.java
- platform-tests/src/test/java/org/junit/platform/reporting/legacy/xml/XmlReportDataTests.java
- platform-tests/src/test/java/org/junit/platform/reporting/legacy/xml/XmlReportWriterTests.java
- platform-tests/src/test/java/org/junit/platform/runner/JUnitPlatformRunnerTests.java
- settings.gradle.kts
> Avoid unnecessarily parsing unique IDs

- documentation/src/docs/asciidoc/release-notes/release-notes-5.10.0-M1.adoc
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTestExtension.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTestInvocationContext.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTestMethodContext.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTestParameterResolver.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/aggregator/ArgumentsAccessor.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/aggregator/DefaultArgumentsAccessor.java
- junit-jupiter-params/src/test/java/org/junit/jupiter/params/aggregator/AggregatorIntegrationTests.java
- junit-jupiter-params/src/test/java/org/junit/jupiter/params/aggregator/DefaultArgumentsAccessorTests.java
- junit-jupiter-params/src/test/kotlin/org/junit/jupiter/params/aggregator/ArgumentsAccessorKotlinTests.kt
Adding the possibility to get the invocation index of any ArgumentsAccessor 
Fixes #1668
---
---
> Supply invocation index for @ParameterizedTest to test author 

- buildSrc/src/main/kotlin/java-library-conventions.gradle.kts
Document build cache miss to ease detection of (new) performance regression.
The `shadowJar` task is getting build cache misses due to one of its input changing between builds (`Manifest` file containing _build time_)
https://ge.junit.org/c/tz35q4eso3ktg/we4fflr3ipauu/task-inputs?cacheability=cacheable&expanded=WyJpcGFwaG1zcmhwdDVlLXJvb3RzcGVjJDIkMSJd&task-text=shad#change-ipaphmsrhpt5e-rootSpec$2$1-0-0
Marking the task as non cacheable will prevent from analyzing the same cache miss in the future.
> Document shadowJar cache miss

- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/StreamInterceptor.java
Inner classes that do not reference their enclosing instances can be made static.
This prevents a common cause of memory leaks and uses less memory per instance of the class.
* InnerClassMayBeStatic (1)
> Make inner class static to avoid code smell

- documentation/src/docs/asciidoc/release-notes/release-notes-5.9.2.adoc
- documentation/src/docs/asciidoc/user-guide/advanced-topics/junit-platform-suite-engine.adoc
- junit-platform-suite-engine/src/main/java/org/junit/platform/suite/engine/ClassSelectorResolver.java
- junit-platform-suite-engine/src/main/java/org/junit/platform/suite/engine/SuiteTestDescriptor.java
- platform-tests/src/test/java/org/junit/platform/suite/engine/SuiteEngineTests.java
- platform-tests/src/test/java/org/junit/platform/suite/engine/SuiteTestDescriptorTests.java
- platform-tests/src/test/java/org/junit/platform/suite/engine/testsuites/EmptyCyclicSuite.java
- platform-tests/src/test/java/org/junit/platform/suite/engine/testsuites/ThreePartCyclicSuite.java
It is relatively easy to create a test suite that contains itself by accident. E.g:
```java
package org.example.tag;
@Tag("fast")
public class FastTest {
@Test
public void test() {
System.out.println("I am fast test");
}
}
```
```java
package org.example.tag;
@Tag("slow")
public class SlowTest {
@Test
public void test() {
System.out.println("I am slow test");
}
}
```
```java
package org.example.tag;
@SelectPackages("org.example.tag")
@IncludeTags("fast")
@Suite
public class TestSuite {
}
```
This configuration will result in a a long stack trace with a message explaining that the suite contained a cycle.
```
Configuration error: The suite configuration may not contain a cycle [[engine:junit-platform-suite]/[suite:org.example.tag.TestSuite]/[engine:junit-platform-suite]/[suite:org.example.t …
```
> Stop further suite discovery when encountering a cycle

- documentation/src/docs/asciidoc/user-guide/advanced-topics/engines.adoc
This PR adds a section to the User Guide documenting the requirements for test engines for interoperability with IDEs and build tools.
---
---
> Document minimum requirements for test engines

- documentation/src/docs/asciidoc/release-notes/release-notes-5.10.0-M1.adoc
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ClassBasedTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/JupiterTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/MethodBasedTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestMethodTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/ExtensionRegistry.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/MutableExtensionRegistry.java
- junit-platform-commons/src/main/java/org/junit/platform/commons/util/CollectionUtils.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/CompositeEngineExecutionListener.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/CompositeTestExecutionListener.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/IterationOrder.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/listeners/discovery/CompositeLauncherDiscoveryListener.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/listeners/session/CompositeLauncherSessionListener.java
- platform-tests/src/test/java/org/junit/platform/commons/util/CollectionUtilsTests.java
- platform-tests/src/test/java/org/junit/platform/launcher/core/CompositeEngineExecutionListenerTests.java
- platform-tests/src/test/java/org/junit/platform/launcher/core/CompositeTestExecutionListenerTests.java
- platform-tests/src/test/java/org/junit/platform/launcher/core/LauncherSessionTests.java
- platform-tests/src/test/java/org/junit/platform/launcher/listeners/discovery/CompositeLauncherDiscoveryListenerTests.java
- platform-tests/src/test/java/org/junit/platform/launcher/listeners/session/CompositeLauncherSessionListenerTests.java
- Call TestExecutionListener finish methods in reverse order
- Call EngineExecutionListener.executionFinished method in reverse order
- Call LauncherDiscoveryListener.class finish methods in reverse order
- Call LauncherSessionListener closed method in reverse order
- Reuse CollectionUtils.forEachInReverseOrder
- Optimize common cases
Resolves #3082.
---
---
> Consistently use "wrap semantics" for started/finished and opened/closed listener methods

- documentation/src/docs/asciidoc/release-notes/release-notes-5.10.0-M1.adoc
- documentation/src/docs/asciidoc/user-guide/writing-tests.adoc
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/EmptyArgumentsProvider.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/EmptySource.java
- junit-jupiter-params/src/test/java/org/junit/jupiter/params/ParameterizedTestIntegrationTests.java
Fixes #2791.
This adds support for:
* `Collection` and subtypes with a public no-arg constructor
* `SortedSet`
* `NavigableSet`
* `Map` subtypes with a public no-arg constructor
* `SortedMap`
* `NavigableMap`
---
---
> Add support for concrete Collection/Map types to EmptySource

- documentation/src/docs/asciidoc/user-guide/writing-tests.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/TestInstance.java
Related Stack Overflow post: [What use is @TestInstance annotation in JUnit 5?](https://stackoverflow.com/a/66185596/8583692)
Add another use case for `TestInstace.PER_CLASS` in Kotlin, which is, using regular simple class methods as the method factory for `@MethodSource` (which is used for parameterized tests):
```kotlin
@ParameterizedTest
@MethodSource("generateStrings")
fun `Test strings`(argument: String) {
check(argument.isNotEmpty())
}
private fun generateStrings() = listOf(
"java",
"kotlin"
)
```
---
---
> Document `@MethodSource` as use case for `@TestInstance` per-class lifecycle

- gradle/wrapper/gradle-wrapper.properties
Upgrade the Gradle wrapper to the last stable version 8.1 with an update of `distributionSha256Sum` value 
---
---
> Upgradle to 8.1

- junit-platform-console/src/main/java/org/junit/platform/console/ConsoleLauncher.java
- junit-platform-console/src/main/java/org/junit/platform/console/options/AvailableOptions.java
- junit-platform-console/src/main/java/org/junit/platform/console/options/CommandLineOptions.java
- junit-platform-console/src/main/java/org/junit/platform/console/tasks/ConsoleTestExecutor.java
- junit-platform-console/src/main/java/org/junit/platform/console/tasks/DetailsPrintingListener.java
- junit-platform-console/src/main/java/org/junit/platform/console/tasks/FlatPrintingListener.java
- junit-platform-console/src/main/java/org/junit/platform/console/tasks/TreePrinter.java
- junit-platform-console/src/main/java/org/junit/platform/console/tasks/TreePrintingListener.java
- junit-platform-console/src/main/java/org/junit/platform/console/tasks/VerboseTreePrintingListener.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/TestPlan.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/InternalTestPlan.java
- platform-tests/src/test/java/org/junit/platform/launcher/TestPlanTests.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/StandaloneTests.java
- Add command line option for listing all tests
- Add getter for test identifiers in test plan
- List all tests by skipping them
- Add & implement details printing listener interface
- Omit the arrow symbol when listing tests
- List all tests
- Fix indentation
- Add API annotation
- Fix hierarchy when listing tests in tree mode
- Omit icon when blank
- Add integration test
- Make TestPlan iterable
- Remove unnecessary Supplier
- Add test and fix flat mode
- Add test and fix verbose mode
- Use Visitor instead of Iterator
- Add summary of found containers/tests
- Add tests for summary and none detail modes
---
I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contri …
> Add ConsoleLauncher option to print discovery result

- .github/PULL_REQUEST_TEMPLATE.md
Since CI builds show up as checks on the PR anyway, there's no need for a checkbox.
> Remove superfluous checkbox for CI builds from PR template

- .github/workflows/combine-prs.yml
- gradle/libs.versions.toml
- gradle/plugins/common/build.gradle.kts
- settings.gradle.kts
✅ The following pull requests have been successfully combined on this PR:
- #3257 Bump github/combine-prs from 3.1.0 to 3.1.1
- #3256 Bump com.gradle:gradle-enterprise-gradle-plugin from 3.12.6 to 3.13
- #3255 Bump io.github.classgraph:classgraph from 4.8.153 to 4.8.157
- #3254 Bump com.gradle.enterprise from 3.12.6 to 3.13
- #3253 Bump io.github.gradle-nexus.publish-plugin from 1.2.0 to 1.3.0
- #3252 Bump com.diffplug.spotless:spotless-plugin-gradle from 6.17.0 to 6.18.0
- #3251 Bump org.apache.groovy:groovy from 4.0.10 to 4.0.11
> This PR was created by the [`github/combine-prs`](https://github.com/github/combine-prs) action
> Combined PRs

- documentation/src/docs/asciidoc/release-notes/release-notes-5.10.0-M1.adoc
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TempDirectory.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/TempDirectoryPerDeclarationTests.java
- Include root cause when failing to delete file
- Improve error message when root could not be deleted
---
---
> Fix temp dir error reporting for undeletable files

- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/DynamicTestTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/discovery/DiscoverySelectorResolverTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/TempDirectoryPerDeclarationTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/TimeoutConfigurationTests.java
- platform-tests/src/test/java/org/junit/platform/AbstractEqualsAndHashCodeTests.java
- platform-tests/src/test/java/org/junit/platform/commons/util/ClasspathScannerTests.java
- platform-tests/src/test/java/org/junit/platform/console/tasks/DiscoveryRequestCreatorTests.java
- platform-tests/src/test/java/org/junit/platform/console/tasks/TreeNodeTests.java
- platform-tests/src/test/java/org/junit/platform/engine/support/descriptor/CompositeTestSourceTests.java
- platform-tests/src/test/java/org/junit/platform/launcher/TagFilterTests.java
- platform-tests/src/test/java/org/junit/platform/launcher/core/DefaultLauncherTests.java
Slight refactoring of AssertJ assertions into shorter, more descriptive and generating better error messages.
---
---
> Use proper AssertJ assertions

- README.md
[![Maven Central](https://img.shields.io/maven-central/v/org.junit.jupiter/junit-jupiter)](https://search.maven.org/artifact/org.junit.jupiter/junit-jupiter)
---
> Add Maven Central badges

- documentation/src/docs/asciidoc/release-notes/release-notes-5.10.0-M1.adoc
- junit-platform-engine/src/main/java/org/junit/platform/engine/discovery/ClassSelector.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/discovery/DiscoverySelectors.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/discovery/MethodSelector.java
- platform-tests/src/test/java/org/junit/platform/engine/discovery/ClassSelectorTests.java
- platform-tests/src/test/java/org/junit/platform/engine/discovery/DiscoverySelectorsTests.java
- platform-tests/src/test/java/org/junit/platform/engine/discovery/MethodSelectorTests.java
> Add `selectClass()`/`selectMethod()` variants in `DiscoverySelectors` that take a `ClassLoader`

- documentation/src/docs/asciidoc/release-notes/release-notes-5.10.0-M1.adoc
- junit-platform-engine/src/main/java/org/junit/platform/engine/discovery/ClassSelector.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/discovery/DiscoverySelectors.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/discovery/MethodSelector.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/discovery/NestedClassSelector.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/discovery/NestedMethodSelector.java
- platform-tests/src/test/java/org/junit/platform/engine/discovery/ClassSelectorTests.java
- platform-tests/src/test/java/org/junit/platform/engine/discovery/DiscoverySelectorsTests.java
- platform-tests/src/test/java/org/junit/platform/engine/discovery/MethodSelectorTests.java
- platform-tests/src/test/java/org/junit/platform/engine/discovery/NestedClassSelectorTests.java
- platform-tests/src/test/java/org/junit/platform/engine/discovery/NestedMethodSelectorTests.java
- Reduce number of internal constructors
- Support explicit ClassLoader in NestedClassSelector
- Support explicit ClassLoader in NestedMethodSelector
---
> Add explicit ClassLoader support for NestedClass/MethodSelectors

- gradle/plugins/common/src/main/kotlin/junitbuild.spotless-conventions.gradle.kts
Fix a cache miss on `platform-tests` due to these changing inputs:
> Ignore build folders for spotlessDocumentation

- junit-platform-console/src/main/java/org/junit/platform/console/options/MainCommand.java
- platform-tests/src/test/java/org/junit/platform/console/ConsoleLauncherIntegrationTests.java
When explicitly specifying the `execute` subcommand as advised by:
> WARNING: Delegated to the 'execute' command.
>          This behaviour has been deprecated and will be removed in a future release.
>          Please use the 'execute' command directly.
... it happens that `ConsoleLauncher.run` returns a `CommandResult` whose `getValue` method always returns `Optional.empty()` instead of the expected (non-empty) `Optional<TestExecutionSummary>`.
It turns out that, when `picocli` executes a _subcommand_, it doesn't propagate the return value to the parent `CommandLine`, whose `getExecutionResult` method then returns `null`.
There was a question about it last year (https://github.com/remkop/picocli/issues/1656) answered by the [user …
> Return subcommand execution result

- gradle/plugins/common/src/main/kotlin/junitbuild.osgi-conventions.gradle.kts
Eagerly configure Jar tasks to create the BundleTaskExtension prior to the Gradle compileClasspath configuration becoming locked and triggering it's beforeLocking callback to run.  This allows the BND extension to modify the LibraryElements attribute on that configuration and request a variant with the "jar" value prior to Gradle automatically modifying the attribute to request the "classes" value.  This ensures jars are present on the classpath for BND to use when checked for exported classes to use when building the manifest.  If it only uses the classes directory for this task, it will not have access to version information and will not write version info to the manifest it is assembling for the current project, causing the verifyOSGi task to fail.
Addresses issue bndtools/bnd#5695 and …
> Work around bndtools/bnd#5695 by configuring jar tasks eagerly

- documentation/src/docs/asciidoc/release-notes/release-notes-5.10.0-RC1.adoc
- documentation/src/docs/asciidoc/user-guide/running-tests.adoc
- gradle/plugins/common/src/main/kotlin/junitbuild.testing-conventions.gradle.kts
- junit-platform-commons/src/main/java/org/junit/platform/commons/util/ExceptionUtils.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/TestDescriptor.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/LauncherConstants.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/EngineExecutionOrchestrator.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/StackTracePruningEngineExecutionListener.java
- platform-tests/src/test/java/org/junit/platform/StackTracePruningTests.java
- platform-tests/src/test/java/org/junit/platform/commons/util/ExceptionUtilsTests.java
- platform-tests/src/test/java/org/junit/platform/engine/support/descriptor/AbstractTestDescriptorTests.java
- platform-tests/src/test/java/org/junit/platform/launcher/core/LauncherFactoryTests.java
- platform-tests/src/test/java/org/junit/platform/reporting/legacy/xml/LegacyXmlReportGeneratingListenerTests.java
> Revise stacktrace pruning

- documentation/src/docs/asciidoc/release-notes/release-notes-5.10.0-RC1.adoc
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TempDirectory.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/TempDirectoryPerContextTests.java
Fixes https://github.com/junit-team/junit5/issues/3352.
---
---
> Set readonly attribute to false if `DosFileAttributeView` is supported

- .github/workflows/cross-version.yml
- documentation/src/docs/asciidoc/release-notes/release-notes-5.10.0-RC1.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/condition/JRE.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/DisabledForJreRangeConditionTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/DisabledForJreRangeIntegrationTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/DisabledOnJreConditionTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/DisabledOnJreIntegrationTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/EnabledForJreRangeConditionTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/EnabledForJreRangeIntegrationTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/EnabledOnJreConditionTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/EnabledOnJreIntegrationTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/JRETests.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/StandaloneTests.java
> Add JRE.JAVA_22

- junit-jupiter-params/src/main/java/org/junit/jupiter/params/support/AnnotationConsumer.java
The [`AnnotationConsumer`](https://junit.org/junit5/docs/5.10.0-RC1/api/org.junit.jupiter.params/org/junit/jupiter/params/support/AnnotationConsumer.html) Javadoc page currently displays `{@link #accept}` as follows:
With this change, `{@link #accept accept}` is displayed as follows (locally generated):
---
> Use explicit link label in AnnotationConsumer Javadoc

- documentation/src/docs/asciidoc/user-guide/writing-tests.adoc
- documentation/src/test/java/example/TempDirectoryDemo.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/AnnotatedElementContext.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/ParameterContext.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/io/TempDirFactory.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TempDirectory.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/config/DefaultJupiterConfigurationTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/CloseablePathCleanupTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/TempDirectoryPerContextTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/TempDirectoryPerDeclarationTests.java
> Provide access to source element annotations for `TempDirFactory`

- junit-platform-console/src/main/java/org/junit/platform/console/options/MainCommand.java
- junit-platform-console/src/main/java17/org/junit/platform/console/options/ConsoleUtils.java
- platform-tests/src/test/java/org/junit/platform/console/ConsoleLauncherTests.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/StandaloneTests.java
Fixes #3419 by disabling Picocli's usage help auto width computation and tweaking tests.
---
---
> Disable Picocli's usage help auto width computation

- gradle/libs.versions.toml
- junit-platform-console/src/main/java/org/junit/platform/console/options/MainCommand.java
Update picocli to 4.7.5 and enable help width computation in JUnit's console launcher application.
---
---
> Update picocli to 4.7.5 and enable help width computation

- gradle/wrapper/gradle-wrapper.properties
Bumps Gradle Wrapper from 8.4-rc-3 to 8.4.
Release notes of Gradle 8.4 can be found here:
https://docs.gradle.org/8.4/release-notes.html
> Bump Gradle Wrapper from 8.4-rc-3 to 8.4

- gradle/plugins/common/src/main/kotlin/junitbuild.publishing-conventions.gradle.kts
Minor Gradle code cleanup.
---
> Drop duplicate `isSnapshot` variable in Gradle build script

- documentation/src/docs/asciidoc/release-notes/release-notes-5.10.1.adoc
- junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java
- platform-tests/src/test/java/org/junit/platform/commons/util/AnnotationUtilsTests.java
- platform-tests/src/test/java/org/junit/platform/commons/util/ReflectionUtilsTests.java
- platform-tests/src/test/java/org/junit/platform/commons/util/pkg1/SuperclassWithStaticPackagePrivateBeforeMethod.java
- platform-tests/src/test/java/org/junit/platform/commons/util/pkg1/subpkg/SubclassWithNonStaticPackagePrivateBeforeMethod.java
> Apply method predicate before searching type hierarchy

- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AfterAll.java
Looks like this was a copy & paste error from the same text from `@BeforeAll`.
---
---
> Fix typo in AfterAll documentation

- documentation/src/docs/asciidoc/release-notes/release-notes-5.11.0-M1.adoc
- junit-platform-launcher/src/module/org.junit.platform.launcher/module-info.java
- platform-tooling-support-tests/projects/jar-describe-module/junit-platform-launcher.expected.txt
Fixes #3561 by including the new LauncherInterceptor service in the module metadata for the launcher JPMS module.
Otherwise in the context of Java Modules, it cannot use ServiceLoader to look up implementations of LauncherInterceptor.
---
---
> Allow `LauncherInterceptor`s to be discovered when the launcher is used as a Java module

- gradle/wrapper/gradle-wrapper.properties
Bumps Gradle Wrapper from 8.5-rc-3 to 8.5.
Release notes of Gradle 8.5 can be found here:
https://docs.gradle.org/8.5/release-notes.html
> Bump Gradle Wrapper from 8.5-rc-3 to 8.5

- documentation/src/docs/asciidoc/release-notes/release-notes-5.11.0-M1.adoc
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/store/NamespacedHierarchicalStore.java
- platform-tests/src/test/java/org/junit/platform/engine/support/store/NamespacedHierarchicalStoreTests.java
Prior to this commit, the error message just contained the key and the requiredType, but gave no indication what was actually present. Now, the error message also includes the type of the actual value as well as its toString() representation.
---
---
> Improve error message for Store requiredType mismatch

- .github/workflows/cross-version.yml
- documentation/src/docs/asciidoc/release-notes/release-notes-5.11.0-M1.adoc
- gradle.properties
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/condition/JRE.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/DisabledForJreRangeConditionTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/DisabledForJreRangeIntegrationTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/DisabledOnJreConditionTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/DisabledOnJreIntegrationTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/EnabledForJreRangeConditionTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/EnabledForJreRangeIntegrationTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/EnabledOnJreConditionTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/EnabledOnJreIntegrationTests.java
Add JDK 23-ea CI build to "test early and often". See also: https://wiki.openjdk.org/display/quality/Quality+Outreach
---
---
> Extend `JRE` enum to support Java 23

- gradle/wrapper/gradle-wrapper.properties
Bumps Gradle Wrapper from 8.6-rc-2 to 8.6.
Release notes of Gradle 8.6 can be found here:
https://docs.gradle.org/8.6/release-notes.html
> Bump Gradle Wrapper from 8.6-rc-2 to 8.6

- gradle/wrapper/gradle-wrapper.properties
Bumps Gradle Wrapper from 8.7-rc-4 to 8.7.
Release notes of Gradle 8.7 can be found here:
https://docs.gradle.org/8.7/release-notes.html
> Bump Gradle Wrapper from 8.7-rc-4 to 8.7

- documentation/src/docs/asciidoc/user-guide/running-tests.adoc
- gradle/plugins/common/src/main/kotlin/junitbuild.testing-conventions.gradle.kts
> Disable Log4J JMX beans creation in tests to avoid overhead

- .github/actions/main-build/action.yml
- .github/actions/run-gradle/action.yml
- .github/workflows/gradle-dependency-submission.yml
- .github/workflows/main.yml
With the introduction of `gradle/actions/dependency-submission`, it is now simpler (and recommended) to use a separate workflow for generation and submission of GitHub Dependency Graph.
This workflow attempts to detect and submit all dependencies that would be resolved during build execution, without requiring the execution of any particular task. In basic testing it appears that the generated dependency graph contains the same dependencies as before.
A few things to note:
The new workflow will submit a dependency graph with a different "correlator" to the previous one. This means that duplicate dependencies (and alerts) may appear until the older graph ages out and is automatically purged. (Period of days).
Manually dismissed Dependabot Alerts may need to be re-dismissed after switching …
> Add separate `dependency-submission` workflow for GitHub actions

- documentation/src/docs/asciidoc/release-notes/release-notes-5.11.0-M1.adoc
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TempDirectory.java
In `TempDirectory`'s cleanup logic, while walking the temp directory, the file walker may fail to visit a file that has been removed by another thread or process. In this case, JUnit should ignore the `NoSuchFileException`, because there's nothing to clean up.
I have observed such failures when using JGit to manage repositories in temporary directories. JGit uses lock files that it cleans up in background threads. JGit and JUnit will race to delete the lock file, and the JUnit `TempDirectory` cleanup fails when JGit wins that race.
I considered what an automated test for this new behavior would look like. I could add a clear-box test that uses high-level concurrency objects to make sure that the test can delete a file between the time that the `SimpleFileVisitor` lists the temp directory …
> Ignore `NoSuchFileException` in `TempDir` cleanup

- documentation/src/docs/asciidoc/release-notes/release-notes-5.11.0-M1.adoc
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/listeners/UniqueIdTrackingListener.java
- platform-tests/src/test/java/org/junit/platform/launcher/listeners/UniqueIdTrackingListenerIntegrationTests.java
- platform-tooling-support-tests/projects/graalvm-starter/build.gradle.kts
- platform-tooling-support-tests/projects/graalvm-starter/settings.gradle.kts
- platform-tooling-support-tests/projects/graalvm-starter/src/test/java/com/example/project/ClassLevelAnnotationTests.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/GraalVmStarterTests.java
- **Update to latest version of native build tools**
- **Add failing integration test**
- **Track descendants of skipped containers**
- **Add to release notes**
Fixes #3745.
> Fix class-level execution conditions on GraalVM

- documentation/src/docs/asciidoc/release-notes/release-notes-5.11.0-M2.adoc
- gradle/plugins/common/src/main/kotlin/junitbuild.java-library-conventions.gradle.kts
- platform-tooling-support-tests/projects/reflection-tests/build.gradle.kts
- platform-tooling-support-tests/projects/reflection-tests/settings.gradle.kts
- platform-tooling-support-tests/projects/reflection-tests/src/test/java/ReflectionTestCase.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/ReflectionCompatibilityTests.java
By enabling `-parameters` their names are written to the compiled bytecode in addition to the synthetic flag thereby avoiding to trip up the `Method#getParameters` API when running on JDK 8.
Fixes #3797.
> Fix reflection issue on JDK 8 for synthetic bridge methods

- documentation/src/docs/asciidoc/release-notes/release-notes-5.11.0-M2.adoc
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/TestIdentifier.java
- platform-tests/src/test/java/org/junit/platform/launcher/TestIdentifierTests.java
Fix `NullPointerException` when a `TestIdentifier` with no `parentId` is deserialized.
Issue: #3819
---
---
> Fix NPE when deserializing `TestIdentifier`

- documentation/src/docs/asciidoc/release-notes/release-notes-5.11.0-M2.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/ClassOrderer.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/MethodOrderer.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/RandomOrdererUtils.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/SharedOrderingSeed.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/RandomlyOrderedTests.java
Prior to this commit the default seeds were generated separately but the
configuration parameter that allows using a fixed seed only allowed to
set both to the same value making it impossible to reproduce a failure
for different default seeds. Since the default seed is now identical,
this scenario is avoided.
Fixes #3817.
> Use same default seed for method and class ordering

- documentation/documentation.gradle.kts
- gradle/plugins/common/src/main/kotlin/junitbuild.build-metadata.gradle.kts
Rename artifacts before attestation to include information which snapshot revision is being published.
Note that the information used by Maven (as in `<lastUpdated>20240606092913</lastUpdated>` of https://oss.sonatype.org/content/repositories/snapshots/org/junit/jupiter/junit-jupiter/maven-metadata.xml) is not available at this stage of the release/publish process.
Addresses part of #3128 
---
---
> Rename artifacts before attestation

- documentation/src/docs/asciidoc/user-guide/extensions.adoc
- documentation/src/test/java/example/HttpServerDemo.java
- documentation/src/test/java/example/extensions/HttpServerExtension.java
- documentation/src/test/java/example/extensions/HttpServerResource.java
Issue: #1555
Added an explanation in the user guide for how `CloseableResource` can be used, with an example using an `HttpServer` resource.
---
---
> Document how to use `CloseableResource`

- documentation/src/docs/asciidoc/release-notes/release-notes-5.11.0-RC1.adoc
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/AbstractExtensionContext.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ClassBasedTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ClassExtensionContext.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/DynamicExtensionContext.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/DynamicNodeTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/JupiterEngineDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/JupiterEngineExtensionContext.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/MethodExtensionContext.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestMethodTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestTemplateExtensionContext.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestTemplateTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/execution/DefaultExecutableInvoker.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/api/extension/ExecutableInvokerIntegrationTests.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/descriptor/ExtensionContextTests.java
- **Add failing test**
- **Use current context and registry when instantiating ExecutableInvoker**
- **Document in release notes**
Fixes #3905.
---
---
> Use current context and registry when instantiating ExecutableInvoker

- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TempDirectory.java
- junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/CloseablePathTests.java
See https://github.com/junit-team/junit5/pull/3901#discussion_r1699972486.
---
---
> Ensure `TempDir` cleanup is executed when validation fails

- documentation/src/docs/asciidoc/release-notes/release-notes-5.11.0.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/io/TempDir.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TempDirectory.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/extension/CloseablePathTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/extension/TempDirectoryPerDeclarationTests.java
> Let `@TempDir` fail fast with `File` annotated element and non-default file system temp directory

- documentation/src/docs/asciidoc/release-notes/release-notes-5.11.0.adoc
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/CsvFileSource.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/CsvParserFactory.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/CsvSource.java
- jupiter-tests/src/test/java/org/junit/jupiter/params/provider/CsvArgumentsProviderTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/params/provider/CsvFileArgumentsProviderTests.java
> Allow potentially unlimited maxCharsPerColumn in Csv{File}Source

- documentation/src/docs/asciidoc/release-notes/release-notes-5.11.1.adoc
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/CompositeLock.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/SingleLock.java
`SingleLock` uses a `ForkJoinPool.ManagedBlocker` for efficient blocking in a fork-join pool. In the `isReleasable()` method it calls `tryLock()` without remembering the outcome. The `block` method also unconditionally called `lockInterruptibly()` even if the lock was already acquired. The problem that can arise is that the lock is acquired multiple times, but only released once.
`CompositeLockManagedBlocker` is also updated, so that `block()` checks for `acquired` before locking.
---
---
> Fix potential double acquisition in `SingleLock`

- documentation/src/docs/asciidoc/release-notes/release-notes-5.12.0-M1.adoc
- junit-platform-console/src/main/java/org/junit/platform/console/options/AnsiColorOptionMixin.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/StandaloneTests.java
Fix support for `NO_COLOR` environment variable by initializing the `boolean disableAnsiColors` correctly.
---
---
> Fix `NO_COLOR` support

- .github/renovate.json5
It's easier to revert updates if they're from separate PRs.
> Delete custom groups

- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/CompositeLock.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/ForkJoinPoolHierarchicalTestExecutorService.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/LockManager.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/NodeTestTask.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/ResourceLock.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/SingleLock.java
- platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/ForkJoinDeadLockTests.java
- platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/ForkJoinPoolHierarchicalTestExecutorServiceTests.java
- platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/LockManagerTests.java
- platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/ResourceLockTests.java
- platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/SingleLockTests.java
fixes #3945
This PR actually fixes the problem that was attempted in #3936. 
That PR is still valid on its own, although it didn't fix the actual problem.
The release notes still apply for this as well.
---
---
> Fix deadlock in `ForkJoinPoolHierarchicalTestExecutorService`

- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/ForkJoinPoolHierarchicalTestExecutorService.java
When running Spock's tests with the latest snapshot, `pop()` seems to
have been called without a prior call to `push()` on the `Deque` of
resource locks.
> Ensure nesting is only decremented when lock was acquired successfully

- documentation/src/docs/asciidoc/user-guide/writing-tests.adoc
- documentation/src/test/java/example/AssertionsDemo.java
> Document benefits of `messageSupplier` in `Assertions`

- documentation/src/docs/asciidoc/release-notes/release-notes-5.11.1.adoc
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/ForkJoinPoolHierarchicalTestExecutorService.java
- platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/ParallelExecutionIntegrationTests.java
- **Fix/suppress warnings**
- **Add failing test case**
- **Run isolated tasks after all other tasks**
- **Add to release notes**
Resolves #3928.
> Run isolated tasks last

- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/NodeTreeWalker.java
- platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/NodeTreeWalkerIntegrationTests.java
Only acquire global read/write lock on the nodes immediately below the
engine descriptor and ignore other locks when a global read-write lock
is requested.
> Simplify global lock coarsening

- gradle/plugins/code-generator/src/main/kotlin/junitbuild/generator/GenerateJreRelatedSourceCode.kt
This has been handled by updating to Shadow 8.3.2
Follow up https://github.com/junit-team/junit5/pull/3969#issuecomment-2342918871.
---
> Remove the workaround for updating Shadow 8.3.1

- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/CompositeLock.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/ExclusiveResource.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/ForkJoinPoolHierarchicalTestExecutorService.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/LockManager.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/NopLock.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/ResourceLock.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/SingleLock.java
- platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/CompositeLockTests.java
- platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/ForkJoinPoolHierarchicalTestExecutorServiceTests.java
- platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/LockManagerTests.java
- platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/ResourceLockTests.java
- platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/SingleLockTests.java
This allows tasks with only read locks to be stolen by threads that are
currently holding only read locks.
> Allow for work stealing when only holding read locks

- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestTemplateTestDescriptor.java
> Reduce stack utilization of TestTemplateTestDescriptor::execute

- documentation/src/docs/asciidoc/release-notes/release-notes-5.12.0-M1.adoc
- documentation/src/docs/asciidoc/user-guide/writing-tests.adoc
- documentation/src/test/java/example/ParameterizedTestDemo.java
- junit-jupiter-params/src/jmh/java/org/junit/jupiter/params/ParameterizedTestNameFormatterBenchmarks.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTestExtension.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTestMethodContext.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTestSpiInstantiator.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/aggregator/ArgumentsAggregator.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/converter/ArgumentConverter.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/ArgumentsProvider.java
- jupiter-tests/src/test/java/org/junit/jupiter/params/ParameterizedTestExtensionTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/params/ParameterizedTestIntegrationTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/params/ParameterizedTestMethodContextTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/params/ParameterizedTestNameFormatterTests.java
- **Allow ArgumentsProvider implementations to use constructor injection**
- **Allow ArgumentConverter implementations to use constructor injection**
- **Allow ArgumentsAggregator implementations to use constructor injection**
- **Document constructor injection support in release notes**
Resolves #4018.
---
---
> Add constructor injection support for ParameterizedTest SPIs

- documentation/src/docs/asciidoc/release-notes/release-notes-5.11.2.adoc
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/NodeExecutionAdvisor.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/NodeTreeWalker.java
- platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/ParallelExecutionIntegrationTests.java
Prior to this change additional locks were not cleared from siblings 
when discovering the global read-write lock on a test descriptor which 
led to incompatible locks and caused test execution to fail.
Fixes #4027.
---
---
> Fix global read-write lock handling when not declared on top level

- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ClassBasedTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ClassTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ExclusiveResourceCollector.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/JupiterTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/MethodBasedTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/NestedClassTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ResourceLockAware.java
- platform-tests/src/test/java/org/junit/platform/engine/support/descriptor/ResourceLocksProviderTests.java
Instead of looking up annotations on the declaring and all enclosing
classes for each test method, each `ResourceLockAware` test descriptor
now delegates to the `ExclusiveResourceCollector` of its ancestors which
cache the class-level annotations and `ResourceLocksProvider` instances.
Resolves #2677.
---
---
> Avoid multiple class-level annotation lookups

- documentation/src/docs/asciidoc/release-notes/release-notes-5.12.0-M1.adoc
- junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java
- jupiter-tests/src/test/java/org/junit/jupiter/params/converter/DefaultArgumentConverterTests.java
- platform-tests/src/test/java/org/junit/platform/commons/util/ReflectionUtilsTests.java
> Support `void` and `Void` class lookups in `ReflectionUtils`

- documentation/src/docs/asciidoc/release-notes/release-notes-5.12.0-M1.adoc
- documentation/src/docs/asciidoc/user-guide/writing-tests.adoc
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TempDirectory.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/extension/TempDirectoryPerContextTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/extension/TempDirectoryPerDeclarationTests.java
This was made possible by lifting the `ParameterResolver` limitation for
accessing the test-scoped `ExtensionContext` for test class constructors
in #3445.
---
---
> Add constructor injection support for `TempDir`

- junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/TestInstantiationAwareExtension.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/Constants.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/config/CachingJupiterConfiguration.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/config/DefaultJupiterConfiguration.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/config/JupiterConfiguration.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ClassBasedTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/execution/ExtensionContextSupplier.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/execution/ParameterResolutionUtils.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/execution/InterceptingExecutableInvokerTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/extension/TestInstanceFactoryTests.java
The new `junit.jupiter.extensions.testClassInstanceConstruction.extensionContextScope.default` configuration parameters allows to change the default extension context scope introduced in #4062 to allow checking for compatibility issues of existing extensions without having to change their implementation.
---
---
> Introduce configuration parameter for default extension context scope

- jupiter-tests/src/test/java/org/junit/jupiter/engine/extension/InvocationInterceptorTests.java
Check scope of supplied `ExtensionContext` in tests of `InvocationInterceptor`.
---
---
> Add tests for extension context scope supplied to InvocationInterceptor

- documentation/src/docs/asciidoc/user-guide/extensions.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/InvocationInterceptor.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/ParameterResolver.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/TestInstanceFactory.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/TestInstancePostProcessor.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/TestInstancePreConstructCallback.java
> Polish documentation for test-scoped extension context opt-in

- documentation/src/docs/asciidoc/release-notes/release-notes-5.12.0-M1.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/TestTemplateInvocationContextProvider.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestTemplateTestDescriptor.java
- junit-jupiter-params/src/jmh/java/org/junit/jupiter/params/ParameterizedTestNameFormatterBenchmarks.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTest.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTestExtension.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTestMethodContext.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTestParameterResolver.java
- jupiter-tests/src/test/java/org/junit/jupiter/api/extension/KitchenSinkExtension.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/TestTemplateInvocationTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/params/ParameterizedTestExtensionTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/params/ParameterizedTestIntegrationTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/params/ParameterizedTestMethodContextTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/params/ParameterizedTestNameFormatterTests.java
Add a flag to ParameterizedTest to control arguments requirement. This allows users to explicitly opt out from validation of arguments set count and silently skip a test if no arguments are provided
In general, support TestTemplateInvocationContextProvider returning zero invocation contexts. Such providers must override new interface method to indicate that the framework should expect "no context returned"
Resolves #1477
Implemented the team decision described in [this comment](https://github.com/junit-team/junit5/issues/1477#issuecomment-1919412893)
---
---
> Introduce zero invocations in test templates and parameterized tests

- documentation/src/docs/asciidoc/release-notes/release-notes-5.12.0-M1.adoc
- junit-platform-console/src/main/java/org/junit/platform/console/options/TestDiscoveryOptions.java
- junit-platform-console/src/main/java/org/junit/platform/console/options/TestDiscoveryOptionsMixin.java
- junit-platform-console/src/main/java/org/junit/platform/console/tasks/DiscoveryRequestCreator.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/AbstractMethodFilter.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/ExcludeMethodFilter.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/IncludeMethodFilter.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/MethodFilter.java
- platform-tests/src/test/java/org/junit/platform/console/ConsoleLauncherIntegrationTests.java
- platform-tests/src/test/java/org/junit/platform/console/options/CommandLineOptionsParsingTests.java
- platform-tests/src/test/java/org/junit/platform/console/tasks/DiscoveryRequestCreatorTests.java
- platform-tests/src/test/java/org/junit/platform/launcher/MethodFilterTests.java
Issue: #3107
Solves [#3107](https://github.com/junit-team/junit5/issues/3107).
After referring to other Filters (such as TagFilter), I am not sure if I should implement both IncludeMethodFilter and ExcludeMethodFilter, please let me know if I should remove IncludeMethodFilter.
---
---
> Introduce method filter support in the ConsoleLauncher

- documentation/src/docs/asciidoc/release-notes/release-notes-5.11.3.adoc
- junit-platform-commons/junit-platform-commons.gradle.kts
- junit-platform-commons/src/main/java/org/junit/platform/commons/util/PackageNameUtils.java
- junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java
- junit-platform-commons/src/main/java9/org/junit/platform/commons/util/PackageNameUtils.java
- platform-tooling-support-tests/projects/vintage/src/test/java/DefaultPackageTest.java
- **Add reproducer for #4076**
- **Handle Class.getPackage() returning `null` for default package on Java 8**
---
---
> Fix package name comparison on Java 8

- junit-jupiter-api/src/main/java/org/junit/jupiter/api/Assumptions.java
> Document that assertions and exceptions take precedence over assumptions

- documentation/src/docs/asciidoc/release-notes/release-notes-5.12.0-M1.adoc
- junit-platform-commons/src/main/java/org/junit/platform/commons/util/ResourceUtils.java
- junit-platform-console/src/main/java/org/junit/platform/console/options/SelectorConverter.java
- junit-platform-console/src/main/java/org/junit/platform/console/options/TestDiscoveryOptionsMixin.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/descriptor/ClasspathResourceSource.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/descriptor/UriSource.java
- platform-tests/src/test/java/org/junit/platform/console/options/CommandLineOptionsParsingTests.java
> Add support for passing line and column number to ConsoleLauncher via `--select-file` and `--select-resource`

- documentation/src/docs/asciidoc/release-notes/release-notes-5.12.0-M1.adoc
- junit-platform-console/src/main/java/org/junit/platform/console/options/SelectorConverter.java
- junit-platform-console/src/main/java/org/junit/platform/console/options/TestDiscoveryOptions.java
- junit-platform-console/src/main/java/org/junit/platform/console/options/TestDiscoveryOptionsMixin.java
- platform-tests/src/test/java/org/junit/platform/console/options/CommandLineOptionsParsingTests.java
> Add `--select-unique-id` support to ConsoleLauncher

- .github/actions/main-build/action.yml
- .github/workflows/cross-version.yml
- .github/workflows/reproducible-build.yml
- documentation/documentation.gradle.kts
- documentation/src/docs/asciidoc/release-notes/release-notes-5.12.0-M1.adoc
- gradle/libs.versions.toml
- gradle/plugins/common/src/main/kotlin/junitbuild.testing-conventions.gradle.kts
- junit-platform-console-standalone/junit-platform-console-standalone.gradle.kts
- junit-platform-console/junit-platform-console.gradle.kts
- junit-platform-reporting/junit-platform-reporting.gradle.kts
- junit-platform-reporting/src/main/java/org/junit/platform/reporting/open/xml/JUnitContributor.java
- junit-platform-reporting/src/main/resources/META-INF/services/org.opentest4j.reporting.tooling.spi.htmlreport.Contributor
- junit-platform-reporting/src/module/org.junit.platform.reporting/module-info.java
- junit-platform-reporting/src/testFixtures/java/org/junit/platform/reporting/open/xml/OpenTestReportGenerationSystemPropertyOverride.java
- junit-platform-reporting/src/testFixtures/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
- platform-tests/platform-tests.gradle.kts
- platform-tests/src/test/java/org/junit/platform/reporting/legacy/xml/XmlReportWriterTests.java
- platform-tests/src/test/java/org/junit/platform/reporting/open/xml/JUnitContributorTests.java
- platform-tests/src/test/java/org/junit/platform/reporting/open/xml/OpenTestReportGeneratingListenerTests.java
- platform-tests/src/test/resources/junit-platform.properties
- platform-tooling-support-tests/platform-tooling-support-tests.gradle.kts
- platform-tooling-support-tests/projects/jar-describe-module/junit-platform-reporting.expected.txt
- platform-tooling-support-tests/projects/maven-starter/pom.xml
- platform-tooling-support-tests/projects/multi-release-jar/default/pom.xml
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/ArchUnitTests.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/JarDescribeModuleTests.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/ModularUserGuideTests.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/StandaloneTests.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/ToolProviderTests.java
When creating the event-based XML report, the `OpenTestReportGeneratingListener` includes JUnit-specific metadata: type, unique ID, and legacy reporting name. This PR implements open-test-reporting's `Contributor` SPI to include that data in the new HTML report of open-test-reporting.
---
> Add JUnit-specific metadata to open-test-reporting's HTML report

- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/Constants.java
- junit-platform-commons/src/main/java/org/junit/platform/commons/util/ClassNamePatternFilterUtils.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/LauncherConstants.java
- platform-tests/src/test/java/org/junit/platform/commons/util/ClassNamePatternFilterUtilsTests.java
Issue: #3717
I've already worked on this in my personal repository, and since there’s a large amount of code changes, I decided to split it into two PRs.
https://github.com/YongGoose/junit5/commit/a2ef07f02a0fd7e4980931bd2ea2f390f53962fa
I plan to proceed in the following two ways.
1. Add an include method to ClassNamePatternFilterUtils.
2. Implement include and exclude filtering when calling registerAutoDetectedExtensions in MutableExtensionRegistry.
- https://github.com/junit-team/junit5/pull/4115
The link above is the PR for the first step.
---
---
> Add include matching on ClassNamePatternFilterUtils

- documentation/src/docs/asciidoc/release-notes/release-notes-5.12.0-M1.adoc
- junit-platform-reporting/src/main/java/org/junit/platform/reporting/open/xml/OpenTestReportGeneratingListener.java
- platform-tests/src/test/java/org/junit/platform/reporting/open/xml/OpenTestReportGeneratingListenerTests.java
- platform-tooling-support-tests/projects/java-versions/pom.xml
- platform-tooling-support-tests/projects/maven-starter/pom.xml
- platform-tooling-support-tests/projects/maven-surefire-compatibility/pom.xml
- platform-tooling-support-tests/projects/multi-release-jar/default/pom.xml
- platform-tooling-support-tests/projects/vintage/pom.xml
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/GlobalResource.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/JavaVersionsTests.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/LocalMavenRepo.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/MavenRepoProxy.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/MavenStarterTests.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/MavenSurefireCompatibilityTests.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/MultiReleaseJarTests.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/VintageMavenIntegrationTests.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/XmlAssertions.java
Write Git metadata (introduced in https://github.com/ota4j-team/open-test-reporting/pull/180) to infrastructure section of Open Test Report XML output.
---
> Include Git metadata in Open Test Report XML output

- platform-tooling-support-tests/projects/graalvm-starter/settings.gradle.kts
- platform-tooling-support-tests/projects/gradle-kotlin-extensions/settings.gradle.kts
- platform-tooling-support-tests/projects/gradle-missing-engine/settings.gradle.kts
- platform-tooling-support-tests/projects/gradle-starter/settings.gradle.kts
- platform-tooling-support-tests/projects/reflection-tests/settings.gradle.kts
- platform-tooling-support-tests/projects/vintage/settings.gradle.kts
When sample Gradle projects run from integration tests use a JDK provisioned via Gradle, toolchain repositories need to be defined to avoid a Gradle 9.0 deprecation warning.
> Configure toolchain repositories to avoid deprecation warning

- platform-tests/src/test/java/org/junit/platform/reporting/open/xml/OpenTestReportGeneratingListenerTests.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/XmlAssertions.java
fix test to allow git origin urls starting with "git@"
---
---
> Fix test to allow Git origin URLs starting with `git@`

- platform-tooling-support-tests/platform-tooling-support-tests.gradle.kts
When a user has the JAVA_TOOL_OPTIONS set in their environment, java will print "Picked up JAVA_TOOL_OPTIONS: ..." on the error stream.
This leads to failure in some of the Platform Tooling Tests
---
---
> Remove JAVA_TOOL_OPTIONS when running platform tooling supports tests

- documentation/src/docs/asciidoc/release-notes/release-notes-5.12.0-M1.adoc
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTest.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTestExtension.java
- jupiter-tests/src/test/java/org/junit/jupiter/params/ParameterizedTestExtensionTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/params/ParameterizedTestIntegrationTests.java
This is supposed to resolve the Issue #4137
---
---
> Rename requireArguments to allowZeroInvocations

- documentation/src/docs/asciidoc/release-notes/release-notes-5.12.0-M1.adoc
- gradle/plugins/common/src/main/kotlin/junitbuild/exec/RunConsoleLauncher.kt
- junit-platform-console/src/main/java/org/junit/platform/console/ConsoleLauncher.java
- junit-platform-console/src/main/java/org/junit/platform/console/options/CommandFacade.java
- junit-platform-console/src/main/java/org/junit/platform/console/options/MainCommand.java
- junit-platform-console/src/main/java/org/junit/platform/console/options/OutputConfig.java
- junit-platform-console/src/main/java/org/junit/platform/console/options/OutputStreamConfig.java
- platform-tests/src/test/java/org/junit/platform/console/ConsoleLauncherTests.java
- platform-tests/src/test/java/org/junit/platform/console/ConsoleLauncherWrapper.java
Prior to this PR, `ConsoleLauncher` created `PrintWriters` that wouldn't flush automatically when `println` is called which stopped the `testfeed` details mode from being useful. Moreover, it didn't initialized them with the right `Charsets`. Now, we rely on Picocli's initialization again which does both correctly.
---
> Enable auto-flushing of output to fix `testfeed` details mode

- documentation/src/docs/asciidoc/link-attributes.adoc
- documentation/src/docs/asciidoc/release-notes/release-notes-5.12.0-M1.adoc
- documentation/src/docs/asciidoc/user-guide/writing-tests.adoc
- documentation/src/test/java/example/sharedresources/ChildrenSharedResourcesDemo.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/parallel/ResourceLock.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/parallel/ResourceLockTarget.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ExclusiveResourceCollector.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/MethodBasedTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ResourceLockAware.java
- platform-tests/src/test/java/org/junit/platform/engine/support/descriptor/ResourceLockAnnotationTests.java
Issue: #3102
Allow declaring "shared resources" for _direct_ child nodes via the new `@ResourceLock(target = CHILDREN)` attribute.
Using the `@ResourceLock(target = CHILDREN)` in a class-level annotation has the same semantics as adding an annotation with the same `value` and `mode` to each test method and nested test class declared in this class.
This may improve parallelization when a test class declares a `READ` lock, but only a few methods hold a `READ_WRITE` lock.
---
---
> Allow declaring exclusive resources for child nodes

- .github/actions/run-gradle/action.yml
- gradle/scripts/checkBuildReproducibility.sh
- junit-platform-reporting/src/main/java/org/junit/platform/reporting/open/xml/JUnitContributor.java
- **Adapt to API change in open-test-reporting**
- **Force checking for new snapshots on CI**
---
---
> Adapt to API change in open-test-reporting

- documentation/src/docs/asciidoc/release-notes/release-notes-5.12.0-M1.adoc
- documentation/src/test/kotlin/example/KotlinAssertionsDemo.kt
- junit-jupiter-api/src/main/kotlin/org/junit/jupiter/api/Assertions.kt
- jupiter-tests/src/test/kotlin/org/junit/jupiter/api/KotlinAssertTimeoutAssertionsTests.kt
- jupiter-tests/src/test/kotlin/org/junit/jupiter/api/KotlinAssertionsTests.kt
Resolves #1866. 
Introduced `assertNull`, `assertNotNull` methods. 
Introduced contracts for `assertNull`, `assertNotNull`, `assertThrows` and `assertDoesNotThrow` methods.
Added smart casting tests for `assertInstanceOf` methods.
---
---
> Add contracts to Kotlin-specific assertions

- .github/workflows/cross-version.yml
- documentation/src/docs/asciidoc/release-notes/release-notes-5.11.4.adoc
- documentation/src/docs/asciidoc/release-notes/release-notes-5.12.0-M1.adoc
- gradle/base/code-generator-model/src/main/resources/jre.yaml
Add `JRE.JAVA_25` constant and JDK 25 CI build
Closes #4177
---
---
> Add JRE.JAVA_25

- documentation/documentation.gradle.kts
- documentation/src/docs/asciidoc/release-notes/release-notes-5.12.0-M1.adoc
- documentation/src/docs/asciidoc/user-guide/advanced-topics/junit-platform-reporting.adoc
- gradle/plugins/common/src/main/kotlin/junitbuild.testing-conventions.gradle.kts
- junit-platform-reporting/src/main/java/org/junit/platform/reporting/open/xml/OpenTestReportGeneratingListener.java
- platform-tests/src/test/java/org/junit/platform/reporting/open/xml/OpenTestReportGeneratingListenerTests.java
- platform-tooling-support-tests/platform-tooling-support-tests.gradle.kts
Related PR: https://github.com/ota4j-team/open-test-reporting/pull/231
> Report captured output using OTR's new dedicated XML element

- documentation/src/docs/asciidoc/release-notes/release-notes-5.12.0-M1.adoc
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/StreamInterceptor.java
- platform-tests/src/test/java/org/junit/platform/launcher/core/StreamInterceptorTests.java
When using frameworks or running external processes, test output is
often written on other threads than the test. When tests are executed
sequentially that output can be attributed unambiguously to the current
test. If tests are run in parallel, picking the right test to attribute
output to becomes much harder, though.
> Attribute non-test thread output to most recent test thread

- junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTestExtension.java
- jupiter-tests/src/test/java/org/junit/jupiter/params/ParameterizedTestExtensionTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/params/ParameterizedTestIntegrationTests.java
> Fail `@ParameterizedTest` if there are no registered `ArgumentProviders`

- .github/workflows/release.yml
- gradle/plugins/common/src/main/kotlin/junitbuild.temp-maven-repo.gradle.kts
- gradle/plugins/common/src/main/kotlin/junitbuild/release/VerifyBinaryArtifactsAreIdentical.kt
This workflow is supposed to be triggered manually _after_ release
artifacts have been uploaded to a staging repository and the
corresponding Git tag has been pushed to GitHub.
To ensure their integrity and reproducibility, the workflow rebuilds
all binary artifacts and verifies that their checksums are identical to
those in the staging repository.
> Add workflow to verify reproducibility of binary release artifacts

- .github/workflows/release.yml
The new GitHub Actions workflow updates sample projects to use the version about to be releases, injects the staging repository, and builds all samples.
Depends on:
- https://github.com/junit-team/junit5-samples/pull/510
> Automate verification of releases artifact consumability

- .github/scripts/waitForMavenCentralSync.sh
- .github/scripts/waitForUrl.sh
- .github/workflows/release.yml
- **Add job for releasing the staging repository**
- **Add job for publishing documentation**
- **Add job for closing the GitHub milestone of the release**
- **Add job for waiting for sync to Maven Central**
- **Add job for updating samples after sync to Maven Central was successful**
- **Add job for creating a GitHub release**
```
╭───────────────────────────────────╮ ╭─────────────────────────────────╮
│ Verify artifacts are reproducible │ │ Verify artifacts are consumable │
╰───────────────────────────────────╯ ╰─────────────────────────────────╯
⬇
╭────────────────────────────╮
│ Release staging repository │
╰────────────────────────────╯
⬇
╭────────────────────────────────╮ ╭───────────────────────╮ ╭────────────────────────╮
│ Wait for sync to Maven Central │ │ Publish documentation …
```
> Automate post-release steps

- documentation/src/docs/asciidoc/release-notes/release-notes-5.12.0-M1.adoc
- documentation/src/docs/asciidoc/user-guide/writing-tests.adoc
- documentation/src/test/java/example/ParameterizedTestDemo.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/EnumArgumentsProvider.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/EnumSource.java
- jupiter-tests/src/test/java/org/junit/jupiter/params/provider/EnumArgumentsProviderTests.java
> Introduce from and to attributes on @EnumSource (#4185)

- documentation/src/docs/asciidoc/user-guide/appendix.adoc
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/ClasspathAlignmentChecker.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/ClasspathAlignmentCheckingLauncherInterceptor.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/EngineDiscoveryOrchestrator.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/EngineExecutionOrchestrator.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/LauncherFactory.java
- platform-tests/platform-tests.gradle.kts
- platform-tests/src/test/java/org/junit/platform/launcher/core/ClasspathAlignmentCheckerTests.java
- platform-tooling-support-tests/projects/maven-starter/pom.xml
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/JavaVersionsTests.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/MavenEnvVars.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/MultiReleaseJarTests.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/UnalignedClasspathTests.java
The Launcher now checks for classpath alignment in case a LinkageError
such as a ClassNotFoundError is thrown from one of the methods of the
Launcher or TestEngine interfaces. If it finds unaligned versions, it
wraps the LinkageError in a JUnitException with a message listing the
detected versions and a link to the User Guide.
Resolves #3935.
> Check for classpath alignment on LinkageErrors

- documentation/src/docs/asciidoc/user-guide/extensions.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/AnnotatedElementContext.java
- junit-platform-commons/src/main/java/org/junit/platform/commons/support/AnnotationSupport.java
Resolves: #4058 
- Update the Javadoc for both `AnnotationSupport.isAnnotated()` variants to reflect this.
- Update the User Guide documentation for `AnnotationSupport` to reflect this, if applicable.
- Update the Javadoc for `AnnotatedElementContext.isAnnotated()` to reflect this.
---
> Document that `AnnotationSupport.isAnnotated()` does not find repeatable annotations

- junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java
`Class.forName()` from `java.base/java.lang` has built-in support for array type names matching:
- _Primitive arrays such as "[I", "[[[[D", etc._ and
- _Object arrays such as "[Ljava.lang.String;", etc._
This pull request deletes the redundant implementation from JUnit's internal `ReflectionUtils` helper.
---
---
> Remove custom array handling already covered by `Class.forName()`

- documentation/src/docs/asciidoc/release-notes/release-notes-5.12.0-M1.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/DisplayNameGenerator.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/DisplayNameUtils.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/MethodBasedTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/NestedClassTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestFactoryTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestMethodTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestTemplateTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/ClassSelectorResolver.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/MethodSelectorResolver.java
- jupiter-tests/src/test/java/org/junit/jupiter/api/DisplayNameGenerationTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/api/IndicativeSentencesRuntimeEnclosingTypeScenarioOneTestCase.java
- jupiter-tests/src/test/java/org/junit/jupiter/api/IndicativeSentencesRuntimeEnclosingTypeScenarioTwoTestCase.java
- jupiter-tests/src/test/java/org/junit/jupiter/api/IndicativeSentencesRuntimeEnclosingTypeTestCase.java
- jupiter-tests/src/test/java/org/junit/jupiter/api/parallel/ResourceLockAnnotationTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/descriptor/CustomDisplayNameGenerator.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/descriptor/DisplayNameUtilsTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/descriptor/ExtensionContextTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/descriptor/JupiterTestDescriptorTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/descriptor/TestFactoryTestDescriptorTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/descriptor/TestTemplateInvocationTestDescriptorTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/descriptor/TestTemplateTestDescriptorTests.java
> Pass enclosing instance types to DisplayNameGenerators

- documentation/src/test/java/example/sharedresources/DynamicSharedResourcesDemo.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/parallel/ResourceLocksProvider.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ClassTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/MethodBasedTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/NestedClassTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ResourceLockAware.java
- jupiter-tests/src/test/java/org/junit/jupiter/api/parallel/ResourceLockAnnotationTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/api/parallel/ResourceLocksProviderTests.java
> Provide runtime enclosing instance types to ResourceLocksProviders

- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TempDirectory.java
- junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/extension/TempDirectoryPerDeclarationTests.java
- platform-tests/src/test/java/org/junit/platform/commons/util/ReflectionUtilsTests.java
The `@TempDir` annotation on a constructor parameter is copied to the
generated `final` instance field. This caused it top be picked up by
`TempDirectory` for instance field injection which then failed because
the field was `final`. This change now checks if a test class is an
instance of a record type and skips instance field injection. Since
records cannot have any instance fields besides the ones generated from
their constructor, there's no need to inject values into any of them.
> Support `@TempDir` constructor injection for Java record classes

- CONTRIBUTING.md
This PR adds a section to `CONTRIBUTING.md` that provides some basic instructions for getting started as a contributor that we can link to when the question is asked.
> Add "Getting Started" section

- documentation/src/docs/asciidoc/release-notes/release-notes-5.12.0-RC1.adoc
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TempDirectory.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/extension/TempDirectoryCleanupTests.java
- jupiter-tests/src/test/resources/junit-platform.properties
- jupiter-tests/src/test/resources/log4j2-test.xml
> Fix handling of Windows junctions during temp dir cleanup

- documentation/src/docs/asciidoc/release-notes/release-notes-5.12.0-RC2.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/io/TempDir.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TempDirectory.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/extension/CloseablePathTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/extension/TempDirectoryCleanupTests.java
> Warn when deleting symlinks targeting locations outside temp dir

- junit-jupiter-params/src/main/java/org/junit/jupiter/params/converter/DefaultArgumentConverter.java
- jupiter-tests/src/test/java/org/junit/jupiter/params/converter/DefaultArgumentConverterTests.java
- platform-tests/src/test/java/org/junit/platform/commons/support/conversion/ConversionSupportTests.java
Prior to this commit, `platform-tests` had no dedicated tests for `ConversionSupport`. Instead, `DefaultArgumentConverterTests` from `jupiter-tests` provided the corresponding coverage.
Now, string-based tests are moved to `ConversionSupportTests`, while `DefaultArgumentConverterTests` verify that the delegation to `ConversionSupport` happens correctly.
See https://github.com/junit-team/junit5/pull/4219#discussion_r1948126955.
For an easier review, here's the diff between `DefaultArgumentConverterTests` from `main` and `ConversionSupportTests` from this PR:
<details><summary>Diff</summary>
<p>
```diff
--- jupiter-tests/src/test/java/org/junit/jupiter/params/converter/DefaultArgumentConverterTests.java	2025-02-09 16:22:11
+++ platform-tests/src/test/java/org/junit/platform/commons/support/c …
```
> Move string-based argument conversion tests to `platform-test`

- documentation/src/docs/asciidoc/release-notes/release-notes-5.13.0-M1.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/ContainerTemplateInvocationContext.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/TestTemplateInvocationContext.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ContainerTemplateInvocationTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ContainerTemplateTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestMethodTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestTemplateInvocationTestDescriptor.java
- junit-jupiter-params/src/jmh/java/org/junit/jupiter/params/ParameterizedTestNameFormatterBenchmarks.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/ArgumentCountValidator.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/EvaluatedArgumentSet.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTestInvocationContext.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTestNameFormatter.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTestParameterResolver.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/ContainerTemplateInvocationTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/TestTemplateInvocationTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/params/ParameterizedTestIntegrationTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/params/ParameterizedTestNameFormatterTests.java
- **Evaluate `Arguments.get()` at most once**
- **Close all arguments, not just consumed ones**
- **Close all arguments, despite early failures**
---
---
> Close all arguments, despite trimming, wrapping, and early failures

- documentation/src/docs/asciidoc/user-guide/running-tests.adoc
> Overhaul Gradle section regarding dependency alignment

- documentation/src/docs/asciidoc/release-notes/index.adoc
- documentation/src/docs/asciidoc/release-notes/release-notes-5.12.1.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/ExtensionContext.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ClassExtensionContext.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ClassTemplateInvocationExtensionContext.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/DynamicExtensionContext.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/JupiterEngineExtensionContext.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/MethodBasedTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/MethodExtensionContext.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestTemplateExtensionContext.java
- junit-platform-commons/src/main/java/org/junit/platform/commons/support/AnnotationSupport.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/descriptor/ExtensionContextTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/params/ParameterizedTestExtensionTests.java
- **Link to correct method**
- **Create initial 5.12.1 release notes from template**
- **Introduce `ExtensionContext.getEnclosingTestClasses()`**
Resolves #4375.
---
---
> Introduce `ExtensionContext.getEnclosingTestClasses()`

- junit-platform-console-standalone/junit-platform-console-standalone.gradle.kts
Set stable module name for the standalone JAR file to `org.junit.platform.console.standalone`.
Closes #4079
---
---
> Set stable module name for the standalone JAR file

- junit-platform-engine/src/testFixtures/java/org/junit/platform/fakes/FaultyTestEngines.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/DiscoveryIssueCollector.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/listeners/discovery/AbortOnFailureLauncherDiscoveryListener.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/NestedTestClassesTests.java
- platform-tests/src/test/java/org/junit/platform/launcher/core/DefaultLauncherTests.java
- platform-tests/src/test/java/org/junit/platform/launcher/listeners/discovery/AbortOnFailureLauncherDiscoveryListenerTests.java
- platform-tests/src/test/java/org/junit/platform/launcher/listeners/discovery/LoggingLauncherDiscoveryListenerTests.java
Instead of aborting test discovery on the first problematic selector
resolution result, they are now converted to discovery issues with
`ERROR` severity and reported during execution.
Issue: https://github.com/junit-team/junit5/issues/242
---
---
> Report problematic selector resolution results as discovery issues

- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/AbstractOrderingVisitor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/ClassOrderingVisitor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/MethodOrderingVisitor.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/extension/OrderedMethodTests.java
- **Avoid recursing over test tree multiple times for class ordering**
- **Avoid knowledge of subclasses in base class**
---
---
> Optimize `ClassOrderingVisitor`

- documentation/src/docs/asciidoc/release-notes/release-notes-5.13.0-M1.adoc
- documentation/src/docs/asciidoc/user-guide/advanced-topics/testkit.adoc
- documentation/src/test/java/example/testkit/EngineTestKitDiscoveryDemo.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/DiscoveryIssueNotifier.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/LauncherDiscoveryResult.java
- junit-platform-testkit/src/main/java/org/junit/platform/testkit/engine/EngineDiscoveryResults.java
- junit-platform-testkit/src/main/java/org/junit/platform/testkit/engine/EngineTestKit.java
- jupiter-tests/src/test/java/org/junit/jupiter/api/DisplayNameGenerationTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/api/parallel/ResourceLockAnnotationTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/AbstractJupiterTestEngineTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/ClassTemplateInvocationTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/DefaultExecutionModeTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/DynamicNodeGenerationTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/NestedTestClassesTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/StandardTestClassTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/discovery/DiscoveryTests.java
- platform-tests/src/test/java/org/junit/platform/testkit/engine/EngineDiscoveryResultsIntegrationTests.java
The goal is to ease testing for discovery issues encountered by an
engine (see #242).
---
---
> Introduce `EngineTestKit` support for test discovery

- .github/workflows/cross-version.yml
- **Switch to GA release of JDK 24**
- **Remove Leyden EA build**
---
---
> Adjust CI builds to JDK 24 release

- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/DiscoverySelectorResolver.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/MethodSelectorResolver.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/discovery/EngineDiscoveryRequestResolution.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/discovery/SelectorResolver.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/MultipleTestableAnnotationsTests.java
- platform-tests/src/test/java/org/junit/platform/engine/support/discovery/EngineDiscoveryRequestResolverTests.java
> Report discovery issue for competing test method annotations

- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ClassTemplateTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/JupiterTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/DiscoverySelectorResolver.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/discovery/DiscoverySelectorResolverTests.java
Prior to this commit, the Jupiter engine would prune its
`TestDescriptor` tree prior to returning it to the `Launcher`. Since the
`Launcher` will later prune it anyway (after applying filters) that's
unnecessary. Removing it avoids iterating over the entire test tree once
more.
The side effect that `PostDiscoveryFilter` implementations may now see
`TestDescriptors` that would already have been pruned should not be
problematic as there is no contract that engines need to prune
themselves.
---
---
> Remove Jupiter's pre-pruning

- junit-platform-suite-engine/src/main/java/org/junit/platform/suite/engine/ClassSelectorResolver.java
- junit-platform-suite-engine/src/main/java/org/junit/platform/suite/engine/DiscoverySelectorResolver.java
- junit-platform-suite-engine/src/main/java/org/junit/platform/suite/engine/LifecycleMethodUtils.java
- junit-platform-suite-engine/src/main/java/org/junit/platform/suite/engine/SuiteTestDescriptor.java
- junit-platform-suite-engine/src/nativeImage/initialize-at-build-time
- platform-tests/src/test/java/org/junit/platform/suite/engine/BeforeAndAfterSuiteTests.java
- platform-tests/src/test/java/org/junit/platform/suite/engine/SuiteTestDescriptorTests.java
- platform-tests/src/test/java/org/junit/platform/suite/engine/testsuites/LifecycleMethodsSuites.java
> Report discovery issues for invalid suite lifecycle methods

- junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/ClassTemplateInvocationLifecycleMethod.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ClassBasedTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ClassTemplateTestDescriptor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/LifecycleMethodUtils.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/AfterParameterizedClassInvocation.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/BeforeParameterizedClassInvocation.java
- jupiter-tests/src/test/java/org/junit/jupiter/params/ParameterizedClassIntegrationTests.java
Declaring `Before`/`AfterParameterizedClassInvocation` in regular test
classes not annotated with `ParameterizedClass` now causes a discovery
issue with severity `ERROR` to be reported.
---
---
> Report discovery errors for ineffectual lifecycle methods

- documentation/src/docs/asciidoc/release-notes/release-notes-5.13.0-M2.adoc
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/execution/ParameterResolutionUtils.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/ResolverFacade.java
- platform-tooling-support-tests/platform-tooling-support-tests.gradle.kts
- platform-tooling-support-tests/projects/jupiter-starter/build.gradle.kts
- platform-tooling-support-tests/projects/jupiter-starter/gradle.properties
- platform-tooling-support-tests/projects/jupiter-starter/src/test/java/com/example/project/CalculatorParameterizedClassTests.java
- platform-tooling-support-tests/projects/jupiter-starter/src/test/resources/junit-platform.properties
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/AntStarterTests.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/GradleStarterTests.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/MavenStarterTests.java
- platform-tooling-support-tests/src/test/resources/platform/tooling/support/tests/AntStarterTests_snapshots/open-test-report.xml.snapshot
- platform-tooling-support-tests/src/test/resources/platform/tooling/support/tests/GradleStarterTests_snapshots/open-test-report.xml.snapshot
- platform-tooling-support-tests/src/test/resources/platform/tooling/support/tests/MavenStarterTests_snapshots/open-test-report.xml.snapshot
> Fix constructor invocation of `Nested` classes on Java versions < 21

- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/LifecycleMethodUtils.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/ClassSelectorResolver.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/DiscoverySelectorResolver.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/MethodSelectorResolver.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/predicates/IsNestedTestClass.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/predicates/IsTestClassWithTests.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/predicates/IsTestFactoryMethod.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/predicates/IsTestMethod.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/predicates/IsTestTemplateMethod.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/predicates/IsTestableMethod.java
- junit-platform-commons/src/main/java/org/junit/platform/commons/support/ModifierSupport.java
- junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/discovery/ClassContainerSelectorResolver.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/discovery/DiscoveryIssueReporter.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/discovery/EngineDiscoveryRequestResolver.java
- junit-platform-suite-engine/src/main/java/org/junit/platform/suite/engine/LifecycleMethodUtils.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/AbstractJupiterTestEngineTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/discovery/DiscoveryTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/discovery/predicates/IsTestClassWithTestsTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/discovery/predicates/IsTestFactoryMethodTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/discovery/predicates/IsTestMethodTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/discovery/predicates/IsTestTemplateMethodTests.java
- platform-tests/src/test/java/org/junit/platform/commons/support/ModifierSupportTests.java
- platform-tests/src/test/java/org/junit/platform/suite/engine/SuiteTestDescriptorTests.java
- **Report discovery issues for invalid testable methods**
- **Avoid reporting the same discovery issues multiple times**
---
---
> Report discovery issues for invalid testable methods

- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/ClassSelectorResolver.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/predicates/TestClassPredicates.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/discovery/DiscoveryTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/discovery/predicates/TestClassPredicatesTests.java
> Report discovery issue for missing `@Nested` annotations

- junit-jupiter-api/src/main/java/org/junit/jupiter/api/DisplayNameGenerator.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/DiscoveryIssue.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/DiscoveryIssueCollector.java
- jupiter-tests/src/test/java/org/junit/jupiter/api/DisplayNameGenerationTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/AbstractJupiterTestEngineTests.java
- platform-tests/src/test/java/org/junit/platform/launcher/core/DiscoveryIssueCollectorTests.java
> Report discovery issues for blank `@SentenceFragments`

- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/AbstractOrderingVisitor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/ClassOrderingVisitor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/DiscoverySelectorResolver.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/MethodOrderingVisitor.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/extension/OrderedClassTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/extension/OrderedMethodTests.java
- **Report discovery issues for ineffective `@Order` annotations**
- **Report discovery issues misbehaving orderers**
---
---
> Report discovery issues for class and method ordering

- documentation/src/docs/asciidoc/release-notes/index.adoc
- documentation/src/docs/asciidoc/release-notes/release-notes-5.12.2.adoc
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TempDirectory.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/extension/TempDirectoryCleanupTests.java
- **Add 5.12.2 release notes from template**
- **Fix handling of `CleanupMode.ON_SUCCESS`**
Fixes #4464.
---
---
> Fix handling of `CleanupMode.ON_SUCCESS`

- documentation/src/docs/asciidoc/user-guide/writing-tests.adoc
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/AnnotationBasedArgumentsProvider.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/FieldSource.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/MethodSource.java
Resolves https://github.com/junit-team/junit5/issues/4382
---
---
> Document that Streams returned from argument sources closed automatically

- gradle.properties
- platform-tooling-support-tests/projects/graalvm-starter/build.gradle.kts
- platform-tooling-support-tests/projects/graalvm-starter/settings.gradle.kts
Fix GraalVM setup on CI
---
---
> Detect GraalVM on CI via env var set by GitHub action

- documentation/src/docs/asciidoc/release-notes/release-notes-5.13.0-M3.adoc
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/EngineFilterer.java
- platform-tests/src/test/java/org/junit/platform/launcher/core/DefaultLauncherEngineFilterTests.java
- platform-tooling-support-tests/platform-tooling-support-tests.gradle.kts
Prior to this commit, an exception was only thrown when _none_ of a
filter's included IDs matched any engine. Now, an exception is thrown if
at least one included ID across all filters did not match any engine.
Related issue: #2824
---
---
> Make validation of including `EngineFilters` more strict

- documentation/src/docs/asciidoc/release-notes/release-notes-5.13.0-RC1.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/condition/AbstractJreCondition.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/condition/AbstractJreRangeCondition.java
- jupiter-tests/src/templates/resources/test/org/junit/jupiter/api/condition/DisabledOnJreIntegrationTests.java.jte
- jupiter-tests/src/templates/resources/test/org/junit/jupiter/api/condition/EnabledOnJreIntegrationTests.java.jte
- **Validate all versions in `@EnabledOnJre` and `@DisabledOnJre`**
- **Remove unreachable validation**
---
---
> Improve validation of JRE execution condition annotations

- .github/ISSUE_TEMPLATE/bug_report.md
- CONTRIBUTING.md
- README.md
- build.gradle.kts
- documentation/README.md
- documentation/src/docs/asciidoc/release-notes/index.adoc
- documentation/src/docs/asciidoc/user-guide/advanced-topics/engines.adoc
- documentation/src/docs/asciidoc/user-guide/advanced-topics/launcher-api.adoc
- documentation/src/docs/asciidoc/user-guide/api-evolution.adoc
- documentation/src/docs/asciidoc/user-guide/appendix.adoc
- documentation/src/docs/asciidoc/user-guide/index.adoc
- documentation/src/docs/asciidoc/user-guide/overview.adoc
- documentation/src/docs/asciidoc/user-guide/running-tests.adoc
- documentation/src/javadoc/junit-overview.html
- gradle/config/eclipse/junit-eclipse-formatter-settings.xml
- gradle/plugins/common/src/main/kotlin/junitbuild.java-library-conventions.gradle.kts
- junit-jupiter-migrationsupport/README.md
- junit-jupiter-migrationsupport/src/main/java/org/junit/jupiter/migrationsupport/rules/ExternalResourceSupport.java
- junit-jupiter-migrationsupport/src/main/java/org/junit/jupiter/migrationsupport/rules/VerifierSupport.java
- junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/TagFilter.java
- junit-platform-suite-api/src/main/java/org/junit/platform/suite/api/ExcludeTags.java
- junit-platform-suite-api/src/main/java/org/junit/platform/suite/api/IncludeTags.java
- platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/MemoryLeakTests.java
- platform-tooling-support-tests/platform-tooling-support-tests.gradle.kts
In preparation for 6.0
---
---
> Remove version 5 where possible

- .github/actions/run-gradle/action.yml
- gradle/plugins/build-parameters/build.gradle.kts
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/LauncherConstants.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/DefaultLauncher.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/DiscoveryIssueNotifier.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/EngineDiscoveryOrchestrator.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/EngineExecutionOrchestrator.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/LauncherPhase.java
- junit-platform-suite-engine/src/main/java/org/junit/platform/suite/engine/SuiteLauncher.java
- junit-platform-testkit/src/main/java/org/junit/platform/testkit/engine/EngineTestKit.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/AbstractJupiterTestEngineTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/TestInstanceLifecycleConfigurationTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/discovery/DiscoverySelectorResolverTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/discovery/DiscoveryTests.java
- platform-tests/src/test/java/org/junit/platform/jfr/FlightRecordingDiscoveryListenerIntegrationTests.java
- platform-tests/src/test/java/org/junit/platform/launcher/core/DefaultLauncherTests.java
- platform-tests/src/test/java/org/junit/platform/launcher/listeners/discovery/LoggingLauncherDiscoveryListenerTests.java
- platform-tests/src/test/java/org/junit/platform/testkit/engine/EngineDiscoveryResultsIntegrationTests.java
- platform-tests/src/test/java/org/junit/platform/testkit/engine/EngineTestKitTests.java
Users of the Launcher API that perform a discovery without executing the
resulting test plan are prone to accidentally hiding discovery issues
from their users unless they implement their own
`LauncherDiscoveryListener`. Therefore, the new
`junit.platform.discovery.issue.failure.phase` configuration parameter
allows configuring the `discovery` phase as the one that should fail in
case critical discovery issues are encountered. By default, they will
still be reported in the `execution` phase.
---
---
> Make phase that fails due to critical discovery issues configurable

- documentation/src/docs/asciidoc/release-notes/release-notes-6.0.0-M1.adoc
- junit-jupiter-api/junit-jupiter-api.gradle.kts
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertDoesNotThrow.java
- junit-jupiter-api/src/main/kotlin/org/junit/jupiter/api/Assertions.kt
- jupiter-tests/src/test/kotlin/org/junit/jupiter/api/KotlinAssertTimeoutAssertionsTests.kt
Since `Executable` is allowed/expected to throw exceptions, the
semantics of being called `EXACTLY_ONCE` are blurry because it might not
be executed entirely when throwing an exception. Since the Kotlin 2.1
compiler emits a warning for these parameters, we're relaxing their
contracts to be called `AT_MOST_ONCE` instead.
---
> Relax Kotlin contracts for `Executable` passed to `assertTimeout`

- junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java
- platform-tests/src/test/java/org/junit/platform/commons/util/ReflectionUtilsTests.java
Initially triggered by https://github.com/junit-team/junit5/pull/4557#discussion_r2105731215.
---
---
> Remove `null` support from `getWrapperType` input, add test coverage

- junit-platform-reporting/junit-platform-reporting.gradle.kts
- platform-tooling-support-tests/projects/graalvm-starter/settings.gradle.kts
- platform-tooling-support-tests/projects/jupiter-starter/build.gradle.kts
- platform-tooling-support-tests/projects/reflection-tests/build.gradle.kts
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/GraalVmStarterTests.java
Since the module descriptor requires it, it cannot be optional but must
be a regular dependency. Otherwise, using junit-platform-reporting on
the module path will fail.
---
---
> Make dependency on open-test-reporting-tooling-spi non-optional

- documentation/src/docs/asciidoc/release-notes/release-notes-5.13.0.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/ExtensionContext.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/AbstractExtensionContext.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/descriptor/ExtensionContextTests.java
Prior to this commit, both `TestReporter` and `ExtensionContext` threw
an exception when `publishDirectory` was called with an existing
directory. Now, they only attempt to create the directory if it doesn't
already exist.
---
---
> Allow publishing files to an existing directory

- junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java
> Remove short-circuiting to ensure all classes are checked for cycles

- documentation/src/docs/asciidoc/release-notes/release-notes-5.13.1.adoc
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/MethodOrderingVisitor.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/NestedTestClassesTests.java
In order to validate them, classpath scanning was changed to find them
in 5.13.0. However, that caused `@Nested` classes to be added to their
parent descriptors before their sibling test methods. This made the
order of execution in classes containing nested test classes dependent
on how they were discovered unless a `MethodOrderer` was configured in
which case `MethodOrderingVisitor` ensured test methods came before
`@Nested` test classes on the same level.
This commit changes `MethodOrderingVisitor` to also ensure this
ordering constraint in case no `MethodOrderer` is configured.
Resolves #4600.
---
I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-li …
> Ensure `@Nested` classes are executed after sibling test methods

- documentation/src/docs/asciidoc/release-notes/release-notes-5.13.1.adoc
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/support/AnnotationConsumerInitializer.java
- jupiter-tests/src/test/java/org/junit/jupiter/params/support/AnnotationConsumerInitializerTests.java
The `provideArguments(ExtensionContext, Annotation)` was deprecated in
5.13 and no longer taken into account when determining the consumed
annotation. Now, it is checked for again if the new method overload
couldn't be found.
Fixes #4610.
---
---
> Fix support for pre-5.13 `AnnotationBasedArgumentsProviders`

- junit-platform-commons/src/main/java/org/junit/platform/commons/support/AnnotationSupport.java
- junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java
- platform-tests/src/test/java/org/junit/platform/commons/util/ReflectionUtilsTests.java
The latter is easier to read, and it forbids list.add(...) at the compile-time.
See https://jspecify.dev/docs/user-guide/#wildcard-bounds
---
---
> chore: replace List<@Nullable Object> with List<?>

- documentation/src/docs/asciidoc/release-notes/release-notes-5.13.2.adoc
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/ClassSelectorResolver.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/predicates/TestClassPredicates.java
- junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/discovery/DiscoveryTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/discovery/predicates/TestClassPredicatesTests.java
- platform-tests/src/test/java/org/junit/platform/commons/util/ReflectionUtilsTests.java
- **Fix `StackOverflowError`**
- **Avoid discovery errors for inner classes not annotated with `@Nested`**
Resolves #4661.
---
---
> Avoid discovery errors for inner classes not annotated with `@Nested`

- documentation/src/docs/asciidoc/release-notes/release-notes-5.13.2.adoc
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/ClassSelectorResolver.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/NestedTestClassesTests.java
> Avoid reporting discovery warnings for abstract inner classes with tests

- junit-jupiter-api/src/main/java/org/junit/jupiter/api/io/TempDirFactory.java
Fix typo in `TempDirFactory` javadoc
---
---
> Fix typo in TempDirFactory javadoc

- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/ClassSelectorResolver.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/predicates/TestClassPredicates.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/NestedTestClassesTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/StaticNestedTestCase.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/TopLevelNestedTestCase.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/discovery/DiscoveryTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/discovery/predicates/TestClassPredicatesTests.java
Since the introduction of discovery issues in 5.13, top-level and static
member classes annotated with `@Nested` were no longer executed because
the validation logic excluded them. This commit restores the old
behavior and improves the generated discovery issues for such cases.
Fixes #4686.
---
---
> Run non-inner `@Nested` classes to restore backward compatibility

- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/HierarchicalTestExecutorService.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/NodeTestTask.java
Added TestTask::getTestDescriptor as described in the issue. A TestTask should always correspond to an specific test node, so making its descriptor public for further analysis in custom test engines could be useful.
Resolves #4711.
---
---
> Add `TestTask::getTestDescriptor` method

- documentation/src/docs/asciidoc/release-notes/release-notes-5.13.3.adoc
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/ClassOrderingVisitor.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/MethodOrderingVisitor.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/extension/OrderedClassTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/extension/OrderedMethodTests.java
> Improve message of discovery issues for ineffective `@Order` annotations

- documentation/src/docs/asciidoc/release-notes/release-notes-6.0.0-M2.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/ConditionEvaluationResult.java
- jupiter-tests/src/test/java/org/junit/jupiter/api/condition/ConditionEvaluationResultTests.java
This PR addresses the issues raised in #4698 by annotating all "reason" parameters with `@Nullable`.
- #4698
- #4715
> Support `@Nullable` reasons in `ConditionEvaluationResult` APIs

- documentation/src/docs/asciidoc/release-notes/release-notes-5.13.4.adoc
- gradle/plugins/common/src/main/kotlin/junitbuild.osgi-conventions.gradle.kts
... to maximize compatibility with older OSGi runtimes.
Resolves #4733.
---
---
> Remove `java.*` packages from `Import-Package` headers in all jars

- documentation/src/docs/asciidoc/release-notes/release-notes-6.0.0-M2.adoc
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/TestTemplateInvocationContextProvider.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/RepeatedTestExtension.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedClassContext.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedClassExtension.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTestContext.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTestExtension.java
For consistency with `ClassTemplateInvocationContextProvider` and to
make implementations simpler, this commit changes the return type of the
`provideTestTemplateInvocationContexts(ExtensionContext)` method of the
`TestTemplateInvocationContextProvider` interface to allow more concrete
`Streams` to be returned.
This change is source compatible, meaning implementations will still
compile when declaring `Stream<TestTemplateInvocationContext>` as method
return type. To check for binary compatibility, I used Pioneer's
`RetryingTestExtension` with a 6.0.0-SNAPSHOT that included this change.
The extension kept working. Nevertheless, I included this change as
potentially breaking in the release notes.
Resolves #3577.
---
I hereby agree to the terms of the [JUnit Contributor License …
> Allow `Stream<? extends TestTemplateInvocationContext>` return types

- documentation/src/docs/asciidoc/release-notes/release-notes-5.13.4.adoc
- junit-platform-engine/src/main/java/org/junit/platform/engine/discovery/ClasspathResourceSelector.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/descriptor/PackageSource.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/DiscoveryIssueCollector.java
- platform-tests/src/test/java/org/junit/platform/engine/discovery/DiscoverySelectorsTests.java
- platform-tests/src/test/java/org/junit/platform/engine/support/descriptor/PackageSourceTests.java
- platform-tests/src/test/java/org/junit/platform/launcher/core/DiscoveryIssueCollectorTests.java
> Fail on classpath resource names that are blank after removing leading slash

- documentation/src/docs/asciidoc/release-notes/release-notes-6.0.0-M2.adoc
- documentation/src/test/java/example/FirstCustomEngine.java
- documentation/src/test/java/example/SecondCustomEngine.java
- documentation/src/test/java/example/extensions/HttpServerExtension.java
- documentation/src/test/java/example/session/GlobalSetupTeardownListener.java
- junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/ExtensionContext.java
- junit-jupiter-api/src/testFixtures/java/org/junit/jupiter/api/fixtures/TrackLogRecords.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/execution/NamespaceAwareStore.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TempDirectory.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TimeoutExtension.java
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TimeoutInvocationFactory.java
- junit-jupiter-migrationsupport/src/main/java/org/junit/jupiter/migrationsupport/rules/ExpectedExceptionSupport.java
- junit-jupiter-migrationsupport/src/main/java/org/junit/jupiter/migrationsupport/rules/TestRuleSupport.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/ArgumentCountValidator.java
- junit-platform-engine/src/main/java/org/junit/platform/engine/support/store/NamespacedHierarchicalStore.java
- jupiter-tests/src/test/java/org/junit/jupiter/api/extension/Heavyweight.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/descriptor/ExtensionContextTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/execution/ExtensionContextStoreConcurrencyTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/execution/ExtensionContextStoreTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/extension/ExtensionContextExecutionTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/extension/TimeoutInvocationFactoryTests.java
- platform-tests/src/test/java/org/junit/platform/engine/support/store/NamespacedHierarchicalStoreTests.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/LocalMavenRepo.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/ManagedResource.java
- platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/OutputAttachingExtension.java
Since both `ExtensionContext.Store` and its backing
`NamespaceAwareStore` implementation allow storing `null` values, the
`getOrComputeIfAbsent` methods potentially returned `null`, even if
documented otherwise (in case of `getOrComputeIfAbsent(Class)` in
`ExtensionContext.Store`). Now that the API uses JSpecify's nullability
annotations, this became more apparent and also caused
Jupiter `Extension` implementations to have to deal with values being
potentially `null` despite their best intentions to only use
`getOrComputeIfAbsent` to access a certain `key` with a function that
never returned `null`. Therefore, this commit introduces null-safe
variants called `computeIfAbsent` that treat `null` as absent in
addition to the key not being present in the backing `Map`.
---
I hereby agree to …
> Add `computeIfAbsent` variants for non-nullable types to stores

- documentation/src/docs/asciidoc/release-notes/release-notes-5.13.4.adoc
- junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/AbstractExtensionContext.java
- jupiter-tests/src/test/java/org/junit/jupiter/engine/descriptor/ResourceAutoClosingTests.java
To avoid flooding console output with warnings.
Resolves #4776.
---
---
> Log only once per implementation type for `CloseableResource` types

- documentation/src/docs/asciidoc/release-notes/release-notes-6.0.0-RC1.adoc
- junit-platform-commons/src/main/java/org/junit/platform/commons/util/ExceptionUtils.java
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/StackTracePruningEngineExecutionListener.java
- platform-tests/src/test/java/org/junit/platform/StackTracePruningTests.java
Everything before the test method is invoked is not informative for the end user. Discarding that part of the stacktrace removes a few more uninformative frames.
Additionally, when pruning consider the source of the test descriptor not merely its ancestors.
Fixes: #4828
---
---
> Prune stack traces up to test or lifecycle method

- documentation/src/docs/asciidoc/release-notes/release-notes-6.0.0-RC1.adoc
- junit-platform-commons/src/main/java/org/junit/platform/commons/support/ReflectionSupport.java
- junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java
- platform-tests/src/test/java/org/junit/platform/commons/util/ReflectionUtilsTests.java
* The methods `findNestedClasses` and `streamNestedClasses` in
`ReflectionSupport` now return nested classes declared in the same
enclosing class or interface ordered in a deterministic but
intentionally nonobvious way.
* For consistency with test methods, `@Nested` classes declared in the
same enclosing class or interface are now ordered in a deterministic
but intentionally nonobvious way.
---
---
> Order nested classes declared in same enclosing type deterministically

- .jitpack.yml
- gradle/plugins/build-parameters/build.gradle.kts
- gradle/plugins/common/src/main/kotlin/junitbuild.java-library-conventions.gradle.kts
- gradle/plugins/common/src/main/kotlin/junitbuild.publishing-conventions.gradle.kts
- junit-bom/junit-bom.gradle.kts
* Use JitPack's version but replace commit sha and counter with SNAPSHOT
* Use JitPack's group and artifact ID
* Disable artifact signing
---
---
> Make artifacts built by JitPack consumable in Gradle or Maven projects

- documentation/src/docs/asciidoc/release-notes/release-notes-6.0.0-RC2.adoc
- junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/LauncherDiscoveryResult.java
- platform-tests/src/test/java/org/junit/platform/launcher/core/LauncherDiscoveryResultTests.java
Prior to this commit, `LauncherDiscoveryResult.retainEngines()` stored the pruned `LinkedHashMap` content in a `HashMap`, which sometimes resulted in different iteration order for pruned test engines.
To address that, this commit replaces the use of `Collectors.toMap(Function<? super T, ? extends K>, Function<? super T, ? extends U>)` -- which creates a `HashMap` -- with the use of `Collectors.toMap(Function<? super T, ? extends K>, Function<? super T, ? extends U>, BinaryOperator<U>, Supplier<M>)` -- which allows us to specify that the pruned test engines should be stored in a `LinkedHashMap` to retain the original iteration order.
Fixes #4862
> Retain original `TestEngine` order after pruning

- documentation/src/docs/asciidoc/release-notes/release-notes-6.0.0-RC3.adoc
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/DefaultParameterInfo.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterInfo.java
- junit-jupiter-params/src/main/java/org/junit/jupiter/params/ResolverFacade.java
- jupiter-tests/src/test/java/org/junit/jupiter/params/ParameterInfoIntegrationTests.java
- jupiter-tests/src/test/java/org/junit/jupiter/params/support/DeprecatedParameterInfoIntegrationTests.java
- platform-tooling-support-tests/src/archUnit/java/platform/tooling/support/tests/ArchUnitTests.java
> Relocate `ParameterInfo` to `params` package and deprecate old interface
