junit-console/src/main/java/org/junit/gen5/console/tasks/ColoredPrintingTestListener.java, junit-engine-api/src/main/java/org/junit/gen5/engine/EngineExecutionListener.java, junit-engine-api/src/main/java/org/junit/gen5/engine/HierarchicalTestEngine.java, junit-engine-api/src/main/java/org/junit/gen5/engine/TestExecutionResult.java, junit-launcher/src/main/java/org/junit/gen5/launcher/Launcher.java, junit-launcher/src/main/java/org/junit/gen5/launcher/TestExecutionListener.java, junit-launcher/src/main/java/org/junit/gen5/launcher/TestExecutionListenerRegistry.java, junit-launcher/src/main/java/org/junit/gen5/launcher/listeners/LoggingListener.java, junit-launcher/src/main/java/org/junit/gen5/launcher/listeners/SummaryCreatingTestListener.java, junit-tests/src/test/java/org/junit/gen5/engine/DummyEngineExecutionContext.java, junit-tests/src/test/java/org/junit/gen5/engine/DummyTestDescriptor.java, junit-tests/src/test/java/org/junit/gen5/engine/DummyTestEngine.java, junit-tests/src/test/java/org/junit/gen5/engine/junit5/StandardTestClassTest.java, junit-tests/src/test/java/org/junit/gen5/engine/junit5/TrackingEngineExecutionListener.java, junit4-launcher-runner/src/main/java/org/junit/gen5/junit4runner/JUnit5RunnerListener.java, surefire-junit5/src/main/java/org/junit/gen5/surefire/RunListenerAdapter.java
I've changed TestExecutionListener as proposed in #34. Documentation is still missing but I think merging this pull request would be beneficial for upcoming tasks.
=> Refined TestExecutionListener API

junit-console/src/main/java/org/junit/gen5/console/tasks/TestPlanSpecificationCreator.java, junit-engine-api/src/main/java/org/junit/gen5/engine/DiscoveryFilter.java, junit-engine-api/src/main/java/org/junit/gen5/engine/DiscoveryRequest.java, junit-engine-api/src/main/java/org/junit/gen5/engine/EngineIdFilter.java, junit-engine-api/src/main/java/org/junit/gen5/engine/FilterResult.java, junit-engine-api/src/main/java/org/junit/gen5/engine/GenericFilter.java, junit-engine-api/src/main/java/org/junit/gen5/engine/PostDiscoveryFilter.java, junit-engine-api/src/main/java/org/junit/gen5/engine/specification/AllClassFilters.java, junit-engine-api/src/main/java/org/junit/gen5/engine/specification/ClassNameFilter.java, junit-engine-api/src/main/java/org/junit/gen5/engine/specification/PredicateBasedClassFilter.java, junit-engine-api/src/main/java/org/junit/gen5/engine/specification/dsl/DiscoveryRequestBuilder.java, junit-engine-api/src/main/java/org/junit/gen5/engine/specification/dsl/EngineFilterBuilder.java, junit-engine-api/src/main/java/org/junit/gen5/engine/specification/dsl/NameBasedSelectorBuilder.java, junit-engine-api/src/main/java/org/junit/gen5/engine/specification/dsl/PackageSelectorBuilder.java, junit-engine-api/src/main/java/org/junit/gen5/engine/specification/dsl/TagFilterBuilder.java, junit-launcher/src/main/java/org/junit/gen5/launcher/Launcher.java, junit-tests/src/test/java/org/junit/gen5/console/tasks/TestPlanSpecificationCreatorTests.java, junit-tests/src/test/java/org/junit/gen5/engine/ClassFiltersTests.java, junit-tests/src/test/java/org/junit/gen5/engine/DiscoveryRequestBuilderTests.java, junit-tests/src/test/java/org/junit/gen5/engine/DiscoveryRequestTests.java, junit-tests/src/test/java/org/junit/gen5/engine/junit4/JUnit4TestEngineDiscoveryTests.java, junit-tests/src/test/java/org/junit/gen5/launcher/LauncherTests.java, junit4-engine/src/main/java/org/junit/gen5/engine/junit4/discovery/JUnit4DiscoveryRequestResolver.java, junit4-runner/src/main/java/org/junit/gen5/junit4/runner/JUnit5.java, junit5-engine/src/main/java/org/junit/gen5/engine/junit5/JUnit5TestEngine.java
This is merely a rebase of #119 onto master.
=> Rebase of #119

.github/PULL_REQUEST_TEMPLATE.md
-  Fix #164.
- Add PULL_REQUEST_TEMPLATE.md.
---
=> Add PULL_REQUEST_TEMPLATE.md.

junit-console/src/main/java/org/junit/gen5/console/ConsoleRunner.java, surefire-junit5/src/main/java/org/junit/gen5/surefire/JUnitGen5Provider.java
- Just simplify some point.
---
=> Just simplify some point.

junit-launcher/src/main/java/org/junit/gen5/launcher/main/Root.java
While reading this class I found parts of the code that required some time for understanding because the code was not as meaningful and/or readable as it could be. I rewrote it into code that is at least better readable for me. Hopefully this helps other readers, too.
---
=> Refactor code for readability.

junit5-api/src/main/java/org/junit/gen5/api/extension/ExtensionPointRegistry.java
- Delete unnecessary semicolon.
---
=> Delete unnecessary semicolon.

junit-launcher/src/main/java/org/junit/gen5/launcher/main/TestDiscoveryRequestBuilder.java, junit-tests/src/test/java/org/junit/gen5/launcher/main/TestDiscoveryRequestBuilderTests.java
Fix typo (remove surplus comma).
---
=> Fix typo (remove surplus comma).

junit-tests/src/test/java/org/junit/gen5/commons/util/StringUtilsTests.java
Micro tests for `StringUtils`. Prerequisite for merging #220.
---
=> Micro tests for StringUtils

junit-tests/src/test/java/org/junit/gen5/console/ConsoleRunnerTests.java, junit-tests/src/test/java/org/junit/gen5/engine/ExecutionEventConditions.java, junit-tests/src/test/java/org/junit/gen5/engine/junit5/discovery/DiscoverySelectorResolverTests.java
Remove import unused import statements.
---
Signed-off-by: Allon Mureinik <mureinik@gmail.com>
=> Remove unused imports

junit-tests/src/test/java/org/junit/gen5/engine/discovery/ClassFilterTests.java, junit-tests/src/test/java/org/junit/gen5/engine/junit5/execution/ExtensionValuesStoreTests.java, junit-tests/src/test/java/org/junit/gen5/engine/junit5/extension/ExtensionPointSortingTests.java
Removed unused imports from the same package.
---
Signed-off-by: Allon Mureinik <mureinik@gmail.com>
=> Remove redundant imports from the same package

junit5-api/src/main/java/org/junit/gen5/api/extension/ExtensionContext.java
=> Improve comment on 'ExtensionContext.Store::getOrComputeIfAbsent'

junit-tests/src/test/java/org/junit/gen5/engine/junit5/execution/FullLogging.java, junit-tests/src/test/java/org/junit/gen5/engine/junit5/execution/MethodInvokerTests.java, junit5-engine/src/main/java/org/junit/gen5/engine/junit5/extension/ExtensionRegistry.java
=> add micro tests for MethodInvoker

junit-engine-api/src/main/java/org/junit/gen5/engine/support/descriptor/DirectorySource.java, junit-engine-api/src/main/java/org/junit/gen5/engine/support/descriptor/FilePosition.java, junit-engine-api/src/main/java/org/junit/gen5/engine/support/descriptor/FileSource.java, junit-engine-api/src/main/java/org/junit/gen5/engine/support/descriptor/FileSystemSource.java, junit-engine-api/src/main/java/org/junit/gen5/engine/support/descriptor/JavaClassSource.java, junit-engine-api/src/main/java/org/junit/gen5/engine/support/descriptor/JavaMethodSource.java, junit-engine-api/src/main/java/org/junit/gen5/engine/support/descriptor/JavaPackageSource.java, junit-engine-api/src/main/java/org/junit/gen5/engine/support/descriptor/JavaSource.java, junit-engine-api/src/main/java/org/junit/gen5/engine/support/descriptor/UriSource.java, junit-tests/src/test/java/org/junit/gen5/engine/junit4/JUnit4TestEngineDiscoveryTests.java, junit-tests/src/test/java/org/junit/gen5/engine/support/discovery/FileSystemSourceTests.java, junit-tests/src/test/java/org/junit/gen5/engine/support/discovery/JavaSourceTests.java, junit-tests/src/test/java/org/junit/gen5/launcher/listener/SummaryGenerationTests.java, junit4-engine/src/main/java/org/junit/gen5/engine/junit4/descriptor/JUnit4TestDescriptor.java, junit4-engine/src/main/java/org/junit/gen5/engine/junit4/descriptor/RunnerTestDescriptor.java, junit5-engine/src/main/java/org/junit/gen5/engine/junit5/descriptor/ClassTestDescriptor.java, junit5-engine/src/main/java/org/junit/gen5/engine/junit5/descriptor/MethodTestDescriptor.java, surefire-junit5/src/main/java/org/junit/gen5/surefire/RunListenerAdapter.java
This is a Pull Request for #175 - Simplify TestSource class hierarchy.
- Refactoring of class structure for TestSource 
- Applied refactoring to production and test code
- Applied refactoring to surefire plugin
---
=> Simplify TestSource class hierarchy

junit-platform-engine/src/main/java/org/junit/platform/engine/TestEngine.java
Make all links of this sentence symmetric. The links to `discover` and `execute` contain the complete phrase, too.
---
=> Link complete phrase "discover an ID".

platform-tests/src/test/java/org/junit/platform/console/tasks/ExecuteTestsTaskTests.java
=> Improve ExecuteTestsTaskTests

data/events.json
=> Add talk at JavaZone 2016

documentation/src/docs/asciidoc/running-tests.adoc
=> Fix Surefire plugin group ID in documentation

documentation/src/test/java/example/TestingAStackDemo.java
=> Delete unused field.

documentation/src/test/java/example/TestingAStackDemo.java
Java 8 code should look like Java 8 code.
---
=> Use diamond operator for creating Stack objects.

documentation/src/test/java/example/TestingAStackDemo.java
Makes it easier for the reader to understand the purpose of the methods. Additionally it shows the reader of the user guide that they can use meaningful names for `@BeforeEach` methods.
---
=> Use meaningful names for @BeforeEach methods.

junit-platform-engine/src/main/java/org/junit/platform/engine/UniqueId.java
-
Remove redundant final of private method
---
=> Remove redundant final of private method

junit-platform-engine/src/main/java/org/junit/platform/engine/UniqueId.java
=> Fix comment

data/events.json, data/speakers.json
Updates to speakers.json and events.json to include our 2016 JavaOne presentation.
---
=> Add JavaOne 2016 Session

junit-platform-commons/src/main/java/org/junit/platform/commons/util/AnnotationUtils.java, junit-platform-commons/src/main/java/org/junit/platform/commons/util/ExceptionUtils.java, junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java
Simplified if-statement and removed explicit type arguments.
---
=> Small code maturity fixes

junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/JupiterTestDescriptor.java, junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/MethodTestDescriptor.java, junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/ExtensionRegistry.java, junit-platform-engine/src/main/java/org/junit/platform/engine/support/descriptor/AbstractTestDescriptor.java, junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/Node.java
=> A couple of small refactorings

junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/DefaultMethodTests.java, junit-platform-console/src/main/java/org/junit/platform/console/tasks/XmlReportWriter.java, junit-platform-engine/src/main/java/org/junit/platform/engine/discovery/DiscoverySelectors.java, junit-platform-engine/src/main/java/org/junit/platform/engine/discovery/JavaClassSelector.java, junit-platform-engine/src/main/java/org/junit/platform/engine/discovery/JavaMethodSelector.java, junit-platform-engine/src/main/java/org/junit/platform/engine/support/descriptor/JavaClassSource.java, junit-platform-engine/src/main/java/org/junit/platform/engine/support/descriptor/JavaMethodSource.java, junit-platform-runner/src/main/java/org/junit/platform/runner/JUnitPlatformTestTree.java, junit-platform-surefire-provider/src/main/java/org/junit/platform/surefire/provider/RunListenerAdapter.java, junit-vintage-engine/src/test/java/org/junit/vintage/engine/VintageTestEngineDiscoveryTests.java, platform-tests/src/test/java/org/junit/platform/engine/discovery/DiscoverySelectorsTests.java, platform-tests/src/test/java/org/junit/platform/engine/support/descriptor/JavaSourceTests.java
This pull requests solves the following issues:
- Store raw values in DiscoverySelectors & TestSources #489
- Cannot select default method by fully qualified method name #516
- Non-standard method names are not supported for discovery selection #477
---
=> Pull request for Raw Value in DiscoverySelectors

build.gradle, gradle/wrapper/gradle-wrapper.properties
Upgrade to Gradle 3.2
See https://discuss.gradle.org/t/gradle-3-2-released/20441
Fixes UTF-8 emission bug described in the realm of #524 -- explicitly here https://github.com/junit-team/junit5/issues/369#issuecomment-246772931
---
=> Upgrade to Gradle 3.2

documentation/src/docs/asciidoc/release-notes-5.0.0-M3.adoc, documentation/src/docs/asciidoc/running-tests.adoc, junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/DiscoveryFilterApplier.java, junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/DiscoveryFilterApplierTests.java, junit-platform-console/src/main/java/org/junit/platform/console/options/AvailableOptions.java, junit-platform-console/src/main/java/org/junit/platform/console/options/CommandLineOptions.java, junit-platform-console/src/main/java/org/junit/platform/console/tasks/DiscoveryRequestCreator.java, junit-platform-engine/src/main/java/org/junit/platform/engine/discovery/ExcludePackageNameFilter.java, junit-platform-engine/src/main/java/org/junit/platform/engine/discovery/IncludePackageNameFilter.java, junit-platform-engine/src/main/java/org/junit/platform/engine/discovery/PackageNameFilter.java, junit-platform-engine/src/main/java/org/junit/platform/engine/support/filter/ClasspathScanningSupport.java, junit-platform-gradle-plugin/src/main/groovy/org/junit/platform/gradle/plugin/JUnitPlatformPlugin.groovy, junit-platform-gradle-plugin/src/main/groovy/org/junit/platform/gradle/plugin/PackagesExtension.groovy, junit-platform-gradle-plugin/src/test/groovy/org/junit/platform/gradle/plugin/JUnitPlatformPluginSpec.groovy, junit-platform-runner/src/main/java/org/junit/platform/runner/ExcludePackages.java, junit-platform-runner/src/main/java/org/junit/platform/runner/IncludePackages.java, junit-platform-runner/src/main/java/org/junit/platform/runner/JUnitPlatform.java, platform-tests/src/test/java/org/junit/platform/console/options/JOptSimpleCommandLineOptionsParserTests.java, platform-tests/src/test/java/org/junit/platform/console/tasks/DiscoveryRequestCreatorTests.java, platform-tests/src/test/java/org/junit/platform/engine/discovery/PackageNameFilterTests.java, platform-tests/src/test/java/org/junit/platform/runner/JUnitPlatformRunnerTests.java
=> PackageNameFilter for including and excluding package names

documentation/src/docs/asciidoc/index.adoc, documentation/src/docs/asciidoc/launcher-api.adoc, documentation/src/docs/asciidoc/release-notes-5.0.0-M4.adoc
Initial documentation for #583 done in User Guide and Release Notes.
---
=> Document auto-loading custom test execution listeners.

junit-platform-surefire-provider/src/main/java/org/junit/platform/surefire/provider/JUnitPlatformProvider.java
- Remove unused constant `static final String EXCEPTION_MESSAGE_NO_ENGINE `
- Fix typo change 'pararameters' to 'parameters'
---
=> Remove unused constant EXCEPTION_MESSAGE_NO_ENGINE and fix typo

junit-platform-surefire-provider/src/main/java/org/junit/platform/surefire/provider/JUnitPlatformProvider.java
=> Use functional expressions for Optionals in JUnitPlatformProvider

data/events.json
=> Add various talks about JUnit 5

assets/js/events.js, data/events.json
=> Add "event" to event list

documentation/src/docs/asciidoc/running-tests.adoc
Replace outdated output example with "condensed" test execution tree, partly copied from https://junit.ci.cloudbees.com/job/JUnit5/lastBuild/consoleFull
---
=> Update console launcher output showing new default tree details

gradle.properties
=> update assertj to 3.7.0 for java 9 compatibility (#775)

documentation/src/docs/asciidoc/release-notes-5.0.0-M5.adoc, documentation/src/docs/asciidoc/writing-tests.adoc, documentation/src/test/java/example/ParameterizedTestDemo.java, junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/EnumArgumentsProvider.java, junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/EnumSource.java, junit-jupiter-params/src/test/java/org/junit/jupiter/params/provider/EnumArgumentsProviderTests.java, junit-jupiter-params/src/test/java/org/junit/jupiter/params/provider/EnumSourceTests.java
=> Add enum constant selection mode attribute to EnumSource

gradle.properties
assertj v3.8.0 basically contains some bug fixes, see http://joel-costigliola.github.io/assertj/assertj-core-news.html#assertj-core-3.8.0 for details.
---
---
=> update assertj to v3.8.0

documentation/src/test/java/example/AssertionsDemo.java
Add example of multiple assertions in one code block. Can be used for dependent assertions.
Based on issue #896.
=> example of multiple assertions in one codeblock

junit-vintage-engine/src/main/java/org/junit/vintage/engine/discovery/UniqueIdSelectorResolver.java
Improve readability of the resolve method by extracting methods `isNotEngineId`,`isForVintageEngine` and `loadTestClass`.
---
---
=> Extract isNotEngineId and isForVintageEngine.

junit-vintage-engine/src/main/java/org/junit/vintage/engine/descriptor/VintageTestDescriptor.java
Improve readability of getTags()
---
---
=> Improve readability of getTags()

documentation/src/docs/asciidoc/release-notes-5.0.0-M6.adoc
Add Java 9 compatibility documentation
---
=> Add Java 9 compatibility documentation

junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/DefaultMethodTests.java, junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java, platform-tests/src/test/java/org/junit/platform/commons/util/ReflectionUtilsTests.java
Return only visible default methods
Addresses #978
---
=> Return only visible default methods

junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/execution/ExtensionValuesStore.java
Previously, the class was holding a lock while calling the
function passed to getOrComputeIfAbsent(), which can cause problems
if the function is slow or blocks. In addition, the coarse-grained
locks make the class more prone to contentions when the Store is
accessed from multiple threads.
---
---
=> Make ExtensionValuesStore concurrent.

README.md
Describe and enumerate `Automatic-Module-Name` JAR attributes in a prominent location: `README.md`
---
=> Describe Automatic-Module-Name JAR attributes

documentation/src/docs/asciidoc/release-notes-5.0.0-RC3.adoc, documentation/src/docs/asciidoc/running-tests.adoc, junit-platform-console/src/main/java/org/junit/platform/console/options/AvailableOptions.java, junit-platform-console/src/main/java/org/junit/platform/console/options/CommandLineOptions.java, junit-platform-console/src/main/java/org/junit/platform/console/options/KeyValuePairConverter.java, junit-platform-console/src/main/java/org/junit/platform/console/tasks/DiscoveryRequestCreator.java, junit-platform-gradle-plugin/src/main/groovy/org/junit/platform/gradle/plugin/JUnitPlatformExtension.groovy, junit-platform-gradle-plugin/src/main/groovy/org/junit/platform/gradle/plugin/JUnitPlatformPlugin.groovy, junit-platform-gradle-plugin/src/test/groovy/org/junit/platform/gradle/plugin/JUnitPlatformPluginSpec.groovy, junit-platform-surefire-provider/src/main/java/org/junit/platform/surefire/provider/JUnitPlatformProvider.java, junit-platform-surefire-provider/src/test/java/org/junit/platform/surefire/provider/JUnitPlatformProviderTests.java, platform-tests/src/test/java/org/junit/platform/console/options/JOptSimpleCommandLineOptionsParserTests.java, platform-tests/src/test/java/org/junit/platform/console/tasks/DiscoveryRequestCreatorTests.java
Implementation for #1015.
---
---
=> Introduce support for configuration parameters in console launcher and build plugins

documentation/src/docs/asciidoc/release-notes-5.1.0-M1.adoc, junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ClassTestDescriptor.java, junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/TestInstanceLifecycleTests.java
=> Create test instance after evaluating conditions

documentation/src/test/kotlin/example/AssertionsDemoKotlin.kt, junit-jupiter-api/src/main/kotlin/org/junit/jupiter/api/Assertions.kt
=> Add assertAll consuming Collection<()->Unit> in Kotlin

documentation/README.md
Fix described output for the html files and add a note for the
requirement of the graphviz package to avoid errors on build.
---
---
=> Update documentation build instructions

documentation/src/docs/asciidoc/extensions.adoc
Added two sections detailing annotation and reflection support, paraphrasing the javadoc.
---
=> #1132 Add annotation and reflection sections to supported utilities section

documentation/src/docs/asciidoc/running-tests.adoc
Updating User Docs to include updated information about Eclipse IDE support 
Closes #1199 
---
---
=> Update User Docs IDE Support info 

junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/DynamicContainerTestDescriptor.java, junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/DynamicNodeTestDescriptor.java, junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/DynamicTestTestDescriptor.java, junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/JupiterEngineDescriptor.java, junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/JupiterTestDescriptor.java, junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/execution/JupiterEngineExecutionContext.java, junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/EngineExecutionContext.java, junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/HierarchicalTestExecutor.java, junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/Node.java, platform-tests/src/test/java/org/junit/jupiter/extensions/Heavyweight.java, platform-tests/src/test/java/org/junit/jupiter/extensions/HeavyweightAlphaTests.java, platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/HierarchicalTestExecutorTests.java
=> Refactor HierarchicalTestExecutor

.travis.yml, gradle.properties, platform-tests/platform-tests.gradle, platform-tests/src/jmh/java/org/junit/jupiter/jmh/AssertionsBenchmarks.java
Addresses https://github.com/junit-team/junit5/pull/1260#issuecomment-360400653 _"[...] I'd like to see some micro-benchmarks that verify that this is a real issue. Can you use JMH to do that?"_
---
---
=> Introduce JMH-based benchmarks

documentation/src/docs/asciidoc/release-notes/release-notes-5.1.0-M2.adoc, documentation/src/docs/asciidoc/user-guide/writing-tests.adoc, documentation/src/test/java/example/EnabledIfTestsDemo.java, junit-jupiter-api/src/main/java/org/junit/jupiter/api/EnabledIf.java, junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/EnabledIfCondition.java, junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/ExtensionRegistry.java, junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/EnabledIfConditionTests.java, junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/ExtensionRegistryTests.java, platform-tests/src/test/java/org/junit/jupiter/extensions/EnabledIfTests.java
Supply a JavaScript script controlling whether the annotated container or test is executed.
Closes #219
---
---
=> Introduce @EnabledIf execution condition

src/install/install-jdk.sh
copy paste typos are the best typos
see also https://github.com/junit-team/junit5-samples/pull/59
---
=> Declare proper JDK version in example usage of the install script

data/events.json, data/speakers.json
=> Include talk in MadridJUG (Java User Group) by Boni Garcia on 16.01.2018

data/events.json, data/speakers.json
---
---
- [] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass
=> Adding new speakers and events

data/events.json, data/speakers.json
Adding information about my conversation on heisenbug conf
see: https://heisenbug-piter.ru/en/talks/2018/spb/sncgtn5gisoswks6owgwq/
=> Adding information about my conversation on heisenbug conf

build.gradle
Update checkStyle toolversion from 8.8 to 8.9 in line 210
---
---
=> Update checkStyle toolversion

documentation/documentation.gradle
See release notes at http://jruby.org/2018/04/23/jruby-9-1-17-0
---
---
=> Upgrade to JRuby 9.1.17.0

CONTRIBUTING.md
Added a link to Mockito's repo.
I'm not sure if the items from Definition of Done should be checked for this case.
---
---
=> Add link to Mockito

documentation/src/docs/asciidoc/release-notes/index.adoc, documentation/src/docs/asciidoc/release-notes/release-notes-5.3.0-M1.adoc
=> Create release note template for 5.3.0-M1

build.gradle
Upgrade some dependencies.
org.ajoberstar:gradle-git-publish:0.4.1
org.junit.platform:junit-platform-gradle-plugin:1.2.0
checkstyle toolVersion 8.10
---
---
=> Upgrade some dependencies

documentation/documentation.gradle
=> Upgrade to fast-classpath-scanner 2.20

README.md
Clarified invocation of gradlew. Otherwise newbies get confused, try to search/install a 'gradlew' from the Internet - a waste of time.
=> Clarified invocation of gradlew on Unix and Windows

junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/DefaultLauncherConfig.java, junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/LauncherConfig.java, junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/LauncherFactory.java, platform-tests/src/test/java/org/junit/platform/launcher/core/LauncherConfigBuilderTests.java, platform-tests/src/test/java/org/junit/platform/launcher/core/LauncherFactoryTests.java
The pull request addresses the feature request in #767.
---
---
=> Introduce LauncherConfig for configuring engines and listeners

data/events.json, data/speakers.json
"Spock vs JUnit 5 - Clash of the Titans" by Marcin Zajączkowski
https://jdd.org.pl/lecture.html#id=47734
=> [Event] Add JUnit 5 event at JDD 2018

data/events.json, data/speakers.json
=> gh-pages: added Droidcon NY

documentation/src/docs/asciidoc/link-attributes.adoc, documentation/src/docs/asciidoc/user-guide/overview.adoc
1. I added kotlin, ant and groovy projects to the JUnit Jupiter Sample Projects section. 2 files were changed. 
2. Let me know if more changes needs to be done.
---
---
=> #1542 Issue Fix : Update JUnit Jupiter Sample Projects section of User Guide

documentation/src/docs/asciidoc/user-guide/writing-tests.adoc, documentation/src/test/java/example/defaultmethods/ComparableContract.java
I'm not sure which is appropriate English, `larger number` or `bigger number` ;-p
---
=> Refine the user guide and example

junit-jupiter-api/src/main/java/org/junit/jupiter/api/parallel/Resources.java
=> Introduce LOCALE and TIME_ZONE constants in Resources

documentation/src/test/java/example/AssertionsDemo.java, documentation/src/test/java/example/AssumptionsDemo.java, documentation/src/test/java/example/DynamicTestsDemo.java, documentation/src/test/java/example/FirstJUnit5Tests.java, documentation/src/test/java/example/HamcrestAssertionDemo.java, documentation/src/test/java/example/ParameterizedTestDemo.java, documentation/src/test/java/example/testinterface/TestInterfaceDemo.java, documentation/src/test/java/example/testinterface/TestInterfaceDynamicTestsDemo.java, documentation/src/test/java/example/util/Calculator.java, documentation/src/test/java/example/util/StringUtils.java
This pull request is created to update the examples in the official documentation.
Issue: #1651
- Added sample Calculator class
---
---
=> Use realistic examples in User Guide

documentation/src/docs/asciidoc/release-notes/release-notes-5.4.0-M1.adoc, junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/ExtensionContext.java, junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/TestInstances.java, junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ClassExtensionContext.java, junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ClassTestDescriptor.java, junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/JupiterEngineExtensionContext.java, junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/MethodExtensionContext.java, junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/NestedClassTestDescriptor.java, junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestMethodTestDescriptor.java, junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestTemplateExtensionContext.java, junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestTemplateTestDescriptor.java, junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/execution/DefaultTestInstances.java, junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/execution/JupiterEngineExecutionContext.java, junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/execution/TestInstancesProvider.java, junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/TestInstanceLifecycleTests.java, junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/execution/DefaultTestInstancesTests.java, junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/execution/ExtensionContextTests.java, junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/execution/JupiterEngineExecutionContextTests.java, junit-jupiter-params/src/test/java/org/junit/jupiter/params/ParameterizedTestExtensionTests.java, junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java, platform-tests/src/test/java/org/junit/platform/commons/util/ReflectionUtilsTests.java
=> Introduce ExtensionContext.getTestInstances() API

documentation/src/docs/asciidoc/release-notes/release-notes-5.4.0-RC1.adoc, documentation/src/docs/asciidoc/user-guide/writing-tests.adoc, junit-jupiter-api/src/main/java/org/junit/jupiter/api/support/io/TempDirectory.java, junit-jupiter-engine/src/test/java/org/junit/jupiter/api/support/io/TempDirectoryTests.java
=> Ensure TempDirectory can return a File

data/events.json, data/speakers.json
Added a [JUnit 5 event](https://cfp.devoxx.fr/2019/talk/TPC-2275) at [Devoxx France 2019](https://www.devoxx.fr/).
---
=> [Event] Add JUnit 5 event

data/events.json
My talk "Spock vs JUnit 5 - Clash of the Titans" at [Greach](https://agenda.greachconf.com/talk/spock-vs-junit5-clash-of-the-titans).
=> [Event] Add talk at Greach 2019

data/events.json
=> ghpages: added hamburg event next week

data/events.json
Adding a JUnit related talk at [Voxxed Days Luxembourg](https://cfp-voxxed-lux.yajug.org/talk/MCB-0767) in June :)
=> [Event] Add JUnit talk at Voxxed Days Luxembourg

platform-tooling-support-tests/src/main/java/platform/tooling/support/Helper.java
=> [Cleanup] Simplify use of if(Optional.isPresent()) using functional style

junit-jupiter-api/src/module/org.junit.jupiter.api/module-info.java, junit-jupiter-params/src/module/org.junit.jupiter.params/module-info.java, junit-platform-testkit/src/module/org.junit.platform.testkit/module-info.java, platform-tooling-support-tests/projects/jar-describe-module/junit-jupiter-api.expected.txt, platform-tooling-support-tests/projects/jar-describe-module/junit-jupiter-params.expected.txt, platform-tooling-support-tests/projects/jar-describe-module/junit-platform-testkit.expected.txt, platform-tooling-support-tests/src/main/java/platform/tooling/support/Helper.java, platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/GradleStarterTests.java, platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/ModularUserGuideTests.java
=> Improve module descriptor directives

documentation/src/docs/asciidoc/release-notes/release-notes-5.5.0-M2.adoc, junit-platform-engine/src/main/java/org/junit/platform/engine/support/descriptor/MethodSource.java, platform-tests/src/test/java/org/junit/platform/engine/support/descriptor/MethodSourceTests.java
Implementation for Issue: #1893
---
---
=> Add MethodSource.from(String, String, Class<?>...)

junit-jupiter-migrationsupport/src/main/java/org/junit/jupiter/migrationsupport/rules/TestRuleSupport.java
Details in commit messages
---
---
=> Tiny cleanup in TestRuleSupport

settings.gradle.kts
=> Remove misleading comment

.github/workflows/experimental.yml, .github/workflows/main.yml
To resolve errors when building PRs.
=> Remove fetch depth when cloning Git repo

platform-tests/src/test/java/org/junit/platform/commons/util/GenericClassHierarchiesReflectionUtilsTests.java, platform-tests/src/test/java/org/junit/platform/commons/util/ReflectionUtilsTests.java
This adds addition test cases as specified in #981 
---
---
=> Added additional test cases for issue #981

data/events.json
=> JFall 2019 added

.github/workflows/main.yml, gradle.properties, junit-jupiter-engine/src/test/java/org/junit/jupiter/api/AssertTimeoutAssertionsTests.java, platform-tooling-support-tests/platform-tooling-support-tests.gradle.kts
Trying to speed-up GitHub Actions builds.
=> Run Gradle with --parallel in GitHub Actions

junit-jupiter-api/src/module/org.junit.jupiter.api/module-info.java, junit-jupiter-engine/src/module/org.junit.jupiter.engine/module-info.java, junit-jupiter-migrationsupport/src/module/org.junit.jupiter.migrationsupport/module-info.java, junit-jupiter-params/src/module/org.junit.jupiter.params/module-info.java, junit-jupiter/src/module/org.junit.jupiter/module-info.java, junit-platform-commons/src/module/org.junit.platform.commons/module-info.java, junit-platform-console/src/module/org.junit.platform.console/module-info.java, junit-platform-engine/src/module/org.junit.platform.engine/module-info.java, junit-platform-launcher/src/module/org.junit.platform.launcher/module-info.java, junit-platform-reporting/src/module/org.junit.platform.reporting/module-info.java, junit-platform-suite-api/src/module/org.junit.platform.suite.api/module-info.java, junit-platform-testkit/src/module/org.junit.platform.testkit/module-info.java, junit-vintage-engine/src/module/org.junit.vintage.engine/module-info.java, platform-tooling-support-tests/projects/jar-describe-module/junit-jupiter-engine.expected.txt, platform-tooling-support-tests/projects/jar-describe-module/junit-jupiter-migrationsupport.expected.txt, platform-tooling-support-tests/projects/jar-describe-module/junit-jupiter-params.expected.txt, platform-tooling-support-tests/projects/jar-describe-module/junit-platform-console.expected.txt, platform-tooling-support-tests/projects/jar-describe-module/junit-platform-engine.expected.txt, platform-tooling-support-tests/projects/jar-describe-module/junit-platform-launcher.expected.txt, platform-tooling-support-tests/projects/jar-describe-module/junit-platform-reporting.expected.txt, platform-tooling-support-tests/projects/jar-describe-module/junit-platform-testkit.expected.txt, platform-tooling-support-tests/projects/jar-describe-module/junit-vintage-engine.expected.txt
Revise module declarations
Closes #2063
---
---
=> Revise module declarations

.github/workflows/cross-version.yml, .github/workflows/main.yml, settings.gradle.kts
=> Handle missing secrets on PR builds from forks

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/java-library-conventions.gradle.kts, buildSrc/src/main/kotlin/shadow-conventions.gradle.kts, gradle/wrapper/gradle-wrapper.properties, gradlew.bat, junit-jupiter-params/junit-jupiter-params.gradle.kts, junit-platform-console-standalone/junit-platform-console-standalone.gradle.kts, junit-platform-console/junit-platform-console.gradle.kts, platform-tooling-support-tests/projects/jar-describe-module/junit-jupiter-params.expected.txt, platform-tooling-support-tests/projects/jar-describe-module/junit-platform-console.expected.txt, platform-tooling-support-tests/src/main/java/platform/tooling/support/Helper.java, platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/JarDescribeModuleTests.java, platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/ManifestTests.java, settings.gradle.kts
=> Upgradle to 6.2.1

buildSrc/src/main/kotlin/Versions.kt
=> Upgrade Picocli to 4.2.0

build.gradle.kts
Signed-off-by: Sebastian Davids <sdavids@gmx.de>
Fix https://github.com/junit-team/junit5/issues/2261
---
---
=> Fix dirMode and fileMode for JARs

.github/workflows/cross-version.yml, buildSrc/build.gradle.kts, gradle.properties
=> Upgrade to bnd 5.1.0

gradle.properties
=> Update mockito version to 3.4.2

platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/ParallelExecutionIntegrationTests.java
=> Reduce wait time to speed up tests

documentation/src/docs/asciidoc/user-guide/extensions.adoc
=> Document composed extension annotations

_includes/junit5-sponsoring.md, assets/css/main.scss
Replace inline script by standard `<a>...</a>` element.
=> Tweak HTML syntax

.github/workflows/cross-version.yml, buildSrc/src/main/kotlin/java-toolchain-conventions.gradle.kts, platform-tooling-support-tests/platform-tooling-support-tests.gradle.kts
=> Let Gradle find Java 8 toolchain

.github/workflows/cross-version.yml, .github/workflows/main.yml, .github/workflows/reproducible-build.yml, platform-tooling-support-tests/platform-tooling-support-tests.gradle.kts, platform-tooling-support-tests/src/main/java/platform/tooling/support/Helper.java, platform-tooling-support-tests/src/test/java/platform/tooling/support/HelperTests.java
Since Gradle supports SDKMAN out of the box.
=> Remove custom env vars for toolchains

.github/workflows/codeql-analysis.yml, .github/workflows/cross-version.yml, .github/workflows/main.yml, .github/workflows/reproducible-build.yml, .lgtm.yml, README.md, build.gradle.kts, buildSrc/src/main/kotlin/JavaLibraryExtension.kt, buildSrc/src/main/kotlin/java-toolchain-conventions.gradle.kts, junit-jupiter-engine/src/test/java/org/junit/jupiter/api/AssertLinesMatchAssertionsTests.java, settings.gradle.kts
=> Build test code with Java 15

data/events.json, data/speakers.json
@marcphilipp suggested that I add our talk to the presentations list. I'm not sure where the final rendered pages are or how to produce them so that I can verify the result looks correct though.
cc @bjhargrave, @rotty3000
=> Added osgi-test EclipseCon 2020 presentation

junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ExtensionUtils.java
=> Use built-in comparator

junit-jupiter-engine/src/test/java/org/junit/jupiter/api/extension/ExtensionComposabilityTests.java
See https://bugs.openjdk.java.net/browse/JDK-8159746 for details.
=> Expect only non-static methods in extension composability tests

.github/workflows/cross-version.yml, buildSrc/src/main/kotlin/java-toolchain-conventions.gradle.kts, documentation/src/docs/asciidoc/release-notes/release-notes-5.7.1.adoc, junit-jupiter-api/src/main/java/org/junit/jupiter/api/condition/JRE.java, junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/DisabledForJreRangeConditionTests.java, junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/DisabledForJreRangeIntegrationTests.java, junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/DisabledOnJreConditionTests.java, junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/DisabledOnJreIntegrationTests.java, junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/EnabledForJreRangeConditionTests.java, junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/EnabledForJreRangeIntegrationTests.java, junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/EnabledOnJreConditionTests.java, junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/EnabledOnJreIntegrationTests.java
=> Add JRE.JAVA_17

settings.gradle.kts
Prior to this commit, only members of the JUnit team were able to
publish build scans because ge.junit.org was configured as server and
requires authentication. Now, CI builds for external branches publish
scans to scans.gradle.com and contributors can manually publish scans
by specifying Gradle's `--scan` option and accepting Gradle's terms and
conditions.
=> Allow publishing build scans to scans.gradle.com

gradle.properties
=> Update Gradle Enterprise Gradle Plugin to 3.5.2

gradle.properties
=> Update to Gradle Enterprise Gradle Plugin 3.6.1

documentation/src/docs/asciidoc/user-guide/running-tests.adoc
=> Improvements to build tool docs section

gradle/libs.versions.toml
just waiting for CI's verdict...
=> Update ArchUnit to 0.18.0

.github/workflows/codeql-analysis.yml, .github/workflows/main.yml, .github/workflows/reproducible-build.yml
Update our Java setup for GH Actions.
=> Use actions/setup-java@v2

.github/workflows/cross-version.yml, .github/workflows/main.yml, gradle.properties
Use download-java and setup-java actions instead.
=> Stop using custom Docker image

platform-tooling-support-tests/projects/multi-release-jar/default/pom.xml
=> Bump Maven Plugin versions

documentation/documentation.gradle.kts, documentation/src/docs/asciidoc/user-guide/running-tests.adoc, junit-platform-console-standalone/junit-platform-console-standalone.gradle.kts
=> Add list of shadowed artifacts to JAR and user guide

settings.gradle.kts
=> Update Gradle Enterprise plugins

buildSrc/build.gradle.kts
The title says it all.
---
---
=> Fix indentation in buildSrc/build.gradle.kts

.github/workflows/cross-version.yml, documentation/src/docs/asciidoc/release-notes/release-notes-5.9.0-M1.adoc, gradle.properties, junit-jupiter-api/src/main/java/org/junit/jupiter/api/condition/JRE.java, junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/DisabledForJreRangeConditionTests.java, junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/DisabledForJreRangeIntegrationTests.java, junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/DisabledOnJreConditionTests.java, junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/DisabledOnJreIntegrationTests.java, junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/EnabledForJreRangeConditionTests.java, junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/EnabledForJreRangeIntegrationTests.java, junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/EnabledOnJreConditionTests.java, junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/EnabledOnJreIntegrationTests.java
=> Add JRE.JAVA_20

documentation/src/docs/asciidoc/release-notes/release-notes-5.9.0-M2.adoc, junit-platform-engine/src/main/java/org/junit/platform/engine/ExecutionRequest.java
=> Add a public factory method to instantiate ExecutionRequest

documentation/src/docs/asciidoc/release-notes/release-notes-5.9.0-M2.adoc, junit-platform-commons/src/main/java/org/junit/platform/commons/util/CloseablePath.java, platform-tests/src/test/java/org/junit/platform/commons/util/ClasspathScannerTests.java
=> Allow scanning classpath concurrently

README.md
=> Document need to install JDK 8 on Silicon Macs

documentation/src/docs/asciidoc/user-guide/advanced-topics/launcher-api.adoc, junit-platform-launcher/src/main/java/org/junit/platform/launcher/TestExecutionListener.java
=> Document how `TestExecutionListener` are called

.github/workflows/combine-prs.yml, gradle/libs.versions.toml, gradle/plugins/common/build.gradle.kts, settings.gradle.kts
✅ The following pull requests have been successfully combined on this PR:
- #3212 Bump github/combine-prs from 2.0.3 to 2.1.0
- #3211 Bump org.apache.groovy:groovy from 4.0.7 to 4.0.10
- #3210 Bump com.gradle:gradle-enterprise-gradle-plugin from 3.12.4 to 3.12.6
- #3208 Bump com.gradle.enterprise from 3.12.4 to 3.12.6
- #3207 Bump xmlunit from 2.9.0 to 2.9.1
> This PR was created by the [`github/combine-prs`](https://github.com/github/combine-prs) action
=> Combined PRs

documentation/src/docs/asciidoc/release-notes/release-notes-5.10.0-M1.adoc, documentation/src/docs/asciidoc/user-guide/advanced-topics/launcher-api.adoc, junit-platform-launcher/src/main/java/org/junit/platform/launcher/LauncherConstants.java, junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/EngineExecutionOrchestrator.java, platform-tests/src/test/java/org/junit/platform/launcher/core/DefaultLauncherTests.java
=> Introduce dry-run execution mode

documentation/src/docs/asciidoc/user-guide/writing-tests.adoc
=> Add missing space in user guide

documentation/src/docs/asciidoc/release-notes/release-notes-5.10.0-M1.adoc, junit-jupiter-api/src/main/java/org/junit/jupiter/api/condition/MethodBasedCondition.java, junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/DisabledIfConditionClassLoaderTests.java, junit-jupiter-engine/src/test/java/org/junit/jupiter/api/condition/EnabledIfConditionClassLoaderTests.java, junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/MethodArgumentsProvider.java, junit-jupiter-params/src/test/java/org/junit/jupiter/params/provider/MethodArgumentsProviderTests.java
=> Revised PR for #3279 and #3292 - custom class loader arrangements

documentation/src/docs/asciidoc/release-notes/release-notes-5.10.0-RC1.adoc, documentation/src/docs/asciidoc/user-guide/writing-tests.adoc, junit-jupiter-api/src/main/java/org/junit/jupiter/api/io/TempDirFactory.java
=> Add thread-safety details to TempDirFactory documentation

documentation/documentation.gradle.kts, gradle/libs.versions.toml
=> Fix component diagram

.github/actions/main-build/action.yml, .github/actions/run-gradle/action.yml, .github/workflows/main.yml
see https://github.com/gradle/gradle-build-action#github-dependency-graph-support
=> Submit GitHub dependency graph from main CI build

junit-jupiter-api/src/main/java/org/junit/jupiter/api/io/TempDirFactory.java, junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/extension/TempDirectoryPerContextTests.java
=> Set prefix to 'junit-' in standard TempDirFactory

junit-platform-commons/src/main/java/org/junit/platform/commons/util/PackageUtils.java, junit-platform-console/src/main/java/org/junit/platform/console/options/AnsiColorOptionMixin.java, junit-platform-console/src/main/java/org/junit/platform/console/options/BannerOptionMixin.java, junit-platform-console/src/main/java/org/junit/platform/console/options/BaseCommand.java, junit-platform-console/src/main/java/org/junit/platform/console/options/CommandFacade.java, junit-platform-console/src/main/java/org/junit/platform/console/options/DiscoverTestsCommand.java, junit-platform-console/src/main/java/org/junit/platform/console/options/ExecuteTestsCommand.java, junit-platform-console/src/main/java/org/junit/platform/console/options/MainCommand.java, junit-platform-console/src/main/java/org/junit/platform/console/options/ManifestVersionProvider.java, junit-platform-engine/src/main/java/org/junit/platform/engine/TestEngine.java, platform-tooling-support-tests/src/main/java/platform/tooling/support/ThirdPartyJars.java, platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/StandaloneTests.java
=> Use module version of Console Launcher when on module path

.github/workflows/cross-version.yml, gradle.properties
Release notes: https://github.com/openjdk/leyden/tree/leyden-ea1-release-notes
---
---
=> Include Project Leyden in JDK matrix

.github/renovate.json5
=> Ignore Eclipse JDT 4.33.0

.github/renovate.json5
- **Delete Eclipse JDT rule**
- **Reference org-level config preset**
=> Polish Renovate config

documentation/src/docs/asciidoc/release-notes/release-notes-5.11.3.adoc, junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/Extensions.java, jupiter-tests/src/test/java/org/junit/jupiter/engine/extension/ExtensionRegistrationViaParametersAndFieldsTests.java, platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/ArchUnitTests.java
=> Allow repeating `ExtendWith` annotation on fields and parameters

.github/workflows/ossf-scorecard.yml
=> Add workflow to run OpenSSF scorecard checks

platform-tests/src/test/java/org/junit/platform/reporting/open/xml/OpenTestReportGeneratingListenerTests.java
=> Re-enable test disabled due to resolved JDK issue

gradle/libs.versions.toml
Reverts junit-team/junit5#4234 due to diffplug/spotless#2389
=> Revert "Update plugin spotless to v7"

RELEASING.md
Document the steps involved in doing a release as a checklist.
=> Document release steps as a checklist

documentation/src/docs/asciidoc/user-guide/running-tests.adoc
=> Recommend using a recent version of Maven Surefire/Failsafe

junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ClassBasedTestDescriptor.java, junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/JupiterTestDescriptor.java, junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/MethodBasedTestDescriptor.java, junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/Validatable.java, junit-jupiter-engine/src/nativeImage/initialize-at-build-time, jupiter-tests/src/test/java/org/junit/jupiter/engine/discovery/DiscoveryTests.java
- **Report discovery issues for invalid tag syntax on class level**
- **Report discovery issues for invalid tag syntax on method level**
---
---
=> Report discovery issues for invalid tag syntax

documentation/src/docs/asciidoc/release-notes/release-notes-6.0.0-M1.adoc, gradle/libs.versions.toml, platform-tooling-support-tests/projects/gradle-kotlin-extensions/build.gradle.kts, platform-tooling-support-tests/projects/kotlin-coroutines/build.gradle.kts
=> Update Kotlin to 2.2.0-RC

gradle/libs.versions.toml
Reverts junit-team/junit-framework#4754
=> Revert "Update dependency com.google.jimfs:jimfs to v1.3.1"

README.md
=> Update README badges to version 6
